"""Stage 04: deterministic release communication artifacts.

Generates changelog.md and notes.md from upstream audit/plan artifacts.
Idempotent. No source mutations. No network.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
STAGE_DIR = REPO_ROOT / "release" / "04_communicate"
AUDIT = REPO_ROOT / "release" / "01_audit" / "audit.json"
PLAN = REPO_ROOT / "release" / "02_plan" / "plan.json"


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def main() -> int:
    if not AUDIT.exists() or not PLAN.exists():
        raise FileNotFoundError("missing upstream audit or plan artifact")

    audit = _read_json(AUDIT)
    plan = _read_json(PLAN)
    if not audit.get("ok") or not plan.get("ok"):
        raise RuntimeError("upstream artifacts indicate failure")

    version = plan.get("version_candidate", "unknown")
    summary = plan.get("scope_summary", "")
    files = audit.get("changed_files", [])
    flags = audit.get("risk_flags", [])

    changelog = "\n".join([
        f"# Release {version}",
        "",
        "## Summary",
        summary or "No changes detected.",
        "",
        "## Changed Files",
        "\n".join(f"- {path}" for path in files) if files else "- None",
        "",
        "## Risk Flags",
        "\n".join(f"- {flag}" for flag in flags) if flags else "- None",
        "",
    ]) + "\n"

    notes = "\n".join([
        f"# Release Notes {version}",
        "",
        "This release was generated by the deterministic Hermes ICM pipeline.",
        "",
        f"Changed files: {len(files)}",
        f"Risk flags: {', '.join(flags) if flags else 'none'}",
        "",
        "Validation gates:",
        "\n".join(f"- {gate}" for gate in plan.get("validation_gates", [])),
        "",
    ]) + "\n"

    (STAGE_DIR / "changelog.md").write_text(changelog)
    (STAGE_DIR / "notes.md").write_text(notes)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
