from __future__ import annotations

PAGE_SCRIPT = """const PRODUCT_UI=__PRODUCT_UI_CONFIG__,darkIcon='__DARK_ICON__',lightIcon='__LIGHT_ICON__';
const $=id=>document.getElementById(id);
const state={session:null,conversation:[],chatSessionId:null,isStreaming:false,adminUsers:[],signupLink:""};
const themeToggle=$("themeToggle"),logoutButton=$("logoutButton"),authMessage=$("authMessage"),sessionChip=$("sessionChip"),chatCard=$("chatCard"),workspaceCard=$("workspaceCard"),adminCard=$("adminCard"),chatLog=$("chatLog"),chatForm=$("chatForm"),chatInput=$("chatInput"),chatSubmit=$("chatSubmit"),chatMessage=$("chatMessage"),adminUsersTable=$("adminUsersTable"),adminMessage=$("adminMessage"),adminCreateUserForm=$("adminCreateUserForm"),adminUsername=$("adminUsername"),adminDisplayName=$("adminDisplayName"),adminEmail=$("adminEmail"),adminCreateUserButton=$("adminCreateUserButton"),adminCreateSignupLinkButton=$("adminCreateSignupLinkButton"),adminSignupTokenCard=$("adminSignupTokenCard"),adminSignupTokenUrl=$("adminSignupTokenUrl"),adminCopySignupLinkButton=$("adminCopySignupLinkButton");
function esc(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;")}
function fmt(value){const text=String(value||"");let out="",cursor=0;while(cursor<text.length){const open=text.indexOf("**",cursor);if(open===-1){out+=esc(text.slice(cursor));break}const close=text.indexOf("**",open+2);if(close===-1){out+=esc(text.slice(cursor));break}out+=esc(text.slice(cursor,open));out+=`<strong>${esc(text.slice(open+2,close))}</strong>`;cursor=close+2}return out}
function setMessage(node,text,kind="neutral"){if(!node)return;node.textContent=text||"";node.classList.remove("is-error");if(kind==="error")node.classList.add("is-error")}
async function api(path,options={}){const response=await fetch(path,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(response.status===204)return null;const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||data.error||"Request failed");return data}
function signedIn(){return Boolean(state.session&&state.session.authenticated&&state.session.user)}
function isAdmin(){return Boolean(signedIn()&&state.session.user.is_admin)}
function renderSession(){const session=state.session;const signed=Boolean(session&&session.authenticated&&session.user);$("authCard").hidden=signed;chatCard.hidden=!signed;workspaceCard.hidden=!signed;adminCard.hidden=!isAdmin();logoutButton.hidden=!signed;sessionChip.hidden=!signed;if(!signed){sessionChip.textContent="";state.adminUsers=[];state.signupLink="";renderChat();renderAdmin();return}const user=session.user;const label=user.name||user.preferred_username||user.sub;sessionChip.textContent=isAdmin()?`${label} · Admin`:label;renderChat();renderAdmin()}
function renderChat(){const signed=signedIn();chatInput.disabled=!signed||state.isStreaming;chatSubmit.disabled=!signed||state.isStreaming||!chatInput.value.trim();if(!signed){chatLog.innerHTML='<div class="empty-state">Sign in to open your chat.</div>';return}if(!state.conversation.length){chatLog.innerHTML='<div class="empty-state">No messages yet.</div>';return}chatLog.innerHTML=state.conversation.map(message=>{const role=message.role==="user"?"user":"assistant";if(message.pending){if(message.answerText){return `<article class="chat-bubble assistant"><span class="chat-role">Agent</span><div class="chat-content">${fmt(message.answerText)}</div></article>`}return `<article class="chat-bubble reasoning"><span class="chat-role">Reasoning</span><div class="reasoning-stack"><div class="reasoning-text">${esc(String(message.reasoningText||""))}</div></div></article>`}if(role==="user"){return `<article class="chat-bubble user"><span class="chat-role">You</span><div class="chat-content">${fmt(message.content||"")}</div></article>`}return `<article class="chat-bubble assistant"><span class="chat-role">Agent</span><div class="chat-content">${fmt(message.content||"")}</div></article>`}).join("");chatLog.scrollTop=chatLog.scrollHeight}
function renderAdmin(){adminSignupTokenCard.hidden=!state.signupLink;if(adminSignupTokenUrl)adminSignupTokenUrl.textContent=state.signupLink||"";if(!isAdmin()){adminUsersTable.innerHTML='<tr><td colspan="4" class="muted-cell">Admin access required.</td></tr>';return}if(!state.adminUsers.length){adminUsersTable.innerHTML='<tr><td colspan="4" class="muted-cell">No product users yet.</td></tr>';return}const currentUserId=state.session?.user?.id||state.session?.user?.sub||"";adminUsersTable.innerHTML=state.adminUsers.map(user=>{const status=user.disabled?'<span class="table-badge is-danger">Disabled</span>':'<span class="table-badge">Active</span>';const action=user.id===currentUserId?'<span class="table-badge">You</span>':user.disabled?'<span class="table-badge">Inactive</span>':`<button class="button secondary-button admin-deactivate-button" data-user-id="${esc(user.id)}" type="button">Deactivate</button>`;const email=user.email?esc(user.email):'<span class="muted-cell">Not set in product</span>';return `<tr><td><strong>${esc(user.display_name||user.username)}</strong><br><span class="muted-cell">${esc(user.username)}</span></td><td>${email}</td><td>${status}</td><td><div class="table-actions">${action}</div></td></tr>`}).join("")}
async function refreshSession(){try{state.session=await api("/api/auth/session")}catch(error){state.session=null;setMessage(authMessage,error.message,"error")}renderSession()}
async function refreshChatSession(){if(!signedIn()){state.conversation=[];state.chatSessionId=null;renderChat();return}try{const payload=await api("/api/chat/session");state.chatSessionId=payload.session_id;state.conversation=payload.messages||[];setMessage(chatMessage,"")}catch(error){state.conversation=[];state.chatSessionId=null;setMessage(chatMessage,error.message,"error")}renderChat()}
async function refreshAdminUsers(){if(!isAdmin()){state.adminUsers=[];renderAdmin();return}try{const payload=await api("/api/admin/users");state.adminUsers=payload.users||[];setMessage(adminMessage,"")}catch(error){state.adminUsers=[];setMessage(adminMessage,error.message,"error")}renderAdmin()}
async function refreshAll(){await refreshSession();await refreshChatSession();await refreshAdminUsers()}
async function streamChatTurn(userMessage){const response=await fetch("/api/chat/turn/stream",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","Accept":"text/event-stream"},body:JSON.stringify({user_message:userMessage})});if(!response.ok||!response.body){let detail="Request failed";try{const payload=await response.json();detail=payload.detail||detail}catch{}throw new Error(detail)}const reader=response.body.getReader();const decoder=new TextDecoder();let buffer="",eventName="message",dataLines=[];const dispatch=(name,payload)=>{if(name==="start"){state.chatSessionId=payload.session_id||state.chatSessionId;return}if(name==="reasoning"){const pending=state.conversation[state.conversation.length-1];const chunk=String(payload.delta||"");if(pending&&pending.pending&&chunk){pending.reasoningText=`${pending.reasoningText||""}${chunk}`.replace(/\\s+/g," ").trim();renderChat()}return}if(name==="answer"){const pending=state.conversation[state.conversation.length-1];const chunk=String(payload.delta||"");if(pending&&pending.pending&&chunk){pending.answerText=`${pending.answerText||""}${chunk}`;renderChat()}return}if(name==="final"){state.chatSessionId=payload.session_id||state.chatSessionId;state.conversation=payload.messages||[];renderChat();return}if(name==="error"){throw new Error(payload.detail||"Stream failed")}};while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let boundary=buffer.indexOf("\\n\\n");while(boundary!==-1){const rawEvent=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);for(const line of rawEvent.split(/\\r?\\n/)){if(!line)continue;if(line.startsWith("event:")){eventName=line.slice(6).trim();continue}if(line.startsWith("data:")){dataLines.push(line.slice(5).trimStart())}}if(dataLines.length){dispatch(eventName,JSON.parse(dataLines.join("\\n")))}eventName="message";dataLines=[];boundary=buffer.indexOf("\\n\\n")}if(done)break}}
themeToggle.addEventListener("click",()=>{document.body.classList.toggle("dark");const isDark=document.body.classList.contains("dark");themeToggle.innerHTML=isDark?lightIcon:darkIcon;themeToggle.setAttribute("aria-label",isDark?"Toggle light mode":"Toggle dark mode")});
logoutButton.addEventListener("click",async()=>{try{await api("/api/auth/logout",{method:"POST"})}catch(error){setMessage(authMessage,error.message,"error")}state.session=null;state.conversation=[];state.chatSessionId=null;state.isStreaming=false;state.adminUsers=[];state.signupLink="";renderSession()});
chatInput.addEventListener("input",()=>{chatSubmit.disabled=!chatInput.value.trim()||state.isStreaming});
chatForm.addEventListener("submit",async event=>{event.preventDefault();const message=chatInput.value.trim();if(!message)return;if(!signedIn()){setMessage(chatMessage,"Please sign in first.","error");return}state.conversation.push({role:"user",content:message},{role:"assistant",content:"",pending:true,reasoningText:"",answerText:""});chatInput.value="";state.isStreaming=true;renderChat();setMessage(chatMessage,"Streaming response...");try{await streamChatTurn(message);setMessage(chatMessage,"Response received.")}catch(error){state.conversation=state.conversation.filter(message=>!message.pending);setMessage(chatMessage,error.message,"error");await refreshChatSession()}finally{state.isStreaming=false;renderChat()}});
adminCreateUserForm.addEventListener("submit",async event=>{event.preventDefault();const username=adminUsername.value.trim();const displayName=adminDisplayName.value.trim();const email=adminEmail.value.trim();if(!username||!displayName){setMessage(adminMessage,"Username and display name are required.","error");return}adminCreateUserButton.disabled=true;adminCreateSignupLinkButton.disabled=true;try{await api("/api/admin/users",{method:"POST",body:JSON.stringify({username:username,display_name:displayName,email:email||null})});adminUsername.value="";adminDisplayName.value="";adminEmail.value="";setMessage(adminMessage,"User created.");await refreshAdminUsers()}catch(error){setMessage(adminMessage,error.message,"error")}finally{adminCreateUserButton.disabled=false;adminCreateSignupLinkButton.disabled=false}});
adminCreateSignupLinkButton.addEventListener("click",async()=>{adminCreateSignupLinkButton.disabled=true;adminCreateUserButton.disabled=true;try{const payload=await api("/api/admin/signup-tokens",{method:"POST"});state.signupLink=payload.signup_url||"";renderAdmin();setMessage(adminMessage,"Signup link created.")}catch(error){setMessage(adminMessage,error.message,"error")}finally{adminCreateSignupLinkButton.disabled=false;adminCreateUserButton.disabled=false}});
adminCopySignupLinkButton.addEventListener("click",async()=>{if(!state.signupLink)return;try{await navigator.clipboard.writeText(state.signupLink);setMessage(adminMessage,"Signup link copied.")}catch(error){setMessage(adminMessage,"Could not copy the signup link.","error")}});
adminUsersTable.addEventListener("click",async event=>{const target=event.target;if(!(target instanceof HTMLElement))return;const button=target.closest(".admin-deactivate-button");if(!(button instanceof HTMLElement))return;const userId=button.getAttribute("data-user-id")||"";if(!userId)return;button.setAttribute("disabled","disabled");try{await api(`/api/admin/users/${encodeURIComponent(userId)}/deactivate`,{method:"POST"});setMessage(adminMessage,"User deactivated.");await refreshAdminUsers()}catch(error){setMessage(adminMessage,error.message,"error")}finally{button.removeAttribute("disabled")}});
refreshAll();"""
