"""Tic-Tac-Toe game server — play against Hermes Agent via browser.

Starts a local HTTP server that serves a web-based tic-tac-toe game.
The agent's moves are generated by the LLM, with minimax fallback
for reliability.

Usage from CLI:
    /play tictactoe
"""

import json
import http.server
import os
import random
import socketserver
import threading
import time
import webbrowser
from typing import Optional, Callable

PORT = 8642
_server_instance: Optional[socketserver.TCPServer] = None
_agent_move_fn: Optional[Callable] = None


# ---------------------------------------------------------------------------
# Minimax fallback (used when LLM is unavailable or returns invalid move)
# ---------------------------------------------------------------------------

def _check_winner(board: list) -> Optional[str]:
    """Return 'X', 'O', or None."""
    lines = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8],  # rows
        [0, 3, 6], [1, 4, 7], [2, 5, 8],  # cols
        [0, 4, 8], [2, 4, 6],              # diags
    ]
    for a, b, c in lines:
        if board[a] and board[a] == board[b] == board[c]:
            return board[a]
    return None


def _minimax(board: list, is_maximizing: bool) -> int:
    winner = _check_winner(board)
    if winner == "O":
        return 1
    if winner == "X":
        return -1
    if all(cell is not None for cell in board):
        return 0

    if is_maximizing:
        best = -2
        for i in range(9):
            if board[i] is None:
                board[i] = "O"
                best = max(best, _minimax(board, False))
                board[i] = None
        return best
    else:
        best = 2
        for i in range(9):
            if board[i] is None:
                board[i] = "X"
                best = min(best, _minimax(board, True))
                board[i] = None
        return best


def _get_minimax_move(board: list) -> int:
    """Get the best move for O using minimax."""
    best_score = -2
    best_move = -1
    for i in range(9):
        if board[i] is None:
            board[i] = "O"
            score = _minimax(board, False)
            board[i] = None
            if score > best_score:
                best_score = score
                best_move = i
    return best_move


# ---------------------------------------------------------------------------
# LLM-based move
# ---------------------------------------------------------------------------

def _get_llm_move(board: list, agent_move_fn: Callable) -> Optional[int]:
    """Ask the LLM for its move. Returns cell index (0-8) or None on failure."""
    display = ""
    for i in range(9):
        cell = board[i] if board[i] else str(i)
        display += f" {cell} "
        if i % 3 < 2:
            display += "|"
        if i % 3 == 2 and i < 8:
            display += "\n---+---+---\n"

    empty = [i for i in range(9) if board[i] is None]
    prompt = (
        f"We're playing Tic-Tac-Toe. You are O, I am X.\n\n"
        f"Current board (empty cells show their index 0-8):\n{display}\n\n"
        f"Available positions: {empty}\n\n"
        f"Reply with ONLY a single digit (0-8) for your move. Nothing else."
    )

    try:
        response = agent_move_fn(prompt)
        if response:
            # Extract first digit from response
            for char in response.strip():
                if char.isdigit() and int(char) in empty:
                    return int(char)
    except Exception:
        pass
    return None


# ---------------------------------------------------------------------------
# HTTP Handler
# ---------------------------------------------------------------------------

_HTML_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Hermes Agent - Tic Tac Toe</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'SF Mono', 'Fira Code', 'JetBrains Mono', monospace;
    background: #0a0a0f;
    color: #e0e0e0;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    overflow: hidden;
  }
  .container {
    text-align: center;
    position: relative;
    z-index: 1;
  }
  h1 {
    font-size: 1.6rem;
    margin-bottom: 0.3rem;
    background: linear-gradient(135deg, #d4af37, #f5d77a, #d4af37);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    letter-spacing: 2px;
  }
  .subtitle {
    color: #666;
    font-size: 0.85rem;
    margin-bottom: 1.5rem;
  }
  .board {
    display: grid;
    grid-template-columns: repeat(3, 110px);
    grid-template-rows: repeat(3, 110px);
    gap: 4px;
    margin: 0 auto 1.5rem auto;
    background: #d4af37;
    padding: 4px;
    border-radius: 12px;
    box-shadow: 0 0 40px rgba(212, 175, 55, 0.15);
    width: fit-content;
  }
  .cell {
    width: 110px;
    height: 110px;
    background: #12121a;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 2.8rem;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s;
    border: none;
    color: #e0e0e0;
  }
  .cell:first-child { border-radius: 8px 0 0 0; }
  .cell:nth-child(3) { border-radius: 0 8px 0 0; }
  .cell:nth-child(7) { border-radius: 0 0 0 8px; }
  .cell:nth-child(9) { border-radius: 0 0 8px 0; }
  .cell:hover:not(.taken):not(.game-over) {
    background: #1a1a2a;
  }
  .cell.taken { cursor: default; }
  .cell.x { color: #6ec6ff; }
  .cell.o { color: #d4af37; }
  .cell.win { animation: pulse 0.6s ease-in-out infinite alternate; }
  @keyframes pulse {
    from { background: #12121a; }
    to { background: #2a2a1a; }
  }
  .status {
    font-size: 1.1rem;
    min-height: 2rem;
    margin-bottom: 1rem;
    color: #999;
  }
  .status.thinking {
    color: #d4af37;
    animation: dots 1.5s infinite;
  }
  @keyframes dots {
    0%, 20% { content: '.'; }
    40% { content: '..'; }
    60%, 100% { content: '...'; }
  }
  .btn {
    padding: 10px 28px;
    font-size: 0.95rem;
    font-family: inherit;
    background: transparent;
    color: #d4af37;
    border: 1px solid #d4af37;
    border-radius: 6px;
    cursor: pointer;
    transition: all 0.2s;
    letter-spacing: 1px;
  }
  .btn:hover {
    background: #d4af37;
    color: #0a0a0f;
  }
  .score {
    display: flex;
    justify-content: center;
    gap: 2rem;
    margin-bottom: 1.2rem;
    font-size: 0.9rem;
  }
  .score span { color: #666; }
  .score .you { color: #6ec6ff; }
  .score .hermes { color: #d4af37; }
  .particles {
    position: fixed;
    top: 0; left: 0;
    width: 100%; height: 100%;
    pointer-events: none;
    z-index: 0;
  }
  .particle {
    position: absolute;
    width: 2px; height: 2px;
    background: #d4af37;
    border-radius: 50%;
    opacity: 0.3;
    animation: float linear infinite;
  }
  @keyframes float {
    from { transform: translateY(100vh); opacity: 0; }
    10% { opacity: 0.3; }
    90% { opacity: 0.3; }
    to { transform: translateY(-10px); opacity: 0; }
  }
</style>
</head>
<body>

<div class="particles" id="particles"></div>

<div class="container">
  <h1>HERMES AGENT</h1>
  <p class="subtitle">Tic Tac Toe</p>

  <div class="score">
    <span>You (<span class="you">X</span>): <span id="scoreX">0</span></span>
    <span>Hermes (<span class="hermes">O</span>): <span id="scoreO">0</span></span>
    <span>Draw: <span id="scoreD">0</span></span>
  </div>

  <div class="board" id="board"></div>
  <div class="status" id="status">Your turn</div>
  <button class="btn" id="resetBtn" onclick="resetGame()">New Game</button>
</div>

<script>
const board = Array(9).fill(null);
let gameOver = false;
let scores = { X: 0, O: 0, D: 0 };

const boardEl = document.getElementById('board');
const statusEl = document.getElementById('status');

// Create cells
for (let i = 0; i < 9; i++) {
  const cell = document.createElement('div');
  cell.className = 'cell';
  cell.dataset.index = i;
  cell.addEventListener('click', () => handleClick(i));
  boardEl.appendChild(cell);
}

// Particles
const particlesEl = document.getElementById('particles');
for (let i = 0; i < 30; i++) {
  const p = document.createElement('div');
  p.className = 'particle';
  p.style.left = Math.random() * 100 + '%';
  p.style.animationDuration = (8 + Math.random() * 12) + 's';
  p.style.animationDelay = Math.random() * 10 + 's';
  particlesEl.appendChild(p);
}

function render() {
  const cells = boardEl.querySelectorAll('.cell');
  cells.forEach((cell, i) => {
    cell.textContent = board[i] || '';
    cell.className = 'cell';
    if (board[i]) cell.classList.add('taken', board[i].toLowerCase());
    if (gameOver) cell.classList.add('game-over');
  });
  document.getElementById('scoreX').textContent = scores.X;
  document.getElementById('scoreO').textContent = scores.O;
  document.getElementById('scoreD').textContent = scores.D;
}

function checkWinner() {
  const lines = [
    [0,1,2],[3,4,5],[6,7,8],
    [0,3,6],[1,4,7],[2,5,8],
    [0,4,8],[2,4,6]
  ];
  for (const [a,b,c] of lines) {
    if (board[a] && board[a] === board[b] && board[b] === board[c]) {
      return { winner: board[a], line: [a,b,c] };
    }
  }
  if (board.every(c => c !== null)) return { winner: 'draw', line: [] };
  return null;
}

function highlightWin(line) {
  const cells = boardEl.querySelectorAll('.cell');
  line.forEach(i => cells[i].classList.add('win'));
}

async function handleClick(i) {
  if (board[i] || gameOver) return;

  // Player move
  board[i] = 'X';
  render();

  const result = checkWinner();
  if (result) {
    endGame(result);
    return;
  }

  // Agent's turn
  statusEl.textContent = 'Hermes is thinking...';
  statusEl.className = 'status thinking';

  try {
    const resp = await fetch('/api/move', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ board })
    });
    const data = await resp.json();

    if (data.move !== undefined && data.move !== null && board[data.move] === null) {
      board[data.move] = 'O';
    }
  } catch (e) {
    console.error('Agent move failed:', e);
  }

  render();
  const result2 = checkWinner();
  if (result2) {
    endGame(result2);
    return;
  }

  statusEl.textContent = 'Your turn';
  statusEl.className = 'status';
}

function endGame(result) {
  gameOver = true;
  if (result.winner === 'X') {
    statusEl.textContent = 'You win!';
    scores.X++;
  } else if (result.winner === 'O') {
    statusEl.textContent = 'Hermes wins!';
    scores.O++;
  } else {
    statusEl.textContent = "It's a draw!";
    scores.D++;
  }
  statusEl.className = 'status';
  if (result.line.length) highlightWin(result.line);
  render();
}

function resetGame() {
  board.fill(null);
  gameOver = false;
  statusEl.textContent = 'Your turn';
  statusEl.className = 'status';
  render();
}

render();
</script>
</body>
</html>"""


class _GameHandler(http.server.BaseHTTPRequestHandler):
    """HTTP handler for the tic-tac-toe game."""

    def log_message(self, format, *args):
        # Suppress default access logs
        pass

    def do_GET(self):
        if self.path == "/" or self.path == "/index.html":
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.end_headers()
            self.wfile.write(_HTML_PAGE.encode("utf-8"))
        elif self.path == "/health":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(b'{"status":"ok"}')
        else:
            self.send_error(404)

    def do_POST(self):
        if self.path == "/api/move":
            content_length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(content_length).decode("utf-8")
            try:
                data = json.loads(body)
                board = data.get("board", [None] * 9)
                move = self._compute_move(board)
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps({"move": move}).encode("utf-8"))
            except Exception as e:
                self.send_response(500)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps({"error": str(e)}).encode("utf-8"))
        else:
            self.send_error(404)

    def _compute_move(self, board: list) -> Optional[int]:
        """Get agent's move — try LLM first, fall back to minimax."""
        empty = [i for i in range(9) if board[i] is None]
        if not empty:
            return None

        # Try LLM
        if _agent_move_fn is not None:
            llm_move = _get_llm_move(board, _agent_move_fn)
            if llm_move is not None and llm_move in empty:
                return llm_move

        # Fallback to minimax
        return _get_minimax_move(board)


def start_game(agent_move_fn: Callable = None, port: int = PORT) -> None:
    """Start the tic-tac-toe game server and open the browser.

    Args:
        agent_move_fn: Function that takes a prompt string and returns
                       the LLM response string. If None, uses minimax only.
        port: Port to listen on.
    """
    global _server_instance, _agent_move_fn
    _agent_move_fn = agent_move_fn

    if _server_instance is not None:
        print(f"  Game already running at http://localhost:{port}")
        webbrowser.open(f"http://localhost:{port}")
        return

    socketserver.TCPServer.allow_reuse_address = True
    _server_instance = socketserver.TCPServer(("", port), _GameHandler)

    thread = threading.Thread(target=_server_instance.serve_forever, daemon=True)
    thread.start()

    url = f"http://localhost:{port}"
    print(f"  Tic Tac Toe started at {url}")
    print(f"  Opening browser...")
    webbrowser.open(url)


def stop_game() -> None:
    """Stop the game server if running."""
    global _server_instance
    if _server_instance is not None:
        _server_instance.shutdown()
        _server_instance = None
