from gateway.tool_progress_format import (
    is_shell_prologue_line,
    terminal_command_preview_line,
)


def test_terminal_preview_skips_set_euo_pipefail_for_multiline_bash():
    command = "set -euo pipefail\npython scripts/build_docs.py --check\npytest tests/docs"

    assert (
        terminal_command_preview_line(command, cap=80)
        == "python scripts/build_docs.py --check ..."
    )


def test_terminal_preview_keeps_ordinary_first_line():
    command = "pytest tests/gateway/test_discord_format.py -q\npython -m compileall gateway"

    assert (
        terminal_command_preview_line(command, cap=80)
        == "pytest tests/gateway/test_discord_format.py -q ..."
    )


def test_terminal_preview_skips_comments_and_blank_lines_before_command():
    command = "\n# generated by agent\nset -euxo pipefail\nuv run pytest tests/gateway -q"

    assert terminal_command_preview_line(command, cap=80) == "uv run pytest tests/gateway -q"


def test_terminal_preview_falls_back_when_command_is_only_prologue():
    assert terminal_command_preview_line("set -euo pipefail", cap=80) == "set -euo pipefail"


def test_terminal_preview_caps_selected_meaningful_line():
    command = "set -euo pipefail\npython " + ("x" * 120)

    preview = terminal_command_preview_line(command, cap=32)

    assert preview.startswith("python ")
    assert preview.endswith("...")
    assert len(preview) == 32


def test_shell_prologue_detection_does_not_skip_compound_work_line():
    assert is_shell_prologue_line("set -euo pipefail")
    assert not is_shell_prologue_line("set -euo pipefail; pytest -q")


def test_terminal_preview_skips_prologue_with_trailing_separator():
    assert (
        terminal_command_preview_line("set -euo pipefail &&\npytest -q", cap=80)
        == "pytest -q"
    )
    assert (
        terminal_command_preview_line("set -o errexit;\npytest -q", cap=80)
        == "pytest -q"
    )


def test_terminal_preview_ignores_trailing_comments_for_continuation_marker():
    command = "echo done\n\n# nothing else to run"

    assert terminal_command_preview_line(command, cap=80) == "echo done"


def test_terminal_preview_handles_very_small_caps():
    assert terminal_command_preview_line("echo hello", cap=3) == "ech"
