"""MES 巡检默认阈值配置。"""

DEFAULT_THRESHOLDS = {
    "nginx": {
        "process_check": True,
        "error_5xx_threshold_warn": 1.0,
        "error_5xx_threshold_critical": 5.0,
        "active_connections_warn": 10000,
        "response_time_warn": 2.0,
        "response_time_critical": 5.0,
        "status_url": "http://localhost/nginx_status",
        "health_check_url": "http://localhost:8080/health",
        "access_log_path": "/var/log/nginx/access.log",
    },
    "jvm": {
        "heap_usage_warn": 80.0,
        "heap_usage_critical": 90.0,
        "full_gc_freq_warn": 5,
        "full_gc_time_critical": 10.0,
        "active_threads_warn": 500,
        "blocked_threads_critical": 10,
        "catalina_log_lines": 1000,
        "tomcat_process_name": "catalina",
    },
    "rabbitmq": {
        "queue_depth_warn": 1000,
        "queue_depth_critical": 10000,
        "memory_usage_warn": 80.0,
        "memory_usage_critical": 95.0,
        "disk_free_warn_percent": 20.0,
        "management_url": "http://localhost:15672",
        "management_user": "guest",
        "management_password": "guest",
    },
    "oracle": {
        "slow_sql_threshold_sec": 5.0,
        "slow_sql_count_warn": 5,
        "tablespace_usage_warn": 80.0,
        "tablespace_usage_critical": 90.0,
        "lock_wait_critical": 10,
        "active_sessions_warn": 100,
        "connection_string": "",
        "username": "",
        "password_env": "ORACLE_PASSWORD",
    },
    "elk": {
        "cluster_status_critical": "red",
        "cluster_status_warn": "yellow",
        "unassigned_shards_warn": 5,
        "disk_usage_warn": 80.0,
        "disk_usage_critical": 90.0,
        "jvm_heap_warn": 75.0,
        "elasticsearch_url": "http://localhost:9200",
    },
    "skywalking": {
        "p95_response_time_warn": 2000,
        "p95_response_time_critical": 5000,
        "sla_warn": 99.0,
        "sla_critical": 95.0,
        "error_rate_critical": 5.0,
        "oap_url": "http://localhost:12800",
        "service_name": "mes-service",
    },
    "upstream": {
        "status_url": "http://localhost/upstream_status?format=json",
        "timeout": 5,
    },
    "alerter": {
        "feishu_webhook_url": "",
        "feishu_app_id_env": "FEISHU_APP_ID",
        "feishu_app_secret_env": "FEISHU_APP_SECRET",
        "feishu_home_channel_env": "FEISHU_HOME_CHANNEL",
        "silence_window_seconds": 900,
        "batch_interval_seconds": 1800,
        "max_message_length": 8000,
    },
    "self_healing": {
        "enabled": True,
        "data_risk_weight": 0.30,
        "reversibility_weight": 0.25,
        "impact_scope_weight": 0.25,
        "success_rate_weight": 0.15,
        "config_change_weight": 0.05,
        "l1_threshold": 30,
        "l2_threshold": 70,
        "default_first_occurrence_level": "L3",
        "data_involved_level": "L3",
    },
    "memory": {
        "log_dir": "",
        "max_case_per_component": 1000,
        "evolution_interval_days": 7,
    },
    "gitlab": {
        "url": "",
        "token_env": "GITLAB_TOKEN",
        "default_branch": "main",
        "mr_reviewers": [],
    },
    "evolution": {
        "iterations": 10,
        "eval_source": "synthetic",
        "optimizer_model": "openai/gpt-4.1",
        "eval_model": "openai/gpt-4.1-mini",
        "hermes_repo": "",
        "skills_dir": "",
        "base_url": "",
        "api_key_env": "OPENAI_API_KEY",
    },
    "model": {
        "provider": "custom",
        "base_url": "",
        "model_name": "Qwen3-235B-A22B-w8a8",
        "api_key_env": "QWEN_API_KEY",
    },
    "debug": {
        "gc_log_path": "/u01/app/mes-app/logs/gc.log",
        "gc_max_lines": 50000,
        "gc_pause_warn_sec": 1.0,
        "gc_pause_critical_sec": 5.0,
        "gc_full_count_warn": 10,
        "stack_context_lines": 10,
        "stack_blocked_warn": 10,
        "es_index_prefix": "39qjmes",
        "es_default_size": 100,
        "es_max_size": 1000,
    },
}
