"""Conflict bucketing helpers."""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from . import gitops


@dataclass(frozen=True)
class ConflictBucket:
    name: str
    files: tuple[str, ...]


@dataclass(frozen=True)
class ConflictFile:
    path: str
    status: str
    hunk_count: int
    bucket: str


STATUS_BUCKETS = {
    "UU": "both_modified",
    "AA": "both_added",
    "DD": "both_deleted",
    "DU": "deleted_by_us",
    "UD": "deleted_by_them",
    "AU": "added_by_us",
    "UA": "added_by_them",
}


def bucket_for_status(status: str) -> str:
    return STATUS_BUCKETS.get(status, "unmerged_other")


def spec_bucket_for_status(status: str) -> str:
    if status in {"DU", "UD", "DD"}:
        return "ARCH-SPLIT"
    if status in {"AA", "AU", "UA"}:
        return "MECHANICAL"
    return "SEMANTIC"


def bucket_conflicts(repo: Path) -> list[ConflictBucket]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for status, path in gitops.conflict_entries(repo):
        grouped[bucket_for_status(status)].append(path)
    return [
        ConflictBucket(name=name, files=tuple(sorted(files)))
        for name, files in sorted(grouped.items())
    ]


def summarize_buckets(buckets: list[ConflictBucket]) -> list[tuple[str, int]]:
    return [(bucket.name, len(bucket.files)) for bucket in buckets]


def conflict_files(repo: Path) -> list[ConflictFile]:
    marker_lines = gitops.conflict_marker_lines(repo)
    hunk_counts: dict[str, int] = {}
    for line in marker_lines:
        path = line.split(":", 1)[0]
        hunk_counts[path] = hunk_counts.get(path, 0) + 1
    rows: list[ConflictFile] = []
    for status, path in gitops.conflict_entries(repo):
        rows.append(
            ConflictFile(
                path=path,
                status=status,
                hunk_count=hunk_counts.get(path, 0),
                bucket=spec_bucket_for_status(status),
            )
        )
    return sorted(rows, key=lambda row: row.path)


def bucket_stats(rows: list[ConflictFile]) -> dict[str, int]:
    stats = {"files": len(rows), "hunks": sum(row.hunk_count for row in rows)}
    for name in ("MECHANICAL", "SEMANTIC", "ARCH-SPLIT"):
        stats[name.lower().replace("-", "_")] = sum(1 for row in rows if row.bucket == name)
    return stats


def format_conflict_report(rows: list[ConflictFile]) -> str:
    stats = bucket_stats(rows)
    lines = [
        "# Conflict Buckets",
        "",
        "| file | status | hunks | bucket |",
        "|---|---:|---:|---|",
    ]
    for row in rows:
        lines.append(f"| `{row.path}` | `{row.status}` | {row.hunk_count} | {row.bucket} |")
    lines.extend(
        [
            "",
            "## Totals",
            "",
            f"- files: {stats['files']}",
            f"- hunks: {stats['hunks']}",
            f"- mechanical: {stats['mechanical']}",
            f"- semantic: {stats['semantic']}",
            f"- arch_split: {stats['arch_split']}",
            "",
            "## Scale Comparison",
            "",
            "| sync | files | hunks | note |",
            "|---|---:|---:|---|",
            "| 2026-07-10 | 56 | 147 | reference sync |",
            f"| current | {stats['files']} | {stats['hunks']} | generated by hermes_parity |",
        ]
    )
    return "\n".join(lines) + "\n"


def write_conflict_report(repo: Path) -> dict[str, int]:
    rows = conflict_files(repo)
    output = repo / "docs" / "sync" / "review" / "conflict-buckets.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(format_conflict_report(rows), encoding="utf-8")
    return bucket_stats(rows)
