services:
  hermes-agent-local:
    image: hermes-agent-local
    container_name: hermes-agent-local
    restart: unless-stopped
    env_file:
      - ../data/.env
    ports:
      - "4861:4861"
      - "8001:8001"
    volumes:
      - D:/hermes-github/data:/opt/data
    command: gateway run
