{
 "id": "youtubereporting:v1",
 "protocol": "rest",
 "mtlsRootUrl": "https://youtubereporting.mtls.googleapis.com/",
 "discoveryVersion": "v1",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
     "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
    },
    "https://www.googleapis.com/auth/yt-analytics.readonly": {
     "description": "View YouTube Analytics reports for your YouTube content"
    }
   }
  }
 },
 "batchPath": "batch",
 "revision": "20260329",
 "rootUrl": "https://youtubereporting.googleapis.com/",
 "version": "v1",
 "kind": "discovery#restDescription",
 "servicePath": "",
 "canonicalName": "YouTube Reporting",
 "ownerName": "Google",
 "resources": {
  "reportTypes": {
   "methods": {
    "list": {
     "id": "youtubereporting.reportTypes.list",
     "path": "v1/reportTypes",
     "flatPath": "v1/reportTypes",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "description": "Lists report types."
    }
   }
  },
  "jobs": {
   "methods": {
    "create": {
     "id": "youtubereporting.jobs.create",
     "path": "v1/jobs",
     "flatPath": "v1/jobs",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "description": "Creates a job and returns it."
    },
    "list": {
     "id": "youtubereporting.jobs.list",
     "path": "v1/jobs",
     "flatPath": "v1/jobs",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "description": "Lists jobs."
    },
    "get": {
     "id": "youtubereporting.jobs.get",
     "path": "v1/jobs/{jobId}",
     "flatPath": "v1/jobs/{jobId}",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "description": "Gets a job."
    },
    "delete": {
     "id": "youtubereporting.jobs.delete",
     "path": "v1/jobs/{jobId}",
     "flatPath": "v1/jobs/{jobId}",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "description": "Deletes a job."
    }
   },
   "resources": {
    "reports": {
     "methods": {
      "list": {
       "id": "youtubereporting.jobs.reports.list",
       "path": "v1/jobs/{jobId}/reports",
       "flatPath": "v1/jobs/{jobId}/reports",
       "httpMethod": "GET",
       "scopes": [
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
        "https://www.googleapis.com/auth/yt-analytics.readonly"
       ],
       "description": "Lists reports created by a specific job. Returns NOT_FOUND if the job does not exist."
      },
      "get": {
       "id": "youtubereporting.jobs.reports.get",
       "path": "v1/jobs/{jobId}/reports/{reportId}",
       "flatPath": "v1/jobs/{jobId}/reports/{reportId}",
       "httpMethod": "GET",
       "scopes": [
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
        "https://www.googleapis.com/auth/yt-analytics.readonly"
       ],
       "description": "Gets the metadata of a specific report."
      }
     }
    }
   }
  },
  "media": {
   "methods": {
    "download": {
     "id": "youtubereporting.media.download",
     "path": "v1/media/{+resourceName}",
     "flatPath": "v1/media/{mediaId}",
     "httpMethod": "GET",
     "supportsMediaDownload": true,
     "useMediaDownloadService": true,
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "description": "Method for media download. Download is supported on the URI `/v1/media/{+name}?alt=media`."
    }
   }
  }
 },
 "documentationLink": "https://developers.google.com/youtube/reporting/v1/reports/",
 "basePath": "",
 "title": "YouTube Reporting API",
 "ownerDomain": "google.com",
 "baseUrl": "https://youtubereporting.googleapis.com/",
 "description": "Schedules reporting jobs containing your YouTube Analytics data and downloads the resulting bulk data reports in the form of CSV files.",
 "name": "youtubereporting"
}