{
 "version": "v3",
 "revision": "20260326",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/youtube": {
     "description": "Manage your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.channel-memberships.creator": {
     "description": "See a list of your current active channel members, their current level, and when they became a member"
    },
    "https://www.googleapis.com/auth/youtube.force-ssl": {
     "description": "See, edit, and permanently delete your YouTube videos, ratings, comments and captions"
    },
    "https://www.googleapis.com/auth/youtube.readonly": {
     "description": "View your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.upload": {
     "description": "Manage your YouTube videos"
    },
    "https://www.googleapis.com/auth/youtubepartner": {
     "description": "View and manage your assets and associated content on YouTube"
    },
    "https://www.googleapis.com/auth/youtubepartner-channel-audit": {
     "description": "View private information of your YouTube channel relevant during the audit process with a YouTube partner"
    }
   }
  }
 },
 "batchPath": "batch",
 "ownerDomain": "google.com",
 "discoveryVersion": "v1",
 "title": "YouTube Data API v3",
 "fullyEncodeReservedExpansion": true,
 "basePath": "",
 "description": "The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.",
 "ownerName": "Google",
 "protocol": "rest",
 "mtlsRootUrl": "https://youtube.mtls.googleapis.com/",
 "kind": "discovery#restDescription",
 "servicePath": "",
 "documentationLink": "https://developers.google.com/youtube/",
 "rootUrl": "https://youtube.googleapis.com/",
 "canonicalName": "YouTube",
 "resources": {
  "abuseReports": {
   "methods": {
    "insert": {
     "id": "youtube.abuseReports.insert",
     "path": "youtube/v3/abuseReports",
     "flatPath": "youtube/v3/abuseReports",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Inserts a new resource into this collection."
    }
   }
  },
  "activities": {
   "methods": {
    "list": {
     "id": "youtube.activities.list",
     "path": "youtube/v3/activities",
     "flatPath": "youtube/v3/activities",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    }
   }
  },
  "captions": {
   "methods": {
    "list": {
     "id": "youtube.captions.list",
     "path": "youtube/v3/captions",
     "flatPath": "youtube/v3/captions",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "insert": {
     "id": "youtube.captions.insert",
     "path": "youtube/v3/captions",
     "flatPath": "youtube/v3/captions",
     "httpMethod": "POST",
     "supportsMediaUpload": true,
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Inserts a new resource into this collection."
    },
    "update": {
     "id": "youtube.captions.update",
     "path": "youtube/v3/captions",
     "flatPath": "youtube/v3/captions",
     "httpMethod": "PUT",
     "supportsMediaUpload": true,
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Updates an existing resource."
    },
    "delete": {
     "id": "youtube.captions.delete",
     "path": "youtube/v3/captions",
     "flatPath": "youtube/v3/captions",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Deletes a resource."
    },
    "download": {
     "id": "youtube.captions.download",
     "path": "youtube/v3/captions/{id}",
     "flatPath": "youtube/v3/captions/{id}",
     "httpMethod": "GET",
     "supportsMediaDownload": true,
     "useMediaDownloadService": true,
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Downloads a caption track."
    }
   }
  },
  "channels": {
   "methods": {
    "list": {
     "id": "youtube.channels.list",
     "path": "youtube/v3/channels",
     "flatPath": "youtube/v3/channels",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner",
      "https://www.googleapis.com/auth/youtubepartner-channel-audit"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "update": {
     "id": "youtube.channels.update",
     "path": "youtube/v3/channels",
     "flatPath": "youtube/v3/channels",
     "httpMethod": "PUT",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Updates an existing resource."
    }
   }
  },
  "channelBanners": {
   "methods": {
    "insert": {
     "id": "youtube.channelBanners.insert",
     "path": "youtube/v3/channelBanners/insert",
     "flatPath": "youtube/v3/channelBanners/insert",
     "httpMethod": "POST",
     "supportsMediaUpload": true,
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.upload"
     ],
     "description": "Inserts a new resource into this collection."
    }
   }
  },
  "channelSections": {
   "methods": {
    "list": {
     "id": "youtube.channelSections.list",
     "path": "youtube/v3/channelSections",
     "flatPath": "youtube/v3/channelSections",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "insert": {
     "id": "youtube.channelSections.insert",
     "path": "youtube/v3/channelSections",
     "flatPath": "youtube/v3/channelSections",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Inserts a new resource into this collection."
    },
    "update": {
     "id": "youtube.channelSections.update",
     "path": "youtube/v3/channelSections",
     "flatPath": "youtube/v3/channelSections",
     "httpMethod": "PUT",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Updates an existing resource."
    },
    "delete": {
     "id": "youtube.channelSections.delete",
     "path": "youtube/v3/channelSections",
     "flatPath": "youtube/v3/channelSections",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Deletes a resource."
    }
   }
  },
  "comments": {
   "methods": {
    "list": {
     "id": "youtube.comments.list",
     "path": "youtube/v3/comments",
     "flatPath": "youtube/v3/comments",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "insert": {
     "id": "youtube.comments.insert",
     "path": "youtube/v3/comments",
     "flatPath": "youtube/v3/comments",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Inserts a new resource into this collection."
    },
    "update": {
     "id": "youtube.comments.update",
     "path": "youtube/v3/comments",
     "flatPath": "youtube/v3/comments",
     "httpMethod": "PUT",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Updates an existing resource."
    },
    "delete": {
     "id": "youtube.comments.delete",
     "path": "youtube/v3/comments",
     "flatPath": "youtube/v3/comments",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Deletes a resource."
    },
    "setModerationStatus": {
     "id": "youtube.comments.setModerationStatus",
     "path": "youtube/v3/comments/setModerationStatus",
     "flatPath": "youtube/v3/comments/setModerationStatus",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Sets the moderation status of one or more comments."
    },
    "markAsSpam": {
     "id": "youtube.comments.markAsSpam",
     "path": "youtube/v3/comments/markAsSpam",
     "flatPath": "youtube/v3/comments/markAsSpam",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Expresses the caller's opinion that one or more comments should be flagged as spam."
    }
   }
  },
  "commentThreads": {
   "methods": {
    "list": {
     "id": "youtube.commentThreads.list",
     "path": "youtube/v3/commentThreads",
     "flatPath": "youtube/v3/commentThreads",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "insert": {
     "id": "youtube.commentThreads.insert",
     "path": "youtube/v3/commentThreads",
     "flatPath": "youtube/v3/commentThreads",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Inserts a new resource into this collection."
    }
   }
  },
  "youtube": {
   "resources": {
    "v3": {
     "methods": {
      "updateCommentThreads": {
       "id": "youtube.youtube.v3.updateCommentThreads",
       "path": "youtube/v3/commentThreads",
       "flatPath": "youtube/v3/commentThreads",
       "httpMethod": "PUT",
       "description": "Updates an existing resource."
      }
     },
     "resources": {
      "liveChat": {
       "resources": {
        "messages": {
         "methods": {
          "stream": {
           "id": "youtube.youtube.v3.liveChat.messages.stream",
           "path": "youtube/v3/liveChat/messages/stream",
           "flatPath": "youtube/v3/liveChat/messages/stream",
           "httpMethod": "GET",
           "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
           ],
           "description": "Allows a user to load live chat through a server-streamed RPC."
          }
         }
        }
       }
      }
     }
    }
   }
  },
  "i18nLanguages": {
   "methods": {
    "list": {
     "id": "youtube.i18nLanguages.list",
     "path": "youtube/v3/i18nLanguages",
     "flatPath": "youtube/v3/i18nLanguages",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    }
   }
  },
  "i18nRegions": {
   "methods": {
    "list": {
     "id": "youtube.i18nRegions.list",
     "path": "youtube/v3/i18nRegions",
     "flatPath": "youtube/v3/i18nRegions",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    }
   }
  },
  "liveBroadcasts": {
   "methods": {
    "list": {
     "id": "youtube.liveBroadcasts.list",
     "path": "youtube/v3/liveBroadcasts",
     "flatPath": "youtube/v3/liveBroadcasts",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "description": "Retrieve the list of broadcasts associated with the given channel."
    },
    "insert": {
     "id": "youtube.liveBroadcasts.insert",
     "path": "youtube/v3/liveBroadcasts",
     "flatPath": "youtube/v3/liveBroadcasts",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Inserts a new stream for the authenticated user."
    },
    "update": {
     "id": "youtube.liveBroadcasts.update",
     "path": "youtube/v3/liveBroadcasts",
     "flatPath": "youtube/v3/liveBroadcasts",
     "httpMethod": "PUT",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Updates an existing broadcast for the authenticated user."
    },
    "delete": {
     "id": "youtube.liveBroadcasts.delete",
     "path": "youtube/v3/liveBroadcasts",
     "flatPath": "youtube/v3/liveBroadcasts",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Delete a given broadcast."
    },
    "bind": {
     "id": "youtube.liveBroadcasts.bind",
     "path": "youtube/v3/liveBroadcasts/bind",
     "flatPath": "youtube/v3/liveBroadcasts/bind",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Bind a broadcast to a stream."
    },
    "transition": {
     "id": "youtube.liveBroadcasts.transition",
     "path": "youtube/v3/liveBroadcasts/transition",
     "flatPath": "youtube/v3/liveBroadcasts/transition",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Transition a broadcast to a given status."
    },
    "insertCuepoint": {
     "id": "youtube.liveBroadcasts.insertCuepoint",
     "path": "youtube/v3/liveBroadcasts/cuepoint",
     "flatPath": "youtube/v3/liveBroadcasts/cuepoint",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Insert cuepoints in a broadcast"
    }
   }
  },
  "liveChatBans": {
   "methods": {
    "insert": {
     "id": "youtube.liveChatBans.insert",
     "path": "youtube/v3/liveChat/bans",
     "flatPath": "youtube/v3/liveChat/bans",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Inserts a new resource into this collection."
    },
    "delete": {
     "id": "youtube.liveChatBans.delete",
     "path": "youtube/v3/liveChat/bans",
     "flatPath": "youtube/v3/liveChat/bans",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Deletes a chat ban."
    }
   }
  },
  "liveChatMessages": {
   "methods": {
    "list": {
     "id": "youtube.liveChatMessages.list",
     "path": "youtube/v3/liveChat/messages",
     "flatPath": "youtube/v3/liveChat/messages",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "insert": {
     "id": "youtube.liveChatMessages.insert",
     "path": "youtube/v3/liveChat/messages",
     "flatPath": "youtube/v3/liveChat/messages",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Inserts a new resource into this collection."
    },
    "delete": {
     "id": "youtube.liveChatMessages.delete",
     "path": "youtube/v3/liveChat/messages",
     "flatPath": "youtube/v3/liveChat/messages",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Deletes a chat message."
    },
    "transition": {
     "id": "youtube.liveChatMessages.transition",
     "path": "youtube/v3/liveChat/messages/transition",
     "flatPath": "youtube/v3/liveChat/messages/transition",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Transition a durable chat event."
    }
   }
  },
  "liveChatModerators": {
   "methods": {
    "list": {
     "id": "youtube.liveChatModerators.list",
     "path": "youtube/v3/liveChat/moderators",
     "flatPath": "youtube/v3/liveChat/moderators",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "insert": {
     "id": "youtube.liveChatModerators.insert",
     "path": "youtube/v3/liveChat/moderators",
     "flatPath": "youtube/v3/liveChat/moderators",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Inserts a new resource into this collection."
    },
    "delete": {
     "id": "youtube.liveChatModerators.delete",
     "path": "youtube/v3/liveChat/moderators",
     "flatPath": "youtube/v3/liveChat/moderators",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Deletes a chat moderator."
    }
   }
  },
  "liveStreams": {
   "methods": {
    "list": {
     "id": "youtube.liveStreams.list",
     "path": "youtube/v3/liveStreams",
     "flatPath": "youtube/v3/liveStreams",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "description": "Retrieve the list of streams associated with the given channel. --"
    },
    "insert": {
     "id": "youtube.liveStreams.insert",
     "path": "youtube/v3/liveStreams",
     "flatPath": "youtube/v3/liveStreams",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Inserts a new stream for the authenticated user."
    },
    "update": {
     "id": "youtube.liveStreams.update",
     "path": "youtube/v3/liveStreams",
     "flatPath": "youtube/v3/liveStreams",
     "httpMethod": "PUT",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Updates an existing stream for the authenticated user."
    },
    "delete": {
     "id": "youtube.liveStreams.delete",
     "path": "youtube/v3/liveStreams",
     "flatPath": "youtube/v3/liveStreams",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "description": "Deletes an existing stream for the authenticated user."
    }
   }
  },
  "members": {
   "methods": {
    "list": {
     "id": "youtube.members.list",
     "path": "youtube/v3/members",
     "flatPath": "youtube/v3/members",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.channel-memberships.creator"
     ],
     "description": "Retrieves a list of members that match the request criteria for a channel."
    }
   }
  },
  "membershipsLevels": {
   "methods": {
    "list": {
     "id": "youtube.membershipsLevels.list",
     "path": "youtube/v3/membershipsLevels",
     "flatPath": "youtube/v3/membershipsLevels",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.channel-memberships.creator"
     ],
     "description": "Retrieves a list of all pricing levels offered by a creator to the fans."
    }
   }
  },
  "playlists": {
   "methods": {
    "list": {
     "id": "youtube.playlists.list",
     "path": "youtube/v3/playlists",
     "flatPath": "youtube/v3/playlists",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "insert": {
     "id": "youtube.playlists.insert",
     "path": "youtube/v3/playlists",
     "flatPath": "youtube/v3/playlists",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Inserts a new resource into this collection."
    },
    "update": {
     "id": "youtube.playlists.update",
     "path": "youtube/v3/playlists",
     "flatPath": "youtube/v3/playlists",
     "httpMethod": "PUT",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Updates an existing resource."
    },
    "delete": {
     "id": "youtube.playlists.delete",
     "path": "youtube/v3/playlists",
     "flatPath": "youtube/v3/playlists",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Deletes a resource."
    }
   }
  },
  "playlistItems": {
   "methods": {
    "list": {
     "id": "youtube.playlistItems.list",
     "path": "youtube/v3/playlistItems",
     "flatPath": "youtube/v3/playlistItems",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "delete": {
     "id": "youtube.playlistItems.delete",
     "path": "youtube/v3/playlistItems",
     "flatPath": "youtube/v3/playlistItems",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Deletes a resource."
    },
    "insert": {
     "id": "youtube.playlistItems.insert",
     "path": "youtube/v3/playlistItems",
     "flatPath": "youtube/v3/playlistItems",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Inserts a new resource into this collection."
    },
    "update": {
     "id": "youtube.playlistItems.update",
     "path": "youtube/v3/playlistItems",
     "flatPath": "youtube/v3/playlistItems",
     "httpMethod": "PUT",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Updates an existing resource."
    }
   }
  },
  "playlistImages": {
   "methods": {
    "list": {
     "id": "youtube.playlistImages.list",
     "path": "youtube/v3/playlistImages",
     "flatPath": "youtube/v3/playlistImages",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "insert": {
     "id": "youtube.playlistImages.insert",
     "path": "youtube/v3/playlistImages",
     "flatPath": "youtube/v3/playlistImages",
     "httpMethod": "POST",
     "supportsMediaUpload": true,
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Inserts a new resource into this collection."
    },
    "update": {
     "id": "youtube.playlistImages.update",
     "path": "youtube/v3/playlistImages",
     "flatPath": "youtube/v3/playlistImages",
     "httpMethod": "PUT",
     "supportsMediaUpload": true,
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Updates an existing resource."
    },
    "delete": {
     "id": "youtube.playlistImages.delete",
     "path": "youtube/v3/playlistImages",
     "flatPath": "youtube/v3/playlistImages",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Deletes a resource."
    }
   }
  },
  "search": {
   "methods": {
    "list": {
     "id": "youtube.search.list",
     "path": "youtube/v3/search",
     "flatPath": "youtube/v3/search",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of search resources"
    }
   }
  },
  "subscriptions": {
   "methods": {
    "list": {
     "id": "youtube.subscriptions.list",
     "path": "youtube/v3/subscriptions",
     "flatPath": "youtube/v3/subscriptions",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "delete": {
     "id": "youtube.subscriptions.delete",
     "path": "youtube/v3/subscriptions",
     "flatPath": "youtube/v3/subscriptions",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Deletes a resource."
    },
    "insert": {
     "id": "youtube.subscriptions.insert",
     "path": "youtube/v3/subscriptions",
     "flatPath": "youtube/v3/subscriptions",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Inserts a new resource into this collection."
    }
   }
  },
  "superChatEvents": {
   "methods": {
    "list": {
     "id": "youtube.superChatEvents.list",
     "path": "youtube/v3/superChatEvents",
     "flatPath": "youtube/v3/superChatEvents",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    }
   }
  },
  "tests": {
   "methods": {
    "insert": {
     "id": "youtube.tests.insert",
     "path": "youtube/v3/tests",
     "flatPath": "youtube/v3/tests",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "description": "POST method."
    }
   }
  },
  "thirdPartyLinks": {
   "methods": {
    "list": {
     "id": "youtube.thirdPartyLinks.list",
     "path": "youtube/v3/thirdPartyLinks",
     "flatPath": "youtube/v3/thirdPartyLinks",
     "httpMethod": "GET",
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "insert": {
     "id": "youtube.thirdPartyLinks.insert",
     "path": "youtube/v3/thirdPartyLinks",
     "flatPath": "youtube/v3/thirdPartyLinks",
     "httpMethod": "POST",
     "description": "Inserts a new resource into this collection."
    },
    "update": {
     "id": "youtube.thirdPartyLinks.update",
     "path": "youtube/v3/thirdPartyLinks",
     "flatPath": "youtube/v3/thirdPartyLinks",
     "httpMethod": "PUT",
     "description": "Updates an existing resource."
    },
    "delete": {
     "id": "youtube.thirdPartyLinks.delete",
     "path": "youtube/v3/thirdPartyLinks",
     "flatPath": "youtube/v3/thirdPartyLinks",
     "httpMethod": "DELETE",
     "description": "Deletes a resource."
    }
   }
  },
  "thumbnails": {
   "methods": {
    "set": {
     "id": "youtube.thumbnails.set",
     "path": "youtube/v3/thumbnails/set",
     "flatPath": "youtube/v3/thumbnails/set",
     "httpMethod": "POST",
     "supportsMediaUpload": true,
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "As this is not an insert in a strict sense (it supports uploading/setting of a thumbnail for multiple videos, which doesn't result in creation of a single resource), I use a custom verb here."
    }
   }
  },
  "videos": {
   "methods": {
    "list": {
     "id": "youtube.videos.list",
     "path": "youtube/v3/videos",
     "flatPath": "youtube/v3/videos",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    },
    "insert": {
     "id": "youtube.videos.insert",
     "path": "youtube/v3/videos",
     "flatPath": "youtube/v3/videos",
     "httpMethod": "POST",
     "supportsMediaUpload": true,
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Inserts a new resource into this collection."
    },
    "update": {
     "id": "youtube.videos.update",
     "path": "youtube/v3/videos",
     "flatPath": "youtube/v3/videos",
     "httpMethod": "PUT",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Updates an existing resource."
    },
    "delete": {
     "id": "youtube.videos.delete",
     "path": "youtube/v3/videos",
     "flatPath": "youtube/v3/videos",
     "httpMethod": "DELETE",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Deletes a resource."
    },
    "reportAbuse": {
     "id": "youtube.videos.reportAbuse",
     "path": "youtube/v3/videos/reportAbuse",
     "flatPath": "youtube/v3/videos/reportAbuse",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Report abuse for a video."
    },
    "rate": {
     "id": "youtube.videos.rate",
     "path": "youtube/v3/videos/rate",
     "flatPath": "youtube/v3/videos/rate",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Adds a like or dislike rating to a video or removes a rating from a video."
    },
    "getRating": {
     "id": "youtube.videos.getRating",
     "path": "youtube/v3/videos/getRating",
     "flatPath": "youtube/v3/videos/getRating",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves the ratings that the authorized user gave to a list of specified videos."
    }
   }
  },
  "videoAbuseReportReasons": {
   "methods": {
    "list": {
     "id": "youtube.videoAbuseReportReasons.list",
     "path": "youtube/v3/videoAbuseReportReasons",
     "flatPath": "youtube/v3/videoAbuseReportReasons",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    }
   }
  },
  "videoCategories": {
   "methods": {
    "list": {
     "id": "youtube.videoCategories.list",
     "path": "youtube/v3/videoCategories",
     "flatPath": "youtube/v3/videoCategories",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Retrieves a list of resources, possibly filtered."
    }
   }
  },
  "videoTrainability": {
   "methods": {
    "get": {
     "id": "youtube.videoTrainability.get",
     "path": "youtube/v3/videoTrainability",
     "flatPath": "youtube/v3/videoTrainability",
     "httpMethod": "GET",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Returns the trainability status of a video."
    }
   }
  },
  "watermarks": {
   "methods": {
    "set": {
     "id": "youtube.watermarks.set",
     "path": "youtube/v3/watermarks/set",
     "flatPath": "youtube/v3/watermarks/set",
     "httpMethod": "POST",
     "supportsMediaUpload": true,
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Allows upload of watermark image and setting it for a channel."
    },
    "unset": {
     "id": "youtube.watermarks.unset",
     "path": "youtube/v3/watermarks/unset",
     "flatPath": "youtube/v3/watermarks/unset",
     "httpMethod": "POST",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "description": "Allows removal of channel watermark."
    }
   }
  }
 },
 "id": "youtube:v3",
 "name": "youtube",
 "baseUrl": "https://youtube.googleapis.com/"
}