"""Install twice-daily PDB-style situation report cron jobs (08:00 / 18:00)."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

JOB_MORNING = "wm-osint-pdb-morning"
JOB_EVENING = "wm-osint-pdb-evening"
DEFAULT_MORNING_SCHEDULE = "0 8 * * *"
DEFAULT_EVENING_SCHEDULE = "0 18 * * *"
_CRON_SCRIPT_TIMEOUT = 900
_CRON_RUN_TIMEOUT = 900


def _ensure_cron_script_timeout(*, min_seconds: int = _CRON_SCRIPT_TIMEOUT) -> dict[str, Any]:
    try:
        import yaml
        from hermes_cli.config import ensure_hermes_home, get_config_path, load_config
        from utils import atomic_yaml_write
    except Exception as exc:
        return {"ok": False, "error": f"config update unavailable: {exc}"}

    ensure_hermes_home()
    current = int(load_config().get("cron", {}).get("script_timeout_seconds") or 120)
    if current >= min_seconds:
        return {
            "ok": True,
            "updated": False,
            "script_timeout_seconds": current,
        }

    config_path = get_config_path()
    user_config: dict = {}
    if config_path.exists():
        try:
            with config_path.open("r", encoding="utf-8") as fh:
                user_config = yaml.safe_load(fh) or {}
        except Exception:
            user_config = {}
    cron_cfg = user_config.setdefault("cron", {})
    cron_cfg["script_timeout_seconds"] = min_seconds
    atomic_yaml_write(config_path, user_config, sort_keys=False)
    return {
        "ok": True,
        "updated": True,
        "script_timeout_seconds": min_seconds,
        "config_path": str(config_path),
    }


def _write_cron_wrapper(
    path: Path,
    *,
    python_exe: Path,
    repo_root: Path,
    slot: str,
    extra_args: list[str],
) -> None:
    payload = {
        "python": str(python_exe),
        "repo_root": str(repo_root),
        "slot": slot,
        "extra_args": extra_args,
    }
    content = f"""# Auto-generated by hermes worldmonitor-osint cron install.
import json
import os
import subprocess
import sys

PAYLOAD = {json.dumps(payload, ensure_ascii=True, indent=2)}

env = os.environ.copy()
env.setdefault("PYTHONIOENCODING", "utf-8")

args = [
    "worldmonitor-osint",
    "situation-report",
    "--slot",
    PAYLOAD["slot"],
    "--cron-stdout",
    *PAYLOAD.get("extra_args", []),
]
result = subprocess.run(
    [PAYLOAD["python"], "-m", "hermes_cli.main", *args],
    cwd=PAYLOAD["repo_root"],
    env=env,
    capture_output=True,
    text=True,
    encoding="utf-8",
    errors="replace",
    timeout={_CRON_RUN_TIMEOUT},
)
stdout = (result.stdout or "").strip()
stderr = (result.stderr or "").strip()
if result.returncode != 0:
    if stderr:
        print(stderr)
    if stdout:
        print(stdout)
    sys.exit(result.returncode)
if stdout:
    print(stdout)
"""
    path.write_text(content, encoding="utf-8")


def _ensure_cron_scripts(
    *,
    source_mode: str,
    wm_tier: str,
    llm_summary: bool,
    max_scenarios: int,
) -> dict[str, str]:
    from hermes_constants import get_hermes_home

    import hermes_cli

    hermes_home = Path(get_hermes_home())
    scripts_dir = hermes_home / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)

    repo_root = Path(hermes_cli.__file__).resolve().parent.parent
    python_exe = Path(sys.executable).resolve()

    extra_args = [
        "--source-mode",
        source_mode,
        "--wm-tier",
        wm_tier,
        "--max-scenarios",
        str(max_scenarios),
    ]
    if llm_summary:
        extra_args.append("--llm-summary")

    morning_script = scripts_dir / "wm-osint-pdb-morning.py"
    evening_script = scripts_dir / "wm-osint-pdb-evening.py"
    _write_cron_wrapper(
        morning_script,
        python_exe=python_exe,
        repo_root=repo_root,
        slot="morning",
        extra_args=extra_args,
    )
    _write_cron_wrapper(
        evening_script,
        python_exe=python_exe,
        repo_root=repo_root,
        slot="evening",
        extra_args=extra_args,
    )
    return {
        "morning": morning_script.name,
        "evening": evening_script.name,
        "morning_path": str(morning_script),
        "evening_path": str(evening_script),
    }


def _preflight_delivery(deliver: str) -> dict[str, Any]:
    """Validate deliver string resolves to concrete platform targets."""
    try:
        from cron.scheduler import _normalize_deliver_value, _resolve_delivery_targets
    except Exception as exc:
        return {"ok": True, "skipped": True, "reason": str(exc)}

    normalized = _normalize_deliver_value(deliver)
    if normalized == "local":
        return {"ok": True, "deliver": normalized, "targets": []}

    targets = _resolve_delivery_targets({"deliver": normalized, "origin": None})
    if not targets:
        return {
            "ok": False,
            "deliver": normalized,
            "error": (
                f"No delivery targets resolved for deliver={normalized!r}. "
                "Set TELEGRAM_HOME_CHANNEL / DISCORD_HOME_CHANNEL in ~/.hermes/.env "
                "and enable the platform in gateway config."
            ),
        }
    return {
        "ok": True,
        "deliver": normalized,
        "targets": [
            {
                "platform": t.get("platform"),
                "chat_id_suffix": str(t.get("chat_id") or "")[-6:] or None,
                "thread_id": t.get("thread_id"),
            }
            for t in targets
        ],
    }


def _find_job_by_name(name: str) -> dict[str, Any] | None:
    from cron.jobs import list_jobs

    for job in list_jobs(include_disabled=True):
        if (job.get("name") or "").strip() == name:
            return job
    return None


def _upsert_job(
    *,
    name: str,
    schedule: str,
    script: str,
    deliver: str,
    paused: bool,
) -> dict[str, Any]:
    from cron.jobs import create_job, pause_job, update_job

    existing = _find_job_by_name(name)
    if existing:
        job = update_job(
            existing["id"],
            {
                "schedule": schedule,
                "script": script,
                "no_agent": True,
                "deliver": deliver,
                "prompt": name,
            },
        )
        if not job:
            job = existing
    else:
        job = create_job(
            prompt=name,
            schedule=schedule,
            name=name,
            deliver=deliver,
            script=script,
            no_agent=True,
        )
    if paused and job.get("id"):
        paused_job = pause_job(job["id"], reason="worldmonitor-osint PDB cron installed paused")
        if paused_job:
            job = paused_job
    return job


def install_pdb_cron(
    *,
    morning_schedule: str = DEFAULT_MORNING_SCHEDULE,
    evening_schedule: str = DEFAULT_EVENING_SCHEDULE,
    deliver: str = "local",
    source_mode: str = "mock",
    wm_tier: str = "auto",
    llm_summary: bool = False,
    max_scenarios: int = 4,
    dry_run: bool = False,
    paused: bool = False,
    force: bool = False,
) -> dict[str, Any]:
    """Create or update 08:00 and 18:00 PDB situation-report cron jobs."""
    scripts = _ensure_cron_scripts(
        source_mode=source_mode,
        wm_tier=wm_tier,
        llm_summary=llm_summary,
        max_scenarios=max_scenarios,
    )
    preview = [
        {
            "name": JOB_MORNING,
            "schedule": morning_schedule,
            "script": scripts["morning"],
            "no_agent": True,
            "deliver": deliver,
        },
        {
            "name": JOB_EVENING,
            "schedule": evening_schedule,
            "script": scripts["evening"],
            "no_agent": True,
            "deliver": deliver,
        },
    ]
    if dry_run:
        delivery_check = _preflight_delivery(deliver)
        return {
            "success": True,
            "dry_run": True,
            "jobs": preview,
            "scripts": scripts,
            "delivery": delivery_check,
            "llm_summary": llm_summary,
            "source_mode": source_mode,
        }

    if deliver != "local":
        delivery_check = _preflight_delivery(deliver)
        if not delivery_check.get("ok") and not force:
            return {"success": False, **delivery_check}
    else:
        delivery_check = _preflight_delivery(deliver)

    timeout_result = _ensure_cron_script_timeout()
    if not timeout_result.get("ok"):
        return {"success": False, "error": "cron script timeout update failed", **timeout_result}

    jobs = []
    for spec in preview:
        jobs.append(
            _upsert_job(
                name=spec["name"],
                schedule=spec["schedule"],
                script=spec["script"],
                deliver=deliver,
                paused=paused,
            )
        )

    return {
        "success": True,
        "paused": paused,
        "cron_script_timeout": timeout_result,
        "delivery": delivery_check,
        "llm_summary": llm_summary,
        "source_mode": source_mode,
        "scripts": scripts,
        "schedules": {
            "morning": morning_schedule,
            "evening": evening_schedule,
            "timezone_note": "Cron uses Hermes/system local wall time (JST if OS is JST).",
        },
        "jobs": [
            {
                "id": job.get("id"),
                "name": job.get("name"),
                "state": job.get("state"),
                "enabled": job.get("enabled"),
                "schedule": job.get("schedule_display"),
                "next_run_at": job.get("next_run_at"),
                "script": job.get("script"),
                "no_agent": job.get("no_agent"),
                "deliver": job.get("deliver"),
            }
            for job in jobs
        ],
        "resume_commands": [
            f"hermes cron resume {job['id']}"
            for job in jobs
            if paused and job.get("id")
        ],
        "manual_test": [
            "py -3 -m hermes_cli.main worldmonitor-osint situation-report --slot morning --cron-stdout",
            f"py -3 {scripts['morning_path']}",
        ],
    }
