"""Hindsight's declared config surface — rendered by the generic desktop panel."""

from plugins.memory.config_schema import (
    KIND_SECRET,
    KIND_SELECT,
    KIND_TEXT,
    ProviderConfigSchema,
    ProviderField,
    ProviderFieldOption,
)

CONFIG_SCHEMA = ProviderConfigSchema(
    name="hindsight",
    label="Hindsight",
    fields=(
        # — Connection —
        ProviderField(
            key="mode",
            label="Mode",
            kind=KIND_SELECT,
            default="cloud",
            description="How Hermes connects to Hindsight.",
            options=(
                ProviderFieldOption(
                    "cloud",
                    "Cloud",
                    "Hindsight Cloud API (lightweight, just needs an API key)",
                ),
                ProviderFieldOption(
                    "local_external",
                    "Local External",
                    "Connect to an existing Hindsight instance",
                ),
            ),
            inline=True,
            group="Connection",
        ),
        ProviderField(
            key="api_key",
            label="Hindsight API key",
            kind=KIND_SECRET,
            env_key="HINDSIGHT_API_KEY",
            description="Cloud or Local External authentication. Not used by Local Embedded mode.",
            placeholder="Enter Hindsight API key",
            inline=True,
            group="Connection",
        ),
        ProviderField(
            key="api_url",
            label="Hindsight API URL",
            kind=KIND_TEXT,
            default="https://api.hindsight.vectorize.io",
            aliases=("apiUrl",),
            env_fallbacks=("HINDSIGHT_API_URL",),
            description="Cloud or Local External endpoint. Not used by Local Embedded mode.",
            inline=True,
            group="Connection",
        ),
        # — Local Embedded LLM —
        ProviderField(
            key="llm_provider",
            label="LLM provider",
            kind=KIND_SELECT,
            default="openai",
            description="LLM backend used by Local Embedded mode.",
            options=(
                ProviderFieldOption("openai", "OpenAI"),
                ProviderFieldOption("anthropic", "Anthropic"),
                ProviderFieldOption("gemini", "Gemini"),
                ProviderFieldOption("groq", "Groq"),
                ProviderFieldOption("openrouter", "OpenRouter"),
                ProviderFieldOption("minimax", "MiniMax"),
                ProviderFieldOption("ollama", "Ollama"),
                ProviderFieldOption("lmstudio", "LM Studio"),
                ProviderFieldOption("openai_compatible", "OpenAI compatible"),
            ),
            group="Local Embedded LLM",
        ),
        ProviderField(
            key="llm_base_url",
            label="LLM base URL",
            kind=KIND_TEXT,
            description="Custom LLM endpoint used by Local Embedded mode.",
            placeholder="https://…/v1",
            group="Local Embedded LLM",
        ),
        ProviderField(
            key="llm_api_key",
            label="LLM API key",
            kind=KIND_SECRET,
            env_key="HINDSIGHT_LLM_API_KEY",
            description="LLM credential used by Local Embedded mode. Optional for some local servers.",
            placeholder="Enter LLM API key",
            group="Local Embedded LLM",
        ),
        ProviderField(
            key="llm_model",
            label="LLM model",
            kind=KIND_TEXT,
            default="gpt-4o-mini",
            description="Model used by Local Embedded mode.",
            placeholder="gpt-4o-mini",
            group="Local Embedded LLM",
        ),
        # — Memory —
        ProviderField(
            key="bank_id",
            label="Bank ID",
            kind=KIND_TEXT,
            default="hermes",
            aliases=("bankId",),
            inline=True,
            group="Memory",
        ),
        ProviderField(
            key="recall_budget",
            label="Recall budget",
            kind=KIND_SELECT,
            default="mid",
            aliases=("budget",),
            options=(
                ProviderFieldOption("low", "low"),
                ProviderFieldOption("mid", "mid"),
                ProviderFieldOption("high", "high"),
            ),
            inline=True,
            group="Memory",
        ),
    ),
)