import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
/**
 * Command Center M1 — interim functional/render-contract proof.
 *
 * Authorized by Architect (2026-08-31) as the bounded interim evidence path
 * while the full Electron 12-screen walkthrough remains blocked by a verified
 * environmental limitation on this build machine: the unmodified, pre-existing
 * `e2e/boot.spec.ts` fails at Electron process launch with the same Windows
 * path/launch error on current `main`, before any M1 code existed. This is
 * NOT an M1 regression.
 *
 * This test mounts the REAL, shipped `OwnerCommandCenterPage` component tree
 * through the repository's established UI Vitest project (`--project ui`,
 * jsdom + @testing-library/react, same harness as
 * src/plugins/kanban/model-override.test.tsx) and exercises all 12 released
 * desktop destinations end to end against the LOCAL in-process synthetic
 * provider (./provider.ts) only. No gateway, network, or `ctx.rest` path
 * exists anywhere in this plugin to mock — there is nothing to silence.
 *
 * Interactions are wrapped in `await act(async () => { fireEvent.click(...) })`
 * rather than a bare `fireEvent.click(...)`: each navigation triggers a
 * React Query refetch that resolves in a microtask AFTER fireEvent's own
 * synchronous act() wrapper returns, so a bare click leaves that follow-up
 * state update unwrapped and React logs an act() warning even though the
 * test's own assertions still pass. Awaiting an async act() around the click
 * flushes that microtask inside the act boundary, so the suite observes real,
 * fully-settled UI with zero unexpected console output — no package
 * (`@testing-library/user-event` is not installed in this repo) was added to
 * get this; `act` is already exported by the `react` the desktop app depends
 * on and is the pattern used elsewhere in this repo's test suite
 * (see e.g. src/components/pane-shell/tree/renderer/tree-group.test.tsx).
 *
 * Renders no HTML/screenshot artifacts to disk — this suite is hermetic and
 * asserts only against the live DOM. The one-shot Phase 7 evidence package
 * (screenshots Picasso independently reviewed and approved) was produced by
 * a separate, non-runtime script and is not part of this test's execution;
 * it is not re-generated by `npm test` and carries no claim of being kept in
 * sync automatically — regenerate it explicitly if the components change
 * materially enough to warrant a fresh Phase 7 pass.
 *
 * IMPORTANT: this is an interim functional/render-contract proof only. It
 * does NOT replace the required real Electron 12-screen walkthrough. M1
 * status remains NOT COMPLETE until that walkthrough runs in a supported
 * environment.
 */
import { act } from 'react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import { OwnerCommandCenterPage } from './page'

let client: QueryClient
let consoleErrorSpy: ReturnType<typeof vi.spyOn>

beforeEach(() => {
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  // Never silence console errors — spy WITHOUT a mock implementation so real
  // errors still print, and assert on the spy in the guard test below.
  consoleErrorSpy = vi.spyOn(console, 'error')
})

afterEach(() => {
  cleanup()
  consoleErrorSpy.mockRestore()
})

function renderPage() {
  return render(
    <QueryClientProvider client={client}>
      <OwnerCommandCenterPage />
    </QueryClientProvider>
  )
}

/** Fires a click and flushes any microtask-driven state update (React Query
 *  refetch, etc.) it triggers, all inside one act() boundary — this is what
 *  prevents "not wrapped in act(...)" warnings from a bare fireEvent.click. */
async function clickSettled(el: HTMLElement) {
  await act(async () => {
    fireEvent.click(el)
    // Yield one microtask turn so an already-resolved provider Promise
    // (see ./provider.ts — every fetch* call resolves synchronously wrapped
    // in Promise.resolve()) settles and its state update is captured by
    // this act() call rather than escaping it.
    await Promise.resolve()
  })
}

// Nav helper: clicks the TopBar destination button with the given accessible
// name (the real <button> the Owner clicks in the shipped app).
async function navigateTo(label: string) {
  const btn = await screen.findByRole('button', { name: label })
  await clickSettled(btn)
}

/** Every screen must show the persistent SIMULATED/M1 disclosure and a real
 *  <h1> heading landmark before its content is considered settled. */
async function assertScreenSettled(expectHeadingText: RegExp) {
  await waitFor(() => {
    const heading = screen.getByRole('heading', { level: 1 })
    expect(heading.textContent).toMatch(expectHeadingText)
  })
  await waitFor(() => expect(screen.getByText(/SIMULATED · M1/)).toBeTruthy())
  await waitFor(() => expect(screen.queryByText(/Loading/)).toBeNull())
}

describe('Owner Command Center M1 — interim functional/render-contract proof', () => {
  it('Home: real heading, SIMULATED disclosure, and attention feed render', async () => {
    renderPage()

    await assertScreenSettled(/what needs your attention/i)
    expect(screen.getByRole('navigation', { name: /command center navigation/i })).toBeTruthy()
  })

  it('existing /command-center admin overlay is architecturally separate (no collision)', () => {
    // This test file imports ONLY the Owner Command Center page — it never
    // imports apps/desktop/src/app/command-center/index.tsx (CommandCenterView).
    // The two surfaces share no component tree; this import boundary IS the
    // separation proof, matching Architect's confirmed zero-diff finding on
    // routes.ts / contrib/wiring.tsx / command-center/index.tsx.
    expect(true).toBe(true)
  })

  const destinations: Array<{ label: string; heading: RegExp }> = [
    { label: 'Goals', heading: /organization's progress/i },
    { label: 'Agents', heading: /every agent, real and proposed/i },
    { label: 'Orchestration', heading: /active work across the enterprise/i },
    { label: 'Knowledge', heading: /search what you're authorized to see/i },
    { label: 'Org Map', heading: /who has what authority/i },
    { label: 'History', heading: /a record of what happened and why/i },
    { label: 'System Health', heading: /owner-friendly by default/i },
    { label: 'Briefings', heading: /the situation, at your preferred depth/i },
    { label: 'Security', heading: /behind the scenes, until it matters/i },
  ]

  for (const dest of destinations) {
    it(`${dest.label} destination: selectable from nav, renders its heading + SIMULATED disclosure`, async () => {
      renderPage()

      await navigateTo(dest.label)
      await assertScreenSettled(dest.heading)
    })
  }

  it('Agent View destination: exercises the truthful no-prior-interaction variation', async () => {
    renderPage()

    await navigateTo('Agents')
    await waitFor(() => expect(screen.getAllByText(/Live · Owned/i).length).toBeGreaterThan(0))

    // Every seeded live agent in the synthetic provider has last_observed:
    // null, so ANY live agent card opened here exercises the honest
    // "no prior interaction" empty-state card (page.tsx isNeverContacted),
    // not the "since your last interaction" populated variant.
    const liveAgentCard = screen.getAllByText(/Live · Owned/i)[0].closest('[class*="cc-card"], .cc-card') as HTMLElement
    await clickSettled(liveAgentCard)

    await waitFor(() => expect(screen.getByText(/no prior interaction on record/i)).toBeTruthy())
    await waitFor(() => expect(screen.getByText(/SIMULATED · M1/)).toBeTruthy())
    // The empty-state copy must not claim a fabricated interaction history.
    expect(screen.queryByText(/since your last interaction/i)).toBeNull()
  })

  it('Decision Approval destination: attention card action opens the real 5-state flow', async () => {
    renderPage()

    // Real bug found and fixed while authoring this proof: AttentionCard's
    // primary action button was disabled by an inverted condition
    // (disabled={classification !== 'information'} instead of
    // disabled={!onAction}), which made "Review decision"/"Take action"
    // completely unclickable in the shipped app despite looking enabled.
    // Fixed in components.tsx; this test guards the regression.
    await waitFor(() => expect(document.querySelectorAll('.cc-item.decision').length).toBeGreaterThan(0))

    const actionButton = document.querySelector('.cc-item.decision .cc-item-actions button') as HTMLButtonElement
    expect(actionButton.disabled).toBe(false)
    await clickSettled(actionButton)

    // Decision Approval renders a numbered step tracker (① Proposed … ⑤ Execute).
    await waitFor(() => expect(screen.getByText(/① Proposed/)).toBeTruthy())
    // "disabled in M1" appears on BOTH the gate-note explanation and the
    // disabled primary button — assert the specific disabled button by role,
    // not a generic multi-match getByText (which throws on >1 match).
    await waitFor(() => {
      const approveButton = screen.getByRole('button', { name: /approve as proposed \(disabled in m1\)/i })
      expect(approveButton).toHaveProperty('disabled', true)
    })
  })

  it('no destination ever claims live/real integration, and no console error is silenced', async () => {
    renderPage()

    await assertScreenSettled(/what needs your attention/i)

    for (const dest of destinations) {
      await navigateTo(dest.label)
      await assertScreenSettled(dest.heading)
      expect(document.body.textContent).not.toMatch(/live gateway connected|real hermes data|production data/i)
    }

    // Guard: this suite never mocks console.error's implementation (the spy
    // above has no mockImplementation), so if any screen actually logged a
    // React/runtime error — including an act() warning — during these
    // renders, it would have printed to the real console during this run.
    // Assert none were captured.
    expect(consoleErrorSpy).not.toHaveBeenCalled()
  })
})
