"""
Shared Constants Package.
"""

HERMES_PROTOCOL_VERSION = "2.0.0"
DEFAULT_HERMES_PORT = 8642
DEFAULT_GATEWAY_WS_PATH = "/ws"
DEFAULT_GATEWAY_HTTP_PATH = "/api/v1"

__all__ = [
    "HERMES_PROTOCOL_VERSION",
    "DEFAULT_HERMES_PORT",
    "DEFAULT_GATEWAY_WS_PATH",
    "DEFAULT_GATEWAY_HTTP_PATH",
]
