import type { Locale } from '@/i18n'

const en = {
  information: 'Information only — nothing to fill in',
  optional: 'Optional — you can skip this step',
  required: 'Action required',
  skip: 'Skip this step',
  loading: 'Loading settings… You can continue reading.',
  retry: 'Retry loading',
  chooseProvider: 'Connect your API or ChatGPT, then choose a provider.',
  checkModel: 'Choose a model and click “Check configuration” to continue.',
  ownApi: 'My Own API',
  apiHint: 'Recommended: OpenRouter for tasks. Gemini API powers voice separately.',
  alternatives: 'Connect ChatGPT or another API',
  personality: 'Get to know each other',
  soulIntro: 'Four short answers help Czesiek adapt to you. Everything is optional and stays in this profile.',
  name: 'What should I call you?',
  purpose: 'What should I help you with most?',
  tone: 'How should I speak to you?',
  detail: 'How detailed should my answers be?',
  friendly: 'Friendly and natural',
  direct: 'Direct and concise',
  professional: 'Professional and calm',
  brief: 'Short answers',
  balanced: 'A useful middle ground',
  thorough: 'Step by step',
  preview: 'Your assistant’s instruction',
  savedLater: 'This instruction is saved when you finish setup and applies to new conversations.'
}

export const setupCopy: Record<Locale, typeof en> = {
  en,
  pl: {
    information: 'Tylko informacja — nic nie wpisujesz',
    optional: 'Opcjonalnie — możesz pominąć',
    required: 'Wymaga Twojego działania',
    skip: 'Pomiń ten krok',
    loading: 'Wczytuję ustawienia… Możesz czytać dalej.',
    retry: 'Wczytaj ponownie',
    chooseProvider: 'Podłącz własne API lub ChatGPT i wybierz dostawcę.',
    checkModel: 'Wybierz model i kliknij „Sprawdź konfigurację”, aby przejść dalej.',
    ownApi: 'Własne API (My Own API)',
    apiHint: 'Polecamy OpenRouter do zadań. Gemini API podłączysz osobno do głosu.',
    alternatives: 'Podłącz ChatGPT lub inne API',
    personality: 'Poznajmy się',
    soulIntro:
      'Cztery krótkie odpowiedzi pomogą Cześkowi dopasować się do Ciebie. Wszystkie są opcjonalne i dotyczą tylko tego profilu.',
    name: 'Jak mam się do Ciebie zwracać?',
    purpose: 'W czym mam Ci najczęściej pomagać?',
    tone: 'Jak mam z Tobą rozmawiać?',
    detail: 'Jak szczegółowych odpowiedzi oczekujesz?',
    friendly: 'Przyjaźnie i naturalnie',
    direct: 'Krótko i konkretnie',
    professional: 'Profesjonalnie i spokojnie',
    brief: 'Krótkie odpowiedzi',
    balanced: 'Tyle szczegółów, ile potrzeba',
    thorough: 'Krok po kroku',
    preview: 'Instrukcja Twojego asystenta',
    savedLater: 'Instrukcja zapisze się po zakończeniu konfiguracji i będzie działać w nowych rozmowach.'
  },
  ja: {
    information: '説明のみ — 入力不要',
    optional: '任意 — スキップできます',
    required: '操作が必要です',
    skip: 'この手順をスキップ',
    loading: '設定を読み込み中… 説明は続けて読めます。',
    retry: '再読み込み',
    chooseProvider: 'APIまたはChatGPTを接続してプロバイダーを選んでください。',
    checkModel: 'モデルを選び、設定確認を押してください。',
    ownApi: '自分のAPI (My Own API)',
    apiHint: 'タスクにはOpenRouter、音声にはGemini APIを推奨します。',
    alternatives: 'ChatGPTまたは別のAPIを接続',
    personality: 'あなたについて',
    soulIntro: '4つの任意の回答でCzesiekを調整します。このプロファイルだけに保存されます。',
    name: '何とお呼びしますか？',
    purpose: '主に何をお手伝いしますか？',
    tone: 'どのような話し方がよいですか？',
    detail: '回答の詳しさは？',
    friendly: '親しみやすく自然に',
    direct: '簡潔に',
    professional: '落ち着いて丁寧に',
    brief: '短く',
    balanced: '必要な詳しさ',
    thorough: '手順を詳しく',
    preview: 'アシスタントへの指示',
    savedLater: '設定完了時に保存され、新しい会話に適用されます。'
  },
  zh: {
    information: '仅供参考 — 无需填写',
    optional: '可选 — 可以跳过',
    required: '需要操作',
    skip: '跳过此步骤',
    loading: '正在加载设置… 可继续阅读。',
    retry: '重新加载',
    chooseProvider: '连接自己的API或ChatGPT，然后选择服务商。',
    checkModel: '选择模型并点击检查配置。',
    ownApi: '自己的API (My Own API)',
    apiHint: '推荐OpenRouter处理任务，Gemini API用于语音。',
    alternatives: '连接ChatGPT或其他API',
    personality: '互相了解',
    soulIntro: '四个可选问题帮助Czesiek适应你。仅保存在此配置中。',
    name: '如何称呼你？',
    purpose: '主要帮你做什么？',
    tone: '你喜欢什么交流风格？',
    detail: '回答应多详细？',
    friendly: '友好自然',
    direct: '简短直接',
    professional: '专业平和',
    brief: '简短回答',
    balanced: '适当详细',
    thorough: '分步说明',
    preview: '助手指令',
    savedLater: '完成设置后保存，并用于新的对话。'
  },
  'zh-hant': {
    information: '僅供參考 — 無需填寫',
    optional: '選填 — 可以略過',
    required: '需要操作',
    skip: '略過此步驟',
    loading: '正在載入設定… 可繼續閱讀。',
    retry: '重新載入',
    chooseProvider: '連接自己的API或ChatGPT，然後選擇服務商。',
    checkModel: '選擇模型並點擊檢查設定。',
    ownApi: '自己的API (My Own API)',
    apiHint: '推薦OpenRouter處理任務，Gemini API用於語音。',
    alternatives: '連接ChatGPT或其他API',
    personality: '互相了解',
    soulIntro: '四個選填問題幫助Czesiek適應你。僅儲存在此設定檔中。',
    name: '如何稱呼你？',
    purpose: '主要幫你做什麼？',
    tone: '你喜歡什麼交流風格？',
    detail: '回答應多詳細？',
    friendly: '友好自然',
    direct: '簡短直接',
    professional: '專業平和',
    brief: '簡短回答',
    balanced: '適當詳細',
    thorough: '分步說明',
    preview: '助理指令',
    savedLater: '完成設定後儲存，並用於新的對話。'
  },
  ru: {
    information: 'Только информация — заполнять не нужно',
    optional: 'Необязательно — можно пропустить',
    required: 'Требуется действие',
    skip: 'Пропустить шаг',
    loading: 'Загрузка настроек… Можно читать дальше.',
    retry: 'Загрузить снова',
    chooseProvider: 'Подключите свой API или ChatGPT и выберите провайдера.',
    checkModel: 'Выберите модель и нажмите «Проверить конфигурацию».',
    ownApi: 'Свой API (My Own API)',
    apiHint: 'Рекомендуем OpenRouter для задач и Gemini API для голоса.',
    alternatives: 'Подключить ChatGPT или другой API',
    personality: 'Познакомимся',
    soulIntro: 'Четыре необязательных ответа помогут настроить Czesiek. Они сохраняются только в этом профиле.',
    name: 'Как к вам обращаться?',
    purpose: 'В чём чаще всего помогать?',
    tone: 'Как с вами общаться?',
    detail: 'Насколько подробными должны быть ответы?',
    friendly: 'Дружелюбно и естественно',
    direct: 'Коротко и по делу',
    professional: 'Спокойно и профессионально',
    brief: 'Кратко',
    balanced: 'По необходимости',
    thorough: 'Пошагово',
    preview: 'Инструкция помощника',
    savedLater: 'Сохраняется при завершении настройки и применяется к новым разговорам.'
  },
  ar: {
    information: 'للمعلومات فقط — لا يلزم إدخال شيء',
    optional: 'اختياري — يمكنك التخطي',
    required: 'يتطلب إجراءً',
    skip: 'تخطي هذه الخطوة',
    loading: 'جارٍ تحميل الإعدادات… يمكنك متابعة القراءة.',
    retry: 'إعادة التحميل',
    chooseProvider: 'اربط API الخاص بك أو ChatGPT ثم اختر المزود.',
    checkModel: 'اختر النموذج واضغط التحقق من الإعدادات.',
    ownApi: 'API الخاص بي (My Own API)',
    apiHint: 'نوصي بـOpenRouter للمهام وGemini API للصوت.',
    alternatives: 'ربط ChatGPT أو API آخر',
    personality: 'لنتعرف على بعضنا',
    soulIntro: 'أربع إجابات اختيارية لتخصيص Czesiek. تحفظ في هذا الملف فقط.',
    name: 'بماذا أناديك؟',
    purpose: 'بماذا أساعدك غالباً؟',
    tone: 'كيف تفضل أن أتحدث معك؟',
    detail: 'ما مستوى التفاصيل الذي تفضله؟',
    friendly: 'ودّي وطبيعي',
    direct: 'مباشر ومختصر',
    professional: 'مهني وهادئ',
    brief: 'إجابات قصيرة',
    balanced: 'تفاصيل حسب الحاجة',
    thorough: 'خطوة بخطوة',
    preview: 'تعليمات مساعدك',
    savedLater: 'تحفظ عند إكمال الإعداد وتطبق على المحادثات الجديدة.'
  }
}
