"""Pioneer provider profile."""

from providers import register_provider
from providers.base import ProviderProfile


pioneer = ProviderProfile(
    name="pioneer",
    aliases=("pioneer-ai", "pioneerai"),
    display_name="Pioneer",
    description="Pioneer - OpenAI-compatible multi-model inference endpoint",
    signup_url="https://pioneer.ai/",
    env_vars=("PIONEER_API_KEY", "PIONEER_BASE_URL"),
    base_url="https://api.pioneer.ai/v1",
    auth_type="api_key",
    supports_developer_role=False,
    default_aux_model="gpt-5.4-mini",
    fallback_models=(
        "claude-haiku-4-5",
        "claude-opus-4-1",
        "claude-opus-4-5",
        "claude-opus-4-6",
        "claude-opus-4-7",
        "claude-opus-4-8",
        "claude-sonnet-4-6",
        "deepseek-ai/DeepSeek-V4-Flash",
        "deepseek-ai/DeepSeek-V4-Pro",
        "gemini-3-flash",
        "gemini-3.1-pro",
        "gemini-3.5-flash",
        "gpt-4.1",
        "gpt-4.1-mini",
        "gpt-4.1-nano",
        "gpt-4o",
        "gpt-4o-mini",
        "gpt-5-mini",
        "gpt-5-nano",
        "gpt-5.1",
        "gpt-5.4",
        "gpt-5.4-mini",
        "gpt-5.4-nano",
        "gpt-5.5",
        "LiquidAI/LFM2-24B-A2B",
        "meta-llama/Llama-3.1-8B-Instruct",
        "meta-llama/Llama-3.2-1B-Instruct",
        "meta-llama/Llama-3.2-3B-Instruct",
        "meta-llama/Llama-3.3-70B-Instruct",
        "MiniMaxAI/MiniMax-M2.7",
        "MiniMaxAI/MiniMax-M3",
        "mistral-medium-3.5",
        "mistralai/Mistral-Nemo-Instruct-2407",
        "mistralai/Mistral-Small-4-119B-2603",
        "moonshotai/Kimi-K2.6",
        "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
        "openai/gpt-oss-120b",
        "openai/gpt-oss-20b",
        "Qwen/Qwen3-32B",
        "Qwen/Qwen3-8B",
        "Qwen/Qwen3.6-35B-A3B",
        "qwen3.6-flash",
        "qwen3.6-max-preview",
        "qwen3.6-plus",
        "qwen3.7-max",
        "XiaomiMiMo/MiMo-V2.5-Pro",
        "zai-org/GLM-5.1",
    ),
)

register_provider(pioneer)
