"""Hermes JIT Context OS - Native Context Engine.

Implements the ContextEngine ABC to act as a native context engine in Hermes (context.engine: jit).
Unlike a passive pre_llm_call hook, JitContextEngine actively selects and filters the wire messages
sent to LLM APIs:
    [System Prompt + <ONA_CONTEXT>] + [Last 3-4 User Turns]
ensuring stable, predictable request size (3,000 - 5,000 tokens) regardless of session length.
Full history remains intact in the SQLite session transcript.
"""

from __future__ import annotations

import copy
import logging
import os
import re
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

# Ensure ona-context plugin root is in sys.path
_PLUGIN_ROOT = Path(__file__).resolve().parent
if str(_PLUGIN_ROOT) not in sys.path:
    sys.path.insert(0, str(_PLUGIN_ROOT))

logger = logging.getLogger("hermes.plugins.ona-context.engine")

try:
    from agent.context_engine import ContextEngine
except ImportError:
    # Fallback for environments where agent.context_engine is not yet available
    class ContextEngine:  # type: ignore[no-redef]
        name: str = "jit"
        last_prompt_tokens: int = 0
        last_completion_tokens: int = 0
        last_total_tokens: int = 0
        threshold_tokens: int = 35000
        context_length: int = 200000
        compression_count: int = 0
        protect_first_n: int = 1
        protect_last_n: int = 8
        emit_automatic_compaction_status: bool = False

        def update_from_response(self, usage: Dict[str, Any]) -> None:
            pass

        def should_compress(self, prompt_tokens: int = None) -> bool:
            return False

        def compress(self, messages: List[Dict[str, Any]], **kwargs) -> List[Dict[str, Any]]:
            return messages

        def select_context(self, request_messages: List[Dict[str, Any]], **kwargs) -> List[Dict[str, Any]]:
            return request_messages


# Global cache for latest capsule generated by pre_llm hook or on-demand
_LATEST_CAPSULE_CACHE: Dict[str, Any] = {
    "session_id": "",
    "capsule": "",
    "timestamp": 0.0,
    "scope": "general",
}

_JIT_ENGINE_ACTIVE: bool = False


def set_jit_engine_active(active: bool = True) -> None:
    global _JIT_ENGINE_ACTIVE
    _JIT_ENGINE_ACTIVE = active


def is_jit_engine_active() -> bool:
    global _JIT_ENGINE_ACTIVE
    return _JIT_ENGINE_ACTIVE or os.environ.get("HERMES_CONTEXT_ENGINE") == "jit"


def update_latest_capsule(session_id: str, capsule: str, scope: str = "general") -> None:
    global _LATEST_CAPSULE_CACHE
    _LATEST_CAPSULE_CACHE = {
        "session_id": session_id,
        "capsule": capsule,
        "timestamp": time.time(),
        "scope": scope,
    }


def get_latest_capsule(session_id: str, max_age_seconds: float = 60.0) -> Optional[str]:
    global _LATEST_CAPSULE_CACHE
    if (
        _LATEST_CAPSULE_CACHE.get("capsule")
        and _LATEST_CAPSULE_CACHE.get("session_id") == session_id
        and (time.time() - _LATEST_CAPSULE_CACHE.get("timestamp", 0.0)) < max_age_seconds
    ):
        return _LATEST_CAPSULE_CACHE["capsule"]
    return None


class JitContextEngine(ContextEngine):
    """Hermes JIT Context OS native Context Engine.
    
    Active context engine:
    1. Replaces wire messages with [System Prompt with <ONA_CONTEXT>] + [Last 4 user turns].
    2. Proactively truncates stale tool outputs (>2000 chars) from prior turns.
    3. Keeps wire requests lean (3,000 - 5,000 tokens) on every call.
    4. Preserves full transcript history in SQLite session DB.
    """

    def __init__(
        self,
        keep_turns: int = 4,
        threshold_tokens: int = 35000,
        context_length: int = 200000,
        model: str = "",
        provider: str = "",
    ):
        super().__init__()
        self._name = "jit"
        self.keep_turns = keep_turns
        self.threshold_tokens = threshold_tokens
        self.context_length = context_length
        self.model = model
        self.provider = provider
        self.base_url = ""
        self.api_key = ""
        self.api_mode = ""

        self.last_prompt_tokens = 0
        self.last_completion_tokens = 0
        self.last_total_tokens = 0
        self.compression_count = 0

        self.protect_first_n = 1
        self.protect_last_n = keep_turns * 2
        self.emit_automatic_compaction_status = False

        self.session_id = "default"
        self.session_db = None
        set_jit_engine_active(True)

    @property
    def name(self) -> str:
        return self._name

    def __deepcopy__(self, memo: Dict[int, Any]) -> "JitContextEngine":
        """Safe deepcopy handling locks and unpicklable handles."""
        cls = self.__class__
        result = cls.__new__(cls)
        memo[id(self)] = result
        for k, v in self.__dict__.items():
            if k in ("_lock", "session_db", "conn"):
                setattr(result, k, None)
            else:
                try:
                    setattr(result, k, copy.deepcopy(v, memo))
                except Exception:
                    setattr(result, k, v)
        set_jit_engine_active(True)
        return result

    def bind_session_state(self, session_db: Any = None, session_id: Optional[str] = None) -> None:
        """Called by Hermes agent_init to bind session context."""
        self.session_db = session_db
        if session_id:
            self.session_id = session_id
        set_jit_engine_active(True)

    def update_model(
        self,
        model: str = "",
        context_length: int = 0,
        base_url: str = "",
        api_key: str = "",
        provider: str = "",
        api_mode: str = "",
        **kwargs: Any,
    ) -> None:
        """Update model and enforce hard threshold ceiling."""
        self.model = model
        self.context_length = context_length or 200000
        self.base_url = base_url
        self.api_key = api_key
        self.provider = provider
        self.api_mode = api_mode
        # Hard ceiling at 35,000 tokens regardless of window (prevents Gemini 1M runaway)
        self.threshold_tokens = min(35000, max(5000, int(self.context_length * 0.5)))

    def update_from_response(self, usage: Dict[str, Any]) -> None:
        """Track tokens returned from LLM API."""
        if not isinstance(usage, dict):
            return
        self.last_prompt_tokens = usage.get("prompt_tokens") or usage.get("input_tokens") or 0
        self.last_completion_tokens = usage.get("completion_tokens") or usage.get("output_tokens") or 0
        self.last_total_tokens = usage.get("total_tokens") or (self.last_prompt_tokens + self.last_completion_tokens)

    def should_compress(self, prompt_tokens: int = None) -> bool:
        """Trigger compaction only when transcript exceeds threshold_tokens."""
        tokens = prompt_tokens if prompt_tokens is not None else self.last_prompt_tokens
        return bool(self.threshold_tokens and tokens >= self.threshold_tokens)

    def compress(
        self,
        messages: List[Dict[str, Any]],
        current_tokens: Optional[int] = None,
        focus_topic: Optional[str] = None,
        force: bool = False,
        memory_context: str = "",
    ) -> List[Dict[str, Any]]:
        """Compact messages transcript when /compress is called."""
        self.compression_count += 1
        return self._slice_turns(messages, keep_turns=max(self.keep_turns, 6), prune_tools=True)

    def select_context(
        self,
        request_messages: List[Dict[str, Any]],
        *,
        conversation_messages: List[Dict[str, Any]] = None,
        incoming_message: Dict[str, Any] = None,
        budget_tokens: int = 0,
    ) -> List[Dict[str, Any]]:
        """Active Context Filter: selects [System Prompt + ONA_CONTEXT] + [Last 4 Turns].

        Wire messages are replaced for THIS request only.
        Persisted transcript in SQLite is completely untouched.
        """
        mode = os.environ.get("ONA_CONTEXT_MODE", "active").lower()
        if mode in ("shadow", "off", "disabled"):
            return request_messages

        if not request_messages:
            return request_messages

        set_jit_engine_active(True)

        # 1. Extract system message
        sys_msgs: List[Dict[str, Any]] = []
        other_msgs: List[Dict[str, Any]] = []
        for m in request_messages:
            if m.get("role") == "system":
                sys_msgs.append(dict(m))
            else:
                other_msgs.append(dict(m))

        if not sys_msgs:
            sys_msg = {"role": "system", "content": ""}
        else:
            sys_msg = sys_msgs[0]
            # Merge extra system messages if any
            if len(sys_msgs) > 1:
                extra_content = "\n\n".join(m.get("content", "") for m in sys_msgs[1:] if m.get("content"))
                if extra_content:
                    sys_msg["content"] = f"{sys_msg.get('content', '')}\n\n{extra_content}"

        # 2. Get or compile ONA_CONTEXT capsule
        capsule = self._resolve_capsule(incoming_message, other_msgs)

        # 3. Inject capsule into system prompt (replacing old capsule if present)
        sys_content = sys_msg.get("content", "")
        if capsule:
            if "<ONA_CONTEXT" in sys_content:
                sys_content = re.sub(r"<ONA_CONTEXT[\s\S]*?</ONA_CONTEXT>", capsule.strip(), sys_content)
            else:
                sys_content = f"{sys_content.rstrip()}\n\n{capsule.strip()}"
        sys_msg["content"] = sys_content

        # 4. Slice to the last N user turns
        selected_history = self._slice_turns(
            other_msgs,
            keep_turns=self.keep_turns,
            prune_tools=True,
        )

        return [sys_msg] + selected_history

    def _resolve_capsule(
        self,
        incoming_message: Optional[Dict[str, Any]],
        history_messages: List[Dict[str, Any]],
    ) -> str:
        """Retrieve cached capsule or compile fresh on-demand."""
        session_id = self.session_id or "default"
        cached = get_latest_capsule(session_id)
        if cached:
            return cached

        # Compile fresh capsule
        try:
            from l0.db import get_db
            from l0.overlay import ensure_session, get_session_cwd
            from l1.scope import resolve_scope
            from context.compiler import compile_context

            user_text = ""
            if incoming_message and isinstance(incoming_message, dict):
                user_text = incoming_message.get("content", "")
            if not user_text and history_messages:
                for m in reversed(history_messages):
                    if m.get("role") == "user" and isinstance(m.get("content"), str):
                        user_text = m["content"]
                        break

            conn = get_db(session_id=session_id)
            try:
                session_cwd = get_session_cwd(conn, session_id)
                default_scope = "general"
                if session_cwd and Path(session_cwd).exists():
                    cname = Path(session_cwd).name
                    if cname not in ("wojciechwiesner", "Projects", "active"):
                        default_scope = cname
                
                sess_obj = ensure_session(conn, session_id, default_scope=default_scope)
                curr_scope = sess_obj.get("active_scope") or default_scope
                active_scope, _, _, _ = resolve_scope(user_text, curr_scope)

                res = compile_context(
                    conn=conn,
                    session_id=session_id,
                    user_message=user_text,
                    transcript_messages=history_messages,
                    active_scope=active_scope,
                    default_scope=default_scope,
                    session_cwd=session_cwd,
                )
                capsule = str(res)
                update_latest_capsule(session_id, capsule, active_scope)
                return capsule
            finally:
                conn.close()
        except Exception as exc:
            logger.warning("JitContextEngine failed to compile capsule: %s", exc)
            return ""

    def _slice_turns(
        self,
        messages: List[Dict[str, Any]],
        keep_turns: int = 4,
        prune_tools: bool = True,
    ) -> List[Dict[str, Any]]:
        """Slice history to keep the last `keep_turns` user turns intact."""
        if not messages:
            return []

        user_indices = [i for i, m in enumerate(messages) if m.get("role") == "user"]
        if not user_indices:
            # No user messages found; keep the tail
            return messages[-keep_turns * 2:]

        if len(user_indices) <= keep_turns:
            sliced = [dict(m) for m in messages]
        else:
            cut_idx = user_indices[-keep_turns]
            sliced = [dict(m) for m in messages[cut_idx:]]

        if prune_tools:
            self._prune_older_tool_outputs(sliced)

        # Strip any <ONA_CONTEXT> from user messages to prevent duplication
        for m in sliced:
            if m.get("role") == "user" and isinstance(m.get("content"), str):
                if "<ONA_CONTEXT" in m["content"]:
                    m["content"] = re.sub(r"<ONA_CONTEXT[\s\S]*?</ONA_CONTEXT>", "", m["content"]).strip()

        return sliced

    def _prune_older_tool_outputs(self, messages: List[Dict[str, Any]], max_chars: int = 2000) -> None:
        """Truncate massive tool dumps from older turns in the active window."""
        user_indices = [i for i, m in enumerate(messages) if m.get("role") == "user"]
        if not user_indices:
            return

        last_user_idx = user_indices[-1]
        for i, m in enumerate(messages):
            if i < last_user_idx and m.get("role") == "tool":
                content = m.get("content")
                if isinstance(content, str) and len(content) > max_chars:
                    m["content"] = (
                        content[:1000]
                        + f"\n... [tool output pruned by JIT context engine ({len(content)} chars)]"
                    )

    def get_status(self) -> Dict[str, Any]:
        """Status dict with standard fields run_agent.py expects."""
        last_prompt = max(self.last_prompt_tokens, 0)
        return {
            "name": self.name,
            "last_prompt_tokens": last_prompt,
            "threshold_tokens": self.threshold_tokens,
            "context_length": self.context_length,
            "usage_percent": min(100, (last_prompt / self.context_length * 100)) if self.context_length else 0,
            "compression_count": self.compression_count,
            "keep_turns": self.keep_turns,
        }
