"""Optional synchronous PostgreSQL backend for the Hermes durable state store."""

from state_store.postgres.core import (
    BoundedConnectionPool,
    MigrationReport,
    PostgresConfigurationError,
    PostgresConnectionError,
    PostgresDriverUnavailableError,
    PostgresHealthReport,
    PostgresPoolTimeoutError,
    PostgresReadOnlyError,
    PostgresSchemaValidationError,
    PostgresSchemaVersionError,
    PostgresStateStore,
    PostgresStateStoreError,
    ddl_table_names,
    schema_manifest_matches_postgres_ddl,
)
from state_store.postgres.ddl import (
    CORE_INDEXES,
    CORE_INDEX_CONTRACTS,
    CORE_TABLES,
    PostgresColumnUpgrade,
    PostgresColumnContract,
    PostgresIndexContract,
    POSTGRES_COLUMN_CONTRACTS,
    SCHEMA_VERSION,
    TELEGRAM_INDEXES,
    TELEGRAM_INDEX_CONTRACTS,
    TELEGRAM_TABLES,
    V16_TO_V22_COLUMN_UPGRADES,
    schema_statements,
    schema_table_statements,
)
from state_store.postgres.session_db import PostgresSessionDB
from state_store.postgres.session_db_base import PostgresSessionDBBase

__all__ = [
    "BoundedConnectionPool",
    "CORE_INDEXES",
    "CORE_INDEX_CONTRACTS",
    "CORE_TABLES",
    "MigrationReport",
    "PostgresConfigurationError",
    "PostgresConnectionError",
    "PostgresDriverUnavailableError",
    "PostgresHealthReport",
    "PostgresPoolTimeoutError",
    "PostgresReadOnlyError",
    "PostgresSchemaValidationError",
    "PostgresSchemaVersionError",
    "PostgresStateStore",
    "PostgresStateStoreError",
    "PostgresSessionDB",
    "PostgresSessionDBBase",
    "SCHEMA_VERSION",
    "PostgresColumnUpgrade",
    "PostgresColumnContract",
    "PostgresIndexContract",
    "POSTGRES_COLUMN_CONTRACTS",
    "TELEGRAM_INDEXES",
    "TELEGRAM_INDEX_CONTRACTS",
    "TELEGRAM_TABLES",
    "V16_TO_V22_COLUMN_UPGRADES",
    "ddl_table_names",
    "schema_manifest_matches_postgres_ddl",
    "schema_statements",
    "schema_table_statements",
]
