"""Cron installer for MHLW designated-substances monitor."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

JOB_NAME = "mhlw-designated-check"
# Every Monday 09:00 (local wall clock — JST if OS is JST)
DEFAULT_SCHEDULE = "0 9 * * 1"
_CRON_SCRIPT_TIMEOUT = 300
_CRON_RUN_TIMEOUT = 300


def _ensure_cron_script_timeout(*, min_seconds: int = _CRON_SCRIPT_TIMEOUT) -> dict[str, Any]:
    try:
        import yaml
        from hermes_cli.config import ensure_hermes_home, get_config_path, load_config
        from utils import atomic_yaml_write
    except Exception as exc:
        return {"ok": False, "error": str(exc)}

    ensure_hermes_home()
    current = int(load_config().get("cron", {}).get("script_timeout_seconds") or 120)
    if current >= min_seconds:
        return {"ok": True, "updated": False, "script_timeout_seconds": current}

    config_path = get_config_path()
    user_config: dict = {}
    if config_path.exists():
        try:
            with config_path.open("r", encoding="utf-8") as fh:
                user_config = yaml.safe_load(fh) or {}
        except Exception:
            user_config = {}
    cron_cfg = user_config.setdefault("cron", {})
    cron_cfg["script_timeout_seconds"] = min_seconds
    atomic_yaml_write(config_path, user_config, sort_keys=False)
    return {"ok": True, "updated": True, "script_timeout_seconds": min_seconds}


def _write_cron_wrapper(path: Path, *, python_exe: Path, repo_root: Path, extra_args: list[str]) -> None:
    payload = {
        "python": str(python_exe),
        "repo_root": str(repo_root),
        "extra_args": extra_args,
    }
    content = f"""# Auto-generated by hermes scrapling-feeds cron install-mhlw.
import json
import os
import subprocess
import sys

PAYLOAD = {json.dumps(payload, ensure_ascii=True, indent=2)}

env = os.environ.copy()
env.setdefault("PYTHONIOENCODING", "utf-8")

args = ["scrapling-feeds", "mhlw-check", "--cron-stdout", *PAYLOAD.get("extra_args", [])]
result = subprocess.run(
    [PAYLOAD["python"], "-m", "hermes_cli.main", *args],
    cwd=PAYLOAD["repo_root"],
    env=env,
    capture_output=True,
    text=True,
    encoding="utf-8",
    errors="replace",
    timeout={_CRON_RUN_TIMEOUT},
)
stdout = (result.stdout or "").strip()
stderr = (result.stderr or "").strip()
if result.returncode != 0:
    if stderr:
        print(stderr)
    if stdout:
        print(stdout)
    sys.exit(result.returncode)
if stdout:
    print(stdout)
"""
    path.write_text(content, encoding="utf-8")


def _ensure_cron_script(*, record_baseline: bool) -> dict[str, str]:
    from hermes_constants import get_hermes_home

    import hermes_cli

    scripts_dir = Path(get_hermes_home()) / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    repo_root = Path(hermes_cli.__file__).resolve().parent.parent
    python_exe = Path(sys.executable).resolve()
    extra_args = ["--record-baseline"] if record_baseline else []
    script_path = scripts_dir / "mhlw-designated-check.py"
    _write_cron_wrapper(
        script_path,
        python_exe=python_exe,
        repo_root=repo_root,
        extra_args=extra_args,
    )
    return {"script": script_path.name, "path": str(script_path)}


def _preflight_delivery(deliver: str) -> dict[str, Any]:
    try:
        from cron.scheduler import _normalize_deliver_value, _resolve_delivery_targets
    except Exception as exc:
        return {"ok": True, "skipped": True, "reason": str(exc)}

    normalized = _normalize_deliver_value(deliver)
    if normalized == "local":
        return {"ok": True, "deliver": normalized, "targets": []}
    targets = _resolve_delivery_targets({"deliver": normalized, "origin": None})
    if not targets:
        return {
            "ok": False,
            "deliver": normalized,
            "error": (
                f"No delivery targets for deliver={normalized!r}. "
                "Set TELEGRAM_HOME_CHANNEL / DISCORD_HOME_CHANNEL in ~/.hermes/.env"
            ),
        }
    return {"ok": True, "deliver": normalized, "targets": targets}


def _find_job_by_name(name: str) -> dict[str, Any] | None:
    from cron.jobs import list_jobs

    for job in list_jobs(include_disabled=True):
        if (job.get("name") or "").strip() == name:
            return job
    return None


def _upsert_job(*, schedule: str, script: str, deliver: str, paused: bool) -> dict[str, Any]:
    from cron.jobs import create_job, pause_job, update_job

    existing = _find_job_by_name(JOB_NAME)
    if existing:
        job = update_job(
            existing["id"],
            {
                "schedule": schedule,
                "script": script,
                "no_agent": True,
                "deliver": deliver,
                "prompt": JOB_NAME,
            },
        )
        if not job:
            job = existing
    else:
        job = create_job(
            prompt=JOB_NAME,
            schedule=schedule,
            name=JOB_NAME,
            deliver=deliver,
            script=script,
            no_agent=True,
        )
    if paused and job.get("id"):
        paused_job = pause_job(job["id"], reason="mhlw designated cron installed paused")
        if paused_job:
            job = paused_job
    return job


def install_mhlw_cron(
    *,
    schedule: str = DEFAULT_SCHEDULE,
    deliver: str = "local",
    dry_run: bool = False,
    paused: bool = False,
    force: bool = False,
    record_baseline: bool = False,
) -> dict[str, Any]:
    """Install weekly MHLW 指定薬物部会 / 施行チェック cron job."""
    scripts = _ensure_cron_script(record_baseline=record_baseline)
    preview = {
        "name": JOB_NAME,
        "schedule": schedule,
        "script": scripts["script"],
        "no_agent": True,
        "deliver": deliver,
    }
    if dry_run:
        return {
            "success": True,
            "dry_run": True,
            "job": preview,
            "scripts": scripts,
            "delivery": _preflight_delivery(deliver),
        }

    if deliver != "local":
        delivery_check = _preflight_delivery(deliver)
        if not delivery_check.get("ok") and not force:
            return {"success": False, **delivery_check}
    else:
        delivery_check = _preflight_delivery(deliver)

    timeout_result = _ensure_cron_script_timeout()
    if not timeout_result.get("ok"):
        return {"success": False, "error": "cron timeout update failed", **timeout_result}

    job = _upsert_job(
        schedule=schedule,
        script=scripts["script"],
        deliver=deliver,
        paused=paused,
    )
    return {
        "success": True,
        "paused": paused,
        "job": {
            "id": job.get("id"),
            "name": job.get("name"),
            "state": job.get("state"),
            "schedule": job.get("schedule_display"),
            "next_run_at": job.get("next_run_at"),
            "deliver": job.get("deliver"),
        },
        "scripts": scripts,
        "delivery": delivery_check,
        "cron_script_timeout": timeout_result,
        "schedule_note": "Cron uses OS local wall time (JST if system is JST).",
        "manual_test": [
            "py -3 -m hermes_cli.main scrapling-feeds mhlw-check",
            f"py -3 {scripts['path']}",
        ],
        "resume_command": f"hermes cron resume {job.get('id')}" if paused and job.get("id") else None,
    }
