"""Generated Unicode policy data for Discord CHAT_INPUT command names.

Generated by ``scripts/generate_discord_command_unicode.py`` from official UCD
17.0.0 data, relative to Python 3.11's UCD 14.0.0 floor.
Do not edit by hand. Ranges are sorted, disjoint, inclusive, and adjacency-
compressed.

Sources and SHA-256:
- https://www.unicode.org/Public/14.0.0/ucd/UnicodeData.txt
  36018e68657fdcb3485f636630ffe8c8532e01c977703d2803f5b89d6c5feafb
- https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
  2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c
- https://www.unicode.org/Public/17.0.0/ucd/Scripts.txt
  9f5e50d3abaee7d6ce09480f325c706f485ae3240912527e651954d2d6b035bf
- https://www.unicode.org/Public/17.0.0/ucd/SpecialCasing.txt
  efc25faf19de21b92c1194c111c932e03d2a5eaf18194e33f1156e96de4c9588
"""

_APP_COMMAND_UNICODE_BASELINE_VERSION = "14.0.0"
_APP_COMMAND_UNICODE_VERSION = "17.0.0"
_APP_COMMAND_UNICODE_SOURCE_SHA256 = {
    "baseline_unicode_data": "36018e68657fdcb3485f636630ffe8c8532e01c977703d2803f5b89d6c5feafb",
    "unicode_data": "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c",
    "scripts": "9f5e50d3abaee7d6ce09480f325c706f485ae3240912527e651954d2d6b035bf",
    "special_casing": "efc25faf19de21b92c1194c111c932e03d2a5eaf18194e33f1156e96de4c9588",
}

# General_Category L*/N* code points present in UCD 17.0.0 but absent
# from the UCD 14.0.0 runtime floor.
_APP_COMMAND_LN_COMPATIBILITY_RANGES = (
    (0x088F, 0x088F),
    (0x0C5C, 0x0C5C),
    (0x0CDC, 0x0CDC),
    (0x1C89, 0x1C8A),
    (0xA7CB, 0xA7CF),
    (0xA7D2, 0xA7D2),
    (0xA7D4, 0xA7D4),
    (0xA7DA, 0xA7DC),
    (0xA7F1, 0xA7F1),
    (0x105C0, 0x105F3),
    (0x10940, 0x10959),
    (0x10D40, 0x10D65),
    (0x10D6F, 0x10D85),
    (0x10EC2, 0x10EC7),
    (0x1123F, 0x11240),
    (0x11380, 0x11389),
    (0x1138B, 0x1138B),
    (0x1138E, 0x1138E),
    (0x11390, 0x113B5),
    (0x113B7, 0x113B7),
    (0x113D1, 0x113D1),
    (0x113D3, 0x113D3),
    (0x116D0, 0x116E3),
    (0x11BC0, 0x11BE0),
    (0x11BF0, 0x11BF9),
    (0x11DB0, 0x11DDB),
    (0x11DE0, 0x11DE9),
    (0x11F02, 0x11F02),
    (0x11F04, 0x11F10),
    (0x11F12, 0x11F33),
    (0x11F50, 0x11F59),
    (0x1342F, 0x1342F),
    (0x13441, 0x13446),
    (0x13460, 0x143FA),
    (0x16100, 0x1611D),
    (0x16130, 0x16139),
    (0x16D40, 0x16D6C),
    (0x16D70, 0x16D79),
    (0x16EA0, 0x16EB8),
    (0x16EBB, 0x16ED3),
    (0x16FF2, 0x16FF6),
    (0x187F8, 0x187FF),
    (0x18CFF, 0x18CFF),
    (0x18D09, 0x18D1E),
    (0x18D80, 0x18DF2),
    (0x1B132, 0x1B132),
    (0x1B155, 0x1B155),
    (0x1CCF0, 0x1CCF9),
    (0x1D2C0, 0x1D2D3),
    (0x1DF25, 0x1DF2A),
    (0x1E030, 0x1E06D),
    (0x1E4D0, 0x1E4EB),
    (0x1E4F0, 0x1E4F9),
    (0x1E5D0, 0x1E5ED),
    (0x1E5F0, 0x1E5FA),
    (0x1E6C0, 0x1E6DE),
    (0x1E6E0, 0x1E6E2),
    (0x1E6E4, 0x1E6E5),
    (0x1E6E7, 0x1E6ED),
    (0x1E6F0, 0x1E6F4),
    (0x1E6FE, 0x1E6FF),
    (0x2B739, 0x2B73F),
    (0x2CEA2, 0x2CEAD),
    (0x2EBF0, 0x2EE5D),
    (0x31350, 0x33479),
)

# Script=Devanagari/Thai code points whose UCD 17.0.0 category is not L*/N*.
_APP_COMMAND_SCRIPT_RANGES = (
    (0x0900, 0x0903),
    (0x093A, 0x093C),
    (0x093E, 0x094F),
    (0x0955, 0x0957),
    (0x0962, 0x0963),
    (0x0970, 0x0970),
    (0x0E31, 0x0E31),
    (0x0E34, 0x0E3A),
    (0x0E47, 0x0E4F),
    (0x0E5A, 0x0E5B),
    (0xA8E0, 0xA8F1),
    (0xA8F8, 0xA8FA),
    (0xA8FC, 0xA8FC),
    (0xA8FF, 0xA8FF),
    (0x11B00, 0x11B09),
)

# Characters newly visible through the compatibility tables for which UCD
# 17.0.0 defines a lowercase mapping. Older runtimes otherwise treat
# these as uncased and would incorrectly accept uppercase command names.
_APP_COMMAND_LOWERCASE_COMPATIBILITY_RANGES = (
    (0x1C89, 0x1C89),
    (0xA7CB, 0xA7CC),
    (0xA7CE, 0xA7CE),
    (0xA7D2, 0xA7D2),
    (0xA7D4, 0xA7D4),
    (0xA7DA, 0xA7DA),
    (0xA7DC, 0xA7DC),
    (0x10D50, 0x10D65),
    (0x16EA0, 0x16EB8),
)
