"""context-handover core logic.

Separated from __init__.py so it can be unit-tested without touching the
plugin registration machinery.
"""

from __future__ import annotations

import asyncio
import logging
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)

# Maximum characters for task text in presence string.
_PRESENCE_TASK_MAX = 80

# Module-level flag: when this plugin is active (registered), instruct
# turn_context's preflight compression block to skip. Checked via
# agent.compression_enabled being set False before each turn.
_plugin_active = threading.local()


def format_presence(pct: float, task: str) -> str:
    """Return the Discord presence string for *pct* context and *task* text.

    Truncates task to _PRESENCE_TASK_MAX chars to avoid oversized presence.
    """
    task_short = task[:_PRESENCE_TASK_MAX].strip()
    if len(task) > _PRESENCE_TASK_MAX:
        task_short += "…"
    return f"{pct:.0f}% · {task_short}"


def compute_context_pct(agent: Any) -> Optional[float]:
    """Return context usage as a percentage, or None if unavailable."""
    try:
        compressor = agent.context_compressor
        tokens = compressor.last_prompt_tokens
        length = compressor.context_length
        if length <= 0:
            return None
        return tokens / length * 100
    except AttributeError:
        return None


def _extract_task(conversation_history: list[dict], user_message: str) -> str:
    """Best-effort: extract a short task description from conversation context."""
    # Use the most recent user message as a short summary.
    if user_message:
        return user_message[:200].replace("\n", " ").strip()
    # Fallback: scan history for the first user message
    for msg in conversation_history:
        if msg.get("role") == "user":
            content = msg.get("content", "")
            if isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "text":
                        return block.get("text", "")[:200].replace("\n", " ").strip()
            elif isinstance(content, str):
                return content[:200].replace("\n", " ").strip()
    return "unknown task"


def write_handover_doc(
    notes_dir: Path,
    task: str,
    assistant_response: str,
    conversation_history: list[dict],
    pct: float,
    model: str,
) -> Path:
    """Write a handover markdown document and return its path."""
    notes_dir = Path(notes_dir).expanduser()
    notes_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(tz=timezone.utc).strftime("%Y%m%d_%H%M%S")
    doc_path = notes_dir / f"handover-{ts}.md"

    # Count turns from history
    turn_count = sum(1 for m in conversation_history if m.get("role") == "user")

    lines = [
        "# Context Handover",
        "",
        f"**Generated**: {datetime.now(tz=timezone.utc).isoformat()}",
        f"**Trigger**: context at {pct:.1f}% of {model} context window",
        f"**Turns so far**: {turn_count}",
        "",
        "## Current Task",
        "",
        task,
        "",
        "## Last Assistant Response",
        "",
        assistant_response[:2000] + ("…" if len(assistant_response) > 2000 else ""),
        "",
        "## Conversation Summary",
        "",
    ]

    # Pull out the last few turns (up to 6) for the handover doc.
    recent: list[str] = []
    recent_msgs = conversation_history[-12:] if len(conversation_history) > 12 else conversation_history
    for msg in recent_msgs:
        role = msg.get("role", "?")
        content = msg.get("content", "")
        if isinstance(content, list):
            texts = []
            for block in content:
                if isinstance(block, dict) and block.get("type") == "text":
                    texts.append(block.get("text", ""))
            content = " ".join(texts)
        if isinstance(content, str) and content.strip():
            snippet = content[:400].replace("\n", " ").strip()
            if len(content) > 400:
                snippet += "…"
            recent.append(f"**{role}**: {snippet}")

    lines.extend(recent or ["*(no recent conversation)*"])
    lines.extend([
        "",
        "## Next Action",
        "",
        "Continue the task. Read this document for context, then proceed from where the previous session left off.",
        "",
        "---",
        "*This document was auto-generated by the context-handover plugin.*",
    ])

    doc_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("[context-handover] Wrote handover doc: %s", doc_path)
    return doc_path


def update_discord_presence(runner: Any, pct: float, task: str) -> None:
    """Best-effort: set Discord bot presence to reflect context usage + task."""
    try:
        from gateway.config import Platform  # type: ignore
        adapter = runner.adapters.get(Platform.DISCORD)
        if adapter is None:
            return
        client = getattr(adapter, "_client", None)
        if client is None:
            return

        presence_text = format_presence(pct, task)

        async def _set():
            try:
                import discord  # type: ignore
                await client.change_presence(
                    activity=discord.CustomActivity(name=presence_text)
                )
            except Exception as exc:
                logger.debug("[context-handover] Discord presence update failed: %s", exc)

        loop = getattr(client, "loop", None)
        if loop is not None and loop.is_running():
            asyncio.run_coroutine_threadsafe(_set(), loop)
    except Exception as exc:
        logger.debug("[context-handover] update_discord_presence failed: %s", exc)


def trigger_handover(
    *,
    agent: Any,
    runner: Any,
    doc_path: Path,
    session_key: str,
    auto_continue: bool,
) -> None:
    """Reset the session and optionally reseed with a handover prompt."""
    if not auto_continue:
        logger.info("[context-handover] auto_continue=false — wrote doc only")
        return

    session_store = getattr(runner, "session_store", None)
    if session_store is None:
        logger.warning("[context-handover] No session_store on runner — cannot reset")
        return

    # Disable compression on the current agent so it doesn't fire during
    # this final turn processing.
    try:
        agent.compression_enabled = False
    except Exception:
        pass

    new_entry = session_store.reset_session(session_key)
    if new_entry is None:
        logger.warning("[context-handover] reset_session returned None for key=%s", session_key)
        return

    logger.info("[context-handover] Session reset: key=%s new_id=%s", session_key, new_entry.session_id)

    # Inject a reseed message into the adapter's pending message slot so the
    # fresh session receives it on its first iteration.
    seed_text = f"handover: {doc_path}"
    try:
        from gateway.config import Platform  # type: ignore
        from gateway.stream_events import MessageEvent  # type: ignore

        # Determine which platform adapter to inject into.
        platform_str = getattr(agent, "platform", "") or ""
        platform = None
        for p in runner.adapters:
            if p.value == platform_str or str(p) == platform_str:
                platform = p
                break
        if platform is None and runner.adapters:
            platform = next(iter(runner.adapters))

        if platform is not None:
            adapter = runner.adapters.get(platform)
            pending = getattr(adapter, "_pending_messages", None)
            if pending is not None and hasattr(pending, "__setitem__"):
                # Build a minimal event dict — adapters treat _pending_messages
                # as either a raw string or a MessageEvent depending on adapter.
                # Use a string here, which is the lowest-common-denominator.
                pending[session_key] = seed_text
                logger.info("[context-handover] Reseeded session key=%s", session_key)
    except Exception as exc:
        logger.warning("[context-handover] Failed to reseed session: %s", exc)
