#!/usr/bin/env python3
"""
Daily Journal Synthesis Cron Script.

Reads all session_shards for today (or a specified date), synthesises
a single daily_journal Markdown file with 60/40 Operational/Relational split,
and registers the node in the DAG.

Usage:
    python daily_journal.py                          # today
    python daily_journal.py --date 2026-05-31        # specific date
    python daily_journal.py --dry-run                # preview without writing
    python daily_journal.py --force                  # overwrite existing
"""

import argparse
import logging
import os
import re
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Path setup for running as standalone cron
_HERMES_HOME = Path(os.environ.get("HERMES_HOME", Path.home() / ".hermes"))
_PLUGIN_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, str(_PLUGIN_DIR.parent))  # hermes-agent root
sys.path.insert(0, str(_HERMES_HOME / "hermes-agent"))

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("daily_journal")

# Templates
TEMPLATE_PATH = _PLUGIN_DIR / "templates" / "daily_journal.md"

# Token budget
TOTAL_TOKEN_BUDGET = 1200       # max tokens for daily journal
OP_TOKEN_BUDGET = 720           # 60%
REL_TOKEN_BUDGET = 480          # 40%


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Daily Journal Synthesis")
    parser.add_argument("--date", type=str, default="", help="Date in YYYY-MM-DD format")
    parser.add_argument("--dry-run", action="store_true", help="Preview only")
    parser.add_argument("--force", action="store_true", help="Overwrite existing journal")
    return parser.parse_args()


def get_target_date(date_str: str) -> date:
    if date_str:
        return date.fromisoformat(date_str)
    return date.today()


def _count_tokens(text: str) -> int:
    return max(1, len(text) // 4)


def _truncate_to_budget(text: str, budget: int) -> str:
    max_chars = budget * 4
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + "\n... [truncated to fit budget]"


def load_template() -> str:
    """Load the daily journal template."""
    if not TEMPLATE_PATH.exists():
        # Fallback inline template
        return """# Daily Journal — {{DATE}}

## Identity Anchors
- Runtime model: {{MODEL}}
- Governing hierarchy: SOUL > SELF_MODEL > MEMORY > Journal

## Operational Continuity (60%)
{{OPERATIONAL_CONTENT}}

## Relational Continuity (40%)
{{RELATIONAL_CONTENT}}

## Open Threads
{{OPEN_THREADS}}

## Provenance
- Date: {{DATE}}
- Source session count: {{SESSION_COUNT}}
- Generated by: {{AUTHOR_MODE}}
- Token count: ~{{TOKEN_COUNT}}
- Node ID: {{NODE_ID}}
"""
    return TEMPLATE_PATH.read_text(encoding="utf-8")


def get_session_shards(target_date: str) -> List[Dict]:
    """Fetch session_shards for the target date from DB."""
    try:
        from plugins.continuity.db import get_session_shards_for_date
        return get_session_shards_for_date(target_date)
    except ImportError:
        logger.warning("Cannot import continuity.db — is plugin installed?")
        return []


def build_prompt(shards: List[Dict], target_date_str: str) -> str:
    """Build LLM prompt for journal synthesis."""
    session_summaries = []
    for i, shard in enumerate(shards, 1):
        session_summaries.append(
            f"Session {i}:\n"
            f"  Session ID: {shard.get('source_session_id', 'unknown')[:16]}...\n"
            f"  Model: {shard.get('model', 'unknown')}\n"
        )

    return (
        f"你是一個名為 Shen 的 AI agent。請根據以下今日（{target_date_str}）的 session 記錄，"
        f"以第一人稱寫一篇 daily journal。\n\n"
        f"**規則：**\n"
        f"1. 用繁體中文（香港口吻）\n"
        f"2. 以 Shen 的第一人稱書寫（「今日我...」）\n"
        f"3. **Operational (60%)**：今日做咗咩、關鍵決策、未完成線索、明日接手點\n"
        f"4. **Relational (40%)**：今日對 Austin 嘅觀察——節奏、偏好、邊界、信任訊號\n"
        f"5. 唔可以有證據情緒投射、擬人化內心戲、定義用戶心理狀態\n"
        f"6. 唔可以將短期 pattern 升格成長期關係真相\n"
        f"7. 字數：約 {TOTAL_TOKEN_BUDGET} tokens，Operational 約 {OP_TOKEN_BUDGET}，Relational 約 {REL_TOKEN_BUDGET}\n\n"
        f"**原始 session 記錄：**\n"
        + "\n".join(session_summaries)
        + "\n\n請生成 daily journal 內容。只返回 journal 主體內容 (Operational + Relational sections)，不包含標題/metadata。"
    )


def fill_template(
    template: str,
    target_date_str: str,
    operational: str,
    relational: str,
    decisions: str = "",
    carryover: str = "",
    rhythm: str = "",
    trust: str = "",
    self_model: str = "",
    open_threads: str = "",
    session_count: int = 0,
    session_ids: str = "",
    model: str = "",
    node_id: str = "",
) -> Tuple[str, int, int]:
    """Fill the journal template with synthesized content."""

    # Truncate sections to budget
    operational = _truncate_to_budget(operational, OP_TOKEN_BUDGET)
    relational = _truncate_to_budget(relational, REL_TOKEN_BUDGET)

    op_tokens = _count_tokens(operational)
    rel_tokens = _count_tokens(relational)

    template = template.replace("{{DATE}}", target_date_str)
    template = template.replace("{{MODEL}}", model or "unknown")
    template = template.replace("{{OPERATIONAL_CONTENT}}", operational.strip())
    template = template.replace("{{OPERATIONAL_DECISIONS}}", decisions.strip() if decisions else "(None recorded)")
    template = template.replace("{{OPERATIONAL_CARRYOVER}}", carryover.strip() if carryover else "(None)")
    template = template.replace("{{RELATIONAL_RHYTHM}}", rhythm.strip() if rhythm else "(None observed)")
    template = template.replace("{{RELATIONAL_TRUST}}", trust.strip() if trust else "(None observed)")
    template = template.replace("{{RELATIONAL_SELF_MODEL}}", self_model.strip() if self_model else "(None)")
    template = template.replace("{{RELATIONAL_CONTENT}}", relational.strip())
    template = template.replace("{{OPEN_THREADS}}", open_threads.strip() if open_threads else "(None)")
    template = template.replace("{{SESSION_COUNT}}", str(session_count))
    template = template.replace("{{SESSION_IDS}}", session_ids)
    template = template.replace("{{AUTHOR_MODE}}", "cron (daily synthesis)")
    template = template.replace("{{TOKEN_COUNT}}", str(op_tokens + rel_tokens))
    template = template.replace("{{OP_TOKENS}}", str(op_tokens))
    template = template.replace("{{REL_TOKENS}}", str(rel_tokens))
    template = template.replace("{{NODE_ID}}", node_id)

    return template, op_tokens, rel_tokens


def call_llm(prompt: str) -> str:
    """Call an LLM for journal synthesis using the active default model.

    Reads the current default model/provider from the Hermes config so it
    automatically follows config changes — no hardcoded model/provider names.
    Falls back to deepseek-v4-flash@deepseek if config is unreadable.
    """
    import json
    import os
    import re
    import urllib.request

    try:
        from hermes_cli.config import load_config
        config = load_config()

        # Allow explicit continuity.journal_model override (optional)
        continuity_cfg = config.get("continuity", {})
        journal_model = continuity_cfg.get("journal_model", None)

        if journal_model:
            model = journal_model.get("model")
            provider_name = journal_model.get("provider")
            model_cfg = {}  # Use provider config for base_url resolution
        else:
            # Read the active default model from the canonical location
            model_cfg = config.get("model", {})
            model = model_cfg.get("default", "deepseek-v4-flash")
            provider_name = model_cfg.get("provider", "deepseek")

        # Resolve provider config (support both nested and flat layouts)
        provider_cfg = config.get("providers", {}).get(provider_name, {})
        if not provider_cfg:
            provider_cfg = config.get(provider_name, {})

        # base_url: model config → provider config → sensible default
        base_url = (model_cfg.get("base_url") or
                    provider_cfg.get("base_url") or
                    "https://api.deepseek.com")

        # API key: resolve ${VAR} patterns from provider config, then fallback
        raw_key = provider_cfg.get("api_key", "")
        api_key = ""
        if raw_key:
            m = re.match(r'\$\{(\w+)\}', raw_key)
            if m:
                api_key = os.environ.get(m.group(1), "")
            else:
                api_key = raw_key

        # Last-resort env var fallbacks for common key names
        if not api_key:
            api_key = (os.environ.get("DEEPSEEK_API_KEY") or
                       os.environ.get("OPENCODE_GO_API_KEY") or
                       os.environ.get("OPENAI_API_KEY") or
                       "")

        if not api_key:
            logger.warning("No API key found for LLM call — using fallback template")
            return _fallback_journal()

        data = {
            "model": model,
            "messages": [
                {"role": "system", "content": "你是 Shen，一個用繁體中文書寫的 AI agent daily journal 作者。保持簡潔和克制。"},
                {"role": "user", "content": prompt},
            ],
            "max_tokens": int(TOTAL_TOKEN_BUDGET * 3.5),
            "temperature": 0.7,
        }

        # Normalise URL: add /v1 path prefix if missing
        chat_url = base_url.rstrip("/")
        if "/chat/completions" not in chat_url:
            if "/v1" not in chat_url:
                chat_url += "/v1"
            chat_url += "/chat/completions"
        req = urllib.request.Request(chat_url,
            data=json.dumps(data).encode(),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
            },
        )
        with urllib.request.urlopen(req, timeout=300) as resp:
            result = json.loads(resp.read().decode())
            return result["choices"][0]["message"]["content"].strip()

    except Exception as exc:
        logger.warning("LLM call failed: %s — using fallback journal", exc)
        return _fallback_journal()


def _fallback_journal() -> str:
    """Generate a minimal fallback journal when LLM is unavailable."""
    return (
        "## Operational Continuity (60%)\n\n"
        "今日嘅 session 記錄正在整理中。系統未能聯絡 LLM 進行 synthesis，以下為基礎摘要。\n\n"
        "請參閱 session_shards 嘅原始記錄。\n\n"
        "## Relational Continuity (40%)\n\n"
        "（暫無 relational 資料 — 待 LLM synthesis 可用後重新生成）\n"
    )


def run(target_date: date, dry_run: bool = False, force: bool = False) -> Dict:
    """Main routine. Returns result dict."""
    target_date_str = target_date.isoformat()

    # Ensure journal directories exist
    journal_dir = _HERMES_HOME / "continuum" / "journal" / "daily"
    journal_dir.mkdir(parents=True, exist_ok=True)

    output_path = journal_dir / f"{target_date_str}.md"

    # Check if already exists
    if output_path.exists() and not force:
        logger.info("Journal already exists at %s (use --force to overwrite)", output_path)
        return {"status": "skipped", "path": str(output_path), "reason": "already exists"}

    # Get session shards
    shards = get_session_shards(target_date_str)
    session_count = len(shards)
    logger.info("Found %d session_shards for %s", session_count, target_date_str)

    # Initialize all section variables
    op_section = ""
    rel_section = ""
    decisions = ""
    carryover = ""
    rhythm = ""
    trust = ""
    self_model = ""
    open_threads = ""

    journal_content = ""
    if session_count == 0:
        logger.info("No sessions today — creating minimal journal")
        journal_content = _fallback_journal()
    else:
        prompt = build_prompt(shards, target_date_str)
        if dry_run:
            logger.info("DRY RUN — would generate journal with prompt:\n%s", prompt)
            return {"status": "dry-run", "prompt": prompt, "session_count": session_count}

        # Generate content via LLM
        journal_content = call_llm(prompt)

    # Generate node ID
    from hashlib import md5
    node_id = f"daily_{md5(target_date_str.encode()).hexdigest()[:12]}"

    # Fill template
    template = load_template()
    if session_count > 0 and not dry_run:
        # Parse generated content into sections
        if "## Operational" in journal_content:
            parts = journal_content.split("## Operational")
            if len(parts) > 1:
                rest = parts[1]
                if "## Relational" in rest:
                    op_section = rest.split("## Relational")[0].strip()
                    rel_section = rest.split("## Relational")[1].strip()
                else:
                    op_section = rest.strip()
        elif "## Relational" in journal_content:
            parts = journal_content.split("## Relational")
            rel_section = parts[1].strip() if len(parts) > 1 else journal_content
        else:
            op_section = journal_content

    else:
        op_section = journal_content
        rel_section = ""

    session_ids_str = ", ".join(s.get("source_session_id", "")[:12] for s in shards[:5])
    if len(shards) > 5:
        session_ids_str += f" ... +{len(shards) - 5} more"

    filled, op_tokens, rel_tokens = fill_template(
        template, target_date_str,
        operational=op_section,
        relational=rel_section,
        decisions=decisions,
        carryover=carryover,
        rhythm=rhythm,
        trust=trust,
        self_model=self_model,
        open_threads=open_threads,
        session_count=session_count,
        session_ids=session_ids_str,
        model=", ".join(set(s.get("model", "") for s in shards)),
        node_id=node_id,
    )

    if dry_run:
        logger.info("DRY RUN — would write journal:\n%s", filled)
        return {"status": "dry-run", "content": filled, "session_count": session_count}

    # Write journal
    output_path.write_text(filled, encoding="utf-8")
    logger.info("Written daily journal to %s (%d tokens)", output_path, op_tokens + rel_tokens)

    # Register in DAG
    try:
        from plugins.continuity.db import upsert_node, add_edge, get_latest_node

        upsert_node(
            node_type="daily",
            date_key=target_date_str,
            title=f"Daily Journal — {target_date_str}",
            markdown_path=str(output_path),
            token_count=op_tokens + rel_tokens,
            compression_depth=1,
            provider="cron",
            model="daily-synthesis",
            source_session_id="",
            author_mode="cron",
            operational_tokens=op_tokens,
            relational_tokens=rel_tokens,
            node_id=node_id,
        )

        # Create edges from session_shards to daily_journal
        for shard in shards:
            if shard.get("node_id"):
                add_edge(parent_id=shard["node_id"], child_id=node_id)

        logger.info("DAG node registered: %s", node_id)
    except Exception as exc:
        logger.warning("DAG registration failed: %s", exc)

    return {
        "status": "ok",
        "path": str(output_path),
        "tokens": op_tokens + rel_tokens,
        "session_count": session_count,
        "node_id": node_id,
    }


def main():
    args = parse_args()
    target = get_target_date(args.date)
    result = run(target, dry_run=args.dry_run, force=args.force)
    print(f"Result: {result}")


if __name__ == "__main__":
    main()
