#!/usr/bin/env python3
"""Generate Discord CHAT_INPUT Unicode compatibility tables and test oracle.

The policy combines the oldest supported Python Unicode database with pinned
compatibility deltas. Inputs must be official, versioned UCD files; no network
access or third-party package is used by this generator.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Iterable

Range = tuple[int, int]


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _compress_ranges(codepoints: Iterable[int]) -> tuple[Range, ...]:
    ranges: list[Range] = []
    for codepoint in sorted(set(codepoints)):
        if ranges and codepoint == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], codepoint)
        else:
            ranges.append((codepoint, codepoint))
    return tuple(ranges)


def _parse_unicode_data(
    path: Path,
) -> tuple[dict[int, str], dict[int, tuple[int, ...]]]:
    categories: dict[int, str] = {}
    lowercase: dict[int, tuple[int, ...]] = {}
    range_start: tuple[int, str] | None = None

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        if not raw_line:
            continue
        fields = raw_line.split(";")
        codepoint = int(fields[0], 16)
        name = fields[1]
        category = fields[2]

        if name.endswith(", First>"):
            if range_start is not None:
                raise ValueError(f"nested UnicodeData range at U+{codepoint:04X}")
            range_start = (codepoint, category)
            continue
        if name.endswith(", Last>"):
            if range_start is None or range_start[1] != category:
                raise ValueError(
                    f"unmatched UnicodeData range end at U+{codepoint:04X}"
                )
            start, _ = range_start
            categories.update(
                (value, category) for value in range(start, codepoint + 1)
            )
            range_start = None
            continue

        categories[codepoint] = category
        if fields[13]:
            lowercase[codepoint] = tuple(int(value, 16) for value in fields[13].split())

    if range_start is not None:
        raise ValueError("unterminated UnicodeData range")
    return categories, lowercase


def _parse_scripts(path: Path, selected: set[str]) -> set[int]:
    codepoints: set[int] = set()
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        field, script = (part.strip() for part in line.split(";"))
        if script not in selected:
            continue
        if ".." in field:
            start_text, end_text = field.split("..")
            start, end = int(start_text, 16), int(end_text, 16)
        else:
            start = end = int(field, 16)
        codepoints.update(range(start, end + 1))
    return codepoints


def _parse_unconditional_special_lowercase(path: Path) -> dict[int, tuple[int, ...]]:
    lowercase: dict[int, tuple[int, ...]] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [part.strip() for part in line.split(";")]
        if len(fields) < 5 or fields[4]:
            continue
        codepoint = int(fields[0], 16)
        mapping = tuple(int(value, 16) for value in fields[1].split())
        if mapping != (codepoint,):
            lowercase[codepoint] = mapping
    return lowercase


def _format_ranges(name: str, ranges: tuple[Range, ...]) -> str:
    lines = [f"{name} = ("]
    lines.extend(f"    (0x{start:04X}, 0x{end:04X})," for start, end in ranges)
    lines.append(")")
    return "\n".join(lines)


def _format_string_mapping(name: str, values: dict[str, str]) -> str:
    lines = [f"{name} = {{"]
    lines.extend(f'    "{key}": "{value}",' for key, value in values.items())
    lines.append("}")
    return "\n".join(lines)


def _render_policy(
    *,
    baseline_version: str,
    unicode_version: str,
    hashes: dict[str, str],
    ln_ranges: tuple[Range, ...],
    script_ranges: tuple[Range, ...],
    lowercase_ranges: tuple[Range, ...],
) -> str:
    source = f'''"""Generated Unicode policy data for Discord CHAT_INPUT command names.

Generated by ``scripts/generate_discord_command_unicode.py`` from official UCD
{unicode_version} data, relative to Python 3.11's UCD {baseline_version} floor.
Do not edit by hand. Ranges are sorted, disjoint, inclusive, and adjacency-
compressed.

Sources and SHA-256:
- https://www.unicode.org/Public/{baseline_version}/ucd/UnicodeData.txt
  {hashes["baseline_unicode_data"]}
- https://www.unicode.org/Public/{unicode_version}/ucd/UnicodeData.txt
  {hashes["unicode_data"]}
- https://www.unicode.org/Public/{unicode_version}/ucd/Scripts.txt
  {hashes["scripts"]}
- https://www.unicode.org/Public/{unicode_version}/ucd/SpecialCasing.txt
  {hashes["special_casing"]}
"""

_APP_COMMAND_UNICODE_BASELINE_VERSION = "{baseline_version}"
_APP_COMMAND_UNICODE_VERSION = "{unicode_version}"
{_format_string_mapping("_APP_COMMAND_UNICODE_SOURCE_SHA256", hashes)}

# General_Category L*/N* code points present in UCD {unicode_version} but absent
# from the UCD {baseline_version} runtime floor.
{_format_ranges("_APP_COMMAND_LN_COMPATIBILITY_RANGES", ln_ranges)}

# Script=Devanagari/Thai code points whose UCD {unicode_version} category is not L*/N*.
{_format_ranges("_APP_COMMAND_SCRIPT_RANGES", script_ranges)}

# Characters newly visible through the compatibility tables for which UCD
# {unicode_version} defines a lowercase mapping. Older runtimes otherwise treat
# these as uncased and would incorrectly accept uppercase command names.
{_format_ranges("_APP_COMMAND_LOWERCASE_COMPATIBILITY_RANGES", lowercase_ranges)}
'''
    return source


def _render_oracle(
    *,
    baseline_version: str,
    unicode_version: str,
    hashes: dict[str, str],
    property_points: set[int],
    lowercase_disallowed: set[int],
) -> str:
    payload = {
        "schema": 1,
        "baseline_unicode_version": baseline_version,
        "unicode_version": unicode_version,
        "source_urls": {
            "baseline_unicode_data": (
                f"https://www.unicode.org/Public/{baseline_version}/ucd/UnicodeData.txt"
            ),
            "unicode_data": (
                f"https://www.unicode.org/Public/{unicode_version}/ucd/UnicodeData.txt"
            ),
            "scripts": f"https://www.unicode.org/Public/{unicode_version}/ucd/Scripts.txt",
            "special_casing": (
                f"https://www.unicode.org/Public/{unicode_version}/ucd/SpecialCasing.txt"
            ),
        },
        "source_sha256": hashes,
        "property_ranges": _compress_ranges(property_points),
        "lowercase_disallowed_ranges": _compress_ranges(lowercase_disallowed),
    }
    rendered = json.dumps(payload, indent=2)
    rendered = re.sub(
        r"\[\n\s+(\d+),\n\s+(\d+)\n\s+\]",
        r"[\1, \2]",
        rendered,
    )
    return rendered + "\n"


def _write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"generated output differs: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--baseline-unicode-data", type=Path, required=True)
    parser.add_argument("--unicode-data", type=Path, required=True)
    parser.add_argument("--scripts", type=Path, required=True)
    parser.add_argument("--special-casing", type=Path, required=True)
    parser.add_argument("--baseline-version", default="14.0.0")
    parser.add_argument("--unicode-version", default="17.0.0")
    parser.add_argument("--policy-output", type=Path, required=True)
    parser.add_argument("--oracle-output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    baseline_categories, _ = _parse_unicode_data(args.baseline_unicode_data)
    target_categories, target_lowercase = _parse_unicode_data(args.unicode_data)
    target_lowercase.update(_parse_unconditional_special_lowercase(args.special_casing))
    selected_scripts = _parse_scripts(args.scripts, {"Devanagari", "Thai"})

    baseline_ln = {
        codepoint
        for codepoint, category in baseline_categories.items()
        if category[0] in {"L", "N"}
    }
    target_ln = {
        codepoint
        for codepoint, category in target_categories.items()
        if category[0] in {"L", "N"}
    }
    script_exceptions = {
        codepoint
        for codepoint in selected_scripts
        if target_categories.get(codepoint, "Cn")[0] not in {"L", "N"}
    }
    property_points = target_ln.union(script_exceptions)
    ln_compatibility = target_ln.difference(baseline_ln)
    newly_visible = property_points.difference(baseline_ln)
    lowercase_compatibility = newly_visible.intersection(target_lowercase)
    lowercase_disallowed = property_points.intersection(target_lowercase)

    if baseline_ln.difference(target_ln):
        raise SystemExit(
            "target UCD removed baseline L/N code points; delta policy is not safe"
        )

    hashes = {
        "baseline_unicode_data": _sha256(args.baseline_unicode_data),
        "unicode_data": _sha256(args.unicode_data),
        "scripts": _sha256(args.scripts),
        "special_casing": _sha256(args.special_casing),
    }
    ln_ranges = _compress_ranges(ln_compatibility)
    script_ranges = _compress_ranges(script_exceptions)
    lowercase_ranges = _compress_ranges(lowercase_compatibility)
    policy = _render_policy(
        baseline_version=args.baseline_version,
        unicode_version=args.unicode_version,
        hashes=hashes,
        ln_ranges=ln_ranges,
        script_ranges=script_ranges,
        lowercase_ranges=lowercase_ranges,
    )
    oracle = _render_oracle(
        baseline_version=args.baseline_version,
        unicode_version=args.unicode_version,
        hashes=hashes,
        property_points=property_points,
        lowercase_disallowed=lowercase_disallowed,
    )
    _write_or_check(args.policy_output, policy, args.check)
    _write_or_check(args.oracle_output, oracle, args.check)
    print(
        json.dumps(
            {
                "unicode_version": args.unicode_version,
                "property_codepoints": len(property_points),
                "property_ranges": len(_compress_ranges(property_points)),
                "ln_compatibility_codepoints": len(ln_compatibility),
                "ln_compatibility_ranges": len(ln_ranges),
                "script_exception_codepoints": len(script_exceptions),
                "script_exception_ranges": len(script_ranges),
                "lowercase_compatibility_codepoints": len(lowercase_compatibility),
                "lowercase_compatibility_ranges": len(lowercase_ranges),
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
