# make-drive-root-shortcut - (re)generates "<drive root>\Start North Forge.lnk", a
# double-click launcher that sits beside the checkout folder at the root of whatever
# drive the checkout currently lives on, with its icon set to the repo's brand .ico
# and its target pointing at the checkout's real entry point (north-forge.cmd).
<#
  scripts\make-drive-root-shortcut.ps1  [-RepoRoot <path>]  [-LinkDir <path>]
                                        [-LinkName <name.lnk>]  [-Quiet]

  WHY THIS EXISTS  (self-healing, same principle as the venv drive-letter fix)
    A .lnk stores an ABSOLUTE target + working dir + icon path. If Windows hands the
    drive a different letter next boot (E: -> F:, etc.), a shortcut written last time
    now points at a dead path. north-forge.cmd calls this script on EVERY launch, so
    the drive-root shortcut is rewritten from scratch each run against the path the
    checkout is actually at right now - it is always correct for the current letter,
    never a stale pointer.

    The generated .lnk is NOT tracked in git (it is created outside the checkout, at
    the drive root) - it is a build artifact of running north-forge.cmd.

  WHAT IT WRITES
    <LinkDir>\<LinkName>   default:  <root of RepoRoot's drive>\Start North Forge.lnk
      TargetPath        = <RepoRoot>\north-forge.cmd
      WorkingDirectory  = <RepoRoot>
      IconLocation      = <RepoRoot>\assets\icons\north-forge.ico,0   (if that file exists)
      Description        = self-identifying, notes it is auto-regenerated

  PARAMS
    -RepoRoot   the checkout root. Default: the parent of this script's folder.
    -LinkDir    where to write the .lnk. Default: the drive root of -RepoRoot
                (e.g. RepoRoot D:\north-forge-agent -> D:\). Override for tests /
                to simulate a drive-letter change.
    -LinkName   the .lnk filename. Default: "Start North Forge.lnk".
    -Quiet      suppress the normal one-line status print (errors still print).

  EXIT  0 = shortcut written (or refreshed).  1 = could not (missing north-forge.cmd,
        COM failure). north-forge.cmd calls this best-effort and ignores the exit code
        so a failure here never blocks the agent from starting.
#>
[CmdletBinding()]
param(
    [string]$RepoRoot,
    [string]$LinkDir,
    [string]$LinkName = "Start North Forge.lnk",
    [switch]$Quiet
)

$ErrorActionPreference = 'Stop'

function Write-Status([string]$msg) { if (-not $Quiet) { Write-Host "[drive-root-shortcut] $msg" } }

try {
    if (-not $RepoRoot) { $RepoRoot = Split-Path -Parent $PSScriptRoot }
    $RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path.TrimEnd('\')

    $target = Join-Path $RepoRoot 'north-forge.cmd'
    if (-not (Test-Path -LiteralPath $target)) {
        Write-Error "no 'north-forge.cmd' at '$RepoRoot' - is -RepoRoot correct?"
        exit 1
    }

    if (-not $LinkDir) { $LinkDir = [System.IO.Path]::GetPathRoot($RepoRoot) }
    if (-not $LinkDir) {
        Write-Error "could not determine a drive root for '$RepoRoot'; pass -LinkDir."
        exit 1
    }
    if (-not (Test-Path -LiteralPath $LinkDir)) {
        New-Item -ItemType Directory -Path $LinkDir -Force | Out-Null
    }

    $icon = Join-Path $RepoRoot 'assets\icons\north-forge.ico'
    $haveIcon = Test-Path -LiteralPath $icon

    $linkPath = Join-Path $LinkDir $LinkName

    # Rewrite from scratch every run: drop any prior copy first so a partial/locked
    # file can't leave stale metadata behind.
    if (Test-Path -LiteralPath $linkPath) {
        Remove-Item -LiteralPath $linkPath -Force -ErrorAction SilentlyContinue
    }

    $shell = New-Object -ComObject WScript.Shell
    try {
        $sc = $shell.CreateShortcut($linkPath)
        $sc.TargetPath        = $target
        $sc.WorkingDirectory  = $RepoRoot
        $sc.WindowStyle       = 1
        $sc.Description        = "Launch North Forge (drive-native). Auto-regenerated by north-forge.cmd on every run - safe to delete."
        if ($haveIcon) { $sc.IconLocation = "$icon,0" }
        $sc.Save()
    }
    finally {
        [void][System.Runtime.InteropServices.Marshal]::ReleaseComObject($shell)
    }

    if (-not (Test-Path -LiteralPath $linkPath)) {
        Write-Error "shortcut save reported success but '$linkPath' is not there."
        exit 1
    }

    $iconNote = if ($haveIcon) { "north-forge.ico" } else { "(no .ico found - default icon)" }
    Write-Status "wrote '$linkPath'  ->  '$target'   icon: $iconNote"
    exit 0
}
catch {
    Write-Error "failed to write drive-root shortcut: $($_.Exception.Message)"
    exit 1
}
