# Auto-generated by hermes scrapling-feeds cron install-mhlw.
import json
import os
import subprocess
import sys

PAYLOAD = {
  "python": "C:\\Users\\downl\\Documents\\New project\\hermes-agent\\.venv\\Scripts\\python.exe",
  "repo_root": "C:\\Users\\downl\\Documents\\New project\\hermes-agent",
  "extra_args": [
    "--record-baseline"
  ]
}

env = os.environ.copy()
env.setdefault("PYTHONIOENCODING", "utf-8")

args = ["scrapling-feeds", "mhlw-check", "--cron-stdout", *PAYLOAD.get("extra_args", [])]
result = subprocess.run(
    [PAYLOAD["python"], "-m", "hermes_cli.main", *args],
    cwd=PAYLOAD["repo_root"],
    env=env,
    capture_output=True,
    text=True,
    encoding="utf-8",
    errors="replace",
    timeout=300,
)
stdout = (result.stdout or "").strip()
stderr = (result.stderr or "").strip()
if result.returncode != 0:
    if stderr:
        print(stderr)
    if stdout:
        print(stdout)
    sys.exit(result.returncode)
if stdout:
    print(stdout)
