"""In-turn compaction-stats whole-tail-replay kept-tail fix (2026-06-26).

Guards the fix for the silent two-line degrade of the in-turn granular announce:
``build_inturn_stats`` measured ``folded`` pre-side but ``kept`` comp-side, so
``validate()``'s PRE identity failed once LCM sanitized the kept tail. The fix
finds the kept-tail boundary by replaying the REAL LCM sanitizer over candidate
``messages[cut:]`` slices (tail-global drop/stub reproduced correctly), then
measures ``folded`` AND ``kept_pre`` both pre-side.

The fixture (``inturn_reconcile_sanitized_shape.json``) is generated by
``gen_inturn_reconcile_fixture.py`` from the real sanitizer; ``true_kept_count``
is an independent integer so the oracle is non-circular.
"""
from __future__ import annotations

import json
import os

import pytest

from agent.compaction_stats import (
    build_inturn_stats,
    find_inturn_kept_cut,
    _inturn_norm,
)
from agent.model_metadata import estimate_messages_tokens_rough as _est

_FIX = os.path.join(os.path.dirname(__file__), "fixtures", "inturn_reconcile_sanitized_shape.json")


def _load_fixture():
    with open(_FIX, encoding="utf-8") as fh:
        return json.load(fh)


def _sanitizer():
    from plugins.context_engine.lcm.engine import LCMEngine
    eng = LCMEngine.__new__(LCMEngine)
    return lambda ms: eng._sanitize_active_context_messages(list(ms))


def _comp_kept(comp):
    # comp-side kept tail = non-system, non-summary rows
    return [m for m in comp if m.get("role") != "system" and not m.get("_lcm_summary")]


# ───────────────────────── core RED→GREEN ─────────────────────────

def test_inturn_replay_finds_true_cut():
    """kept_pre_messages == the generator's recorded TRUE count (not 0, not derived)."""
    fx = _load_fixture()
    san = _sanitizer()
    stats = build_inturn_stats(
        messages=fx["messages"], compressed=fx["compressed"], estimator=_est,
        engine_is_lcm=True, sanitize=san, fresh_tail_count=fx["fresh_tail_count"],
    )
    ok, why = stats.validate()
    assert ok, why
    assert stats.kept_pre_messages == fx["true_kept_count"]
    assert stats.kept_pre_messages != 0


def test_inturn_reconciles_sanitized_stubbed_tail():
    """PRE identity reconciles (msg exact, tokens within tolerance) on the real-sanitizer fixture."""
    fx = _load_fixture()
    san = _sanitizer()
    stats = build_inturn_stats(
        messages=fx["messages"], compressed=fx["compressed"], estimator=_est,
        engine_is_lcm=True, sanitize=san, fresh_tail_count=fx["fresh_tail_count"],
    )
    # message axis exact
    assert stats.cleared_count + stats.folded_count + stats._kept_pre_messages == stats.pre_messages
    # token axis within tolerance
    ok, why = stats.validate()
    assert ok, why


def test_inturn_old_mixed_side_now_reconciles_via_a_floor():
    """Without the sanitizer (the fallback path), the A-floor single-walk partition
    now RECONCILES this real fixture shape (the old mixed-side bug is fixed) and
    flags ``approx_attribution`` so the caller labels + watches it. The aligned
    path (with sanitizer) remains the EXACT, non-approx path (see tests below)."""
    fx = _load_fixture()
    stats = build_inturn_stats(
        messages=fx["messages"], compressed=fx["compressed"], estimator=_est,
        engine_is_lcm=True,  # no sanitize / fresh_tail → A-floor fallback
    )
    ok, why = stats.validate()
    assert ok, why                         # A-floor reconciles by construction
    assert stats.approx_attribution is True
    # exhaustive pre-side partition
    assert stats.folded_count + stats._kept_pre_messages == stats.pre_messages


# ───────────────────────── uniqueness / determinism (pass-4 RC#1/#2) ──────────

def test_inturn_replay_rejects_neighbor_cuts():
    """accept-on-exact-match is only a gate if neighbor cuts diverge."""
    fx = _load_fixture()
    san = _sanitizer()
    msgs = fx["messages"]
    comp_kept = _comp_kept(fx["compressed"])
    cut = find_inturn_kept_cut(msgs, comp_kept, san, fx["fresh_tail_count"])
    assert cut == len(msgs) - fx["true_kept_count"]
    target = _inturn_norm(comp_kept)
    assert _inturn_norm(san(msgs[cut - 1:])) != target
    assert _inturn_norm(san(msgs[cut + 1:])) != target


def test_inturn_replay_byte_equals_comp_kept():
    """The replay at the found cut reproduces comp_kept exactly, INCLUDING the stub row."""
    fx = _load_fixture()
    san = _sanitizer()
    msgs = fx["messages"]
    comp_kept = _comp_kept(fx["compressed"])
    cut = find_inturn_kept_cut(msgs, comp_kept, san, fx["fresh_tail_count"])
    replayed = san(msgs[cut:])
    assert _inturn_norm(replayed) == _inturn_norm(comp_kept)
    # the stub row is present in the matched tail
    assert any(m.get("role") == "tool" and "earlier conversation" in str(m.get("content", ""))
               for m in replayed)


# ───────────────────────── drop+stub & budget-trim PASSING alignment (RC#2/#3) ──

def test_inturn_alignment_drop_and_stub():
    """A tail with BOTH a dropped raw row AND a stub aligns to the TRUE cut and PASSES
    (not the fail-safe path)."""
    fx = _load_fixture()  # the fixture already contains an interior drop + stub
    san = _sanitizer()
    stats = build_inturn_stats(
        messages=fx["messages"], compressed=fx["compressed"], estimator=_est,
        engine_is_lcm=True, sanitize=san, fresh_tail_count=fx["fresh_tail_count"],
    )
    ok, why = stats.validate()
    assert ok, why
    # kept_pre is the TRUE raw tail, not a degraded fallback
    assert stats.kept_pre_messages == fx["true_kept_count"]


def test_inturn_budget_trimmed_tail_aligns():
    """The §0.5 budget-trimmed (shorter) kept tail finds its interior cut and PASSES."""
    san = _sanitizer()

    def usr(i):
        return {"role": "user", "content": f"user {i} {'w' * 30}"}

    def at(i):
        return {"role": "assistant", "content": f"<thinking>t{i}</thinking>Visible {i}."}

    pre = [usr(i) if i % 2 else at(i) for i in range(200)]
    # the engine emitted only the last 20 rows (budget shortened it below fresh_tail=32)
    kept_raw = pre[-20:]
    comp = [{"role": "system", "content": "anchor"},
            {"role": "assistant",
             "content": "[Recent Summary (d0, node 1)] folded [Expand for details: x]",
             "_lcm_summary": True}] + san(kept_raw)
    stats = build_inturn_stats(
        messages=pre, compressed=comp, estimator=_est,
        engine_is_lcm=True, sanitize=san, fresh_tail_count=32,
    )
    ok, why = stats.validate()
    assert ok, why
    assert stats.kept_pre_messages == 20  # the true interior cut, not 32


# ───────────────────────── post_messages teeth (D-8) ─────────────────────────

def test_inturn_post_messages_measured_not_derived():
    """post_messages == len(comp); corrupting a partition count (comp held fixed) fails validate."""
    fx = _load_fixture()
    san = _sanitizer()
    stats = build_inturn_stats(
        messages=fx["messages"], compressed=fx["compressed"], estimator=_est,
        engine_is_lcm=True, sanitize=san, fresh_tail_count=fx["fresh_tail_count"],
    )
    assert stats.post_messages == len(fx["compressed"])
    # mutate ONLY a partition count (comp untouched) → POST identity must trip
    stats.kept_messages += 1
    ok, _ = stats.validate()
    assert ok is False


# ───────────────────────── fail-safe degrade ─────────────────────────

def test_inturn_alignment_unreproducible_uses_a_floor():
    """An unrecognizable comp shape (no cut reproduces comp_kept) no longer degrades
    to two-line — the A-floor reconciles the TOTALS via the exhaustive single-walk
    partition and flags ``approx_attribution`` (the split is approximate, the totals
    exact). The caller decides render-vs-degrade by the gross-error bound."""
    san = _sanitizer()
    pre = [{"role": "user", "content": f"u{i}"} for i in range(100)]
    # comp_kept rows that no slice of `pre` can reproduce (alien content)
    comp = [{"role": "system", "content": "anchor"},
            {"role": "assistant",
             "content": "[Recent Summary (d0, node 1)] x [Expand for details: y]",
             "_lcm_summary": True},
            {"role": "assistant", "content": "THIS CONTENT EXISTS IN NO PRE ROW zzz"}]
    stats = build_inturn_stats(
        messages=pre, compressed=comp, estimator=_est,
        engine_is_lcm=True, sanitize=san, fresh_tail_count=32,
    )
    ok, why = stats.validate()
    assert ok, why                          # A-floor reconciles totals
    assert stats.approx_attribution is True
    assert stats.folded_count + stats._kept_pre_messages == stats.pre_messages


# ───────────────────────── back-compat (INV-3) ─────────────────────────

def test_inturn_no_sanitize_built_in_back_compat():
    """Built-in / legacy caller (no sanitize, non-sanitizing comp) still reconciles via
    the A-floor exhaustive partition. Because the built-in tail is verbatim (no
    sanitize mutation), the partition matches the comp-kept rows exactly → kept_pre
    equals the comp-side kept and the split is correct (approx_attribution flagged,
    but the verbatim tail means the split is in fact exact)."""
    pre = [{"role": "user", "content": f"u{i}"} for i in range(50)]
    # built-in style: comp = summary + verbatim last-5 tail (no sanitize mutation)
    tail = pre[-5:]
    comp = [{"role": "assistant",
             "content": "[Recent Summary (d0, node 1)] x [Expand for details: y]",
             "_lcm_summary": True}] + [dict(m) for m in tail]
    stats = build_inturn_stats(messages=pre, compressed=comp, estimator=_est, engine_is_lcm=True)
    ok, why = stats.validate()
    assert ok, why
    # A-floor sets kept_pre explicitly (exhaustive partition); verbatim tail → matches comp-side
    assert stats._kept_pre_messages == stats.kept_messages
    assert stats.folded_count + stats._kept_pre_messages == stats.pre_messages


# ───────────────────────── fixture provenance (D-6) ─────────────────────────

def test_inturn_norm_distinguishes_tool_calls():
    """Two assistant rows with identical sanitized content but DIFFERENT tool_calls
    must NOT compare equal in the alignment norm — else a wrong cut can match and
    produce a reconciled-but-wrong folded/kept split (Greptile P1, PR #106)."""
    from agent.compaction_stats import _inturn_norm_row
    a = {"role": "assistant", "content": "Done.",
         "tool_calls": [{"id": "call_1", "function": {"name": "terminal", "arguments": "{}"}}]}
    b = {"role": "assistant", "content": "Done.",
         "tool_calls": [{"id": "call_2", "function": {"name": "browser", "arguments": "{}"}}]}
    assert _inturn_norm_row(a) != _inturn_norm_row(b)
    # identical rows still compare equal (idempotent)
    assert _inturn_norm_row(a) == _inturn_norm_row(dict(a))


def test_fixture_sanitizer_provenance_current():
    """The committed fixture was generated against the CURRENT live sanitizer source.
    Fails (prompting a regenerate) if the sanitizer behavior-relevant source diverges."""
    import sys
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "fixtures"))
    import gen_inturn_reconcile_fixture as gen
    fx = _load_fixture()
    assert fx["sanitizer_source_sha1"] == gen._sanitizer_source_sha1(), (
        "live LCM sanitizer source changed — regenerate "
        "tests/agent/fixtures/inturn_reconcile_sanitized_shape.json"
    )
