"""Market artifact generation and candidate-pool reflection."""

from __future__ import annotations

import math
from statistics import median
from typing import Any

from .schemas import Candidate, CandidatePool, CandidatePoolReflection, EventData, FundamentalData, InvestmentPolicy, SecData
from .storage import utc_now


def build_market_artifacts(
    policy: InvestmentPolicy,
    candidate_pool: CandidatePool,
    macro_context: dict[str, Any] | None = None,
    sec_context: dict[str, Any] | None = None,
) -> dict[str, dict[str, Any]]:
    """Build structured evidence artifacts from the candidate pool.

    The V1 workflow deliberately derives these artifacts from market data and
    candidate metadata only. Current holdings are not available at this layer.
    """
    generated_at = utc_now()
    candidates = candidate_pool.candidates
    macro_context = macro_context or {}
    sec_context = sec_context or {}
    return {
        "research_trace": _research_trace(candidate_pool, generated_at),
        "market_context": _market_context(policy, candidate_pool, generated_at),
        "theme_exposure_map": _theme_exposure_map(candidate_pool, generated_at),
        "plate_constituents": _plate_constituents(candidate_pool, generated_at),
        "market_snapshot": _market_snapshot(candidates, generated_at),
        "technical_summary": _technical_summary(candidates, generated_at),
        "liquidity_context": _liquidity_context(candidates, generated_at),
        "options_surface": _options_surface(candidates, policy, generated_at),
        "sec_filings_context": _sec_filings_context(candidates, sec_context, generated_at),
        "fundamental_quality": _fundamental_quality(candidates, generated_at, sec_context),
        "valuation_context": _valuation_context(candidates, generated_at),
        "earnings_event_calendar": _earnings_event_calendar(candidates, generated_at, sec_context),
        "correlation_and_diversification": _correlation_and_diversification(candidates, generated_at),
        "benchmark_context": _benchmark_context(candidate_pool, macro_context, generated_at),
        "market_regime": _market_regime(macro_context, generated_at),
        "positioning_and_sentiment": _positioning_and_sentiment(candidates, generated_at),
        "analyst_revision_context": _analyst_revision_context(candidates, generated_at),
        "risk_scenario": _risk_scenario(candidate_pool, macro_context, generated_at),
        "risk_flags": _risk_flags(candidates, generated_at, sec_context),
    }


def _research_trace(candidate_pool: CandidatePool, generated_at: str) -> dict[str, Any]:
    return {
        "artifact_type": "research_trace",
        "generated_at": generated_at,
        "theme": candidate_pool.theme,
        "discovery_thesis": candidate_pool.discovery_thesis,
        "search_queries": list(candidate_pool.search_queries),
        "data_asof": dict(candidate_pool.data_asof),
        "sources": [
            source.model_dump(mode="json")
            for source in candidate_pool.research_trace
        ],
        "candidate_source_ids": {
            candidate.symbol: list(candidate.discovery_data.source_ids)
            for candidate in candidate_pool.candidates
        },
        "warnings": [
            "Research trace is generated by the discovery agent and still requires downstream market/fundamental validation."
        ],
    }


def enrich_candidate_pool_with_sec_data(
    candidate_pool: CandidatePool,
    sec_context: dict[str, Any],
) -> CandidatePool:
    """Return a candidate pool with candidate-level SEC/fundamental/event summaries."""

    sec_status = _sec_status(sec_context)
    sec_source = _sec_source(sec_context)
    enriched: list[Candidate] = []
    for candidate in candidate_pool.candidates:
        sec_item = _sec_item(sec_context, candidate.symbol)
        filings = sec_item.get("filings", {}) if isinstance(sec_item, dict) else {}
        sec_data = SecData(
            source=sec_source,
            source_status=sec_item.get("source_status", sec_status),
            ticker=sec_item.get("ticker"),
            cik=sec_item.get("cik"),
            company_name=sec_item.get("company_name"),
            industry=sec_item.get("industry"),
            fiscal_year_end=sec_item.get("fiscal_year_end"),
            filer_category=sec_item.get("filer_category"),
            latest_10k=filings.get("latest_10k"),
            latest_10q=filings.get("latest_10q"),
            latest_8k=filings.get("latest_8k"),
            event_context=sec_item.get("event_context", {}),
            risk_flags=sec_item.get("risk_flags", []),
            error=sec_item.get("error"),
        )
        fundamental_item = _fundamental_quality_item(candidate, sec_item)
        fundamental_data = FundamentalData(
            source_status=fundamental_item.get("data_status", "not_available"),
            sec_source_status=sec_status,
            numeric_source=fundamental_item.get("numeric_source", "not_available"),
            numeric_llm_generated=bool(fundamental_item.get("numeric_llm_generated", False)),
            net_profit=fundamental_item.get("net_profit"),
            eps=fundamental_item.get("eps"),
            net_asset_per_share=fundamental_item.get("net_asset_per_share"),
            dividend_yield_ttm=fundamental_item.get("dividend_yield_ttm"),
            ttm_revenue=fundamental_item.get("ttm_revenue"),
            ttm_net_income=fundamental_item.get("ttm_net_income"),
            gross_profit=fundamental_item.get("gross_profit"),
            operating_income=fundamental_item.get("operating_income"),
            total_assets=fundamental_item.get("total_assets"),
            total_liabilities=fundamental_item.get("total_liabilities"),
            shareholders_equity=fundamental_item.get("shareholders_equity"),
            debt_to_assets=fundamental_item.get("debt_to_assets"),
            roe=fundamental_item.get("roe"),
            net_margin=fundamental_item.get("net_margin"),
            quality_score=fundamental_item.get("quality_score"),
        )
        event_item = _earnings_event_item(candidate, sec_item)
        event_data = EventData(
            source_status=event_item.get("source_status", "not_available"),
            next_earnings_date=event_item.get("next_earnings_date"),
            days_to_earnings=event_item.get("days_to_earnings"),
            event_risk_level=event_item.get("event_risk_level", "unknown"),
            latest_10k=event_item.get("latest_10k"),
            latest_10q=event_item.get("latest_10q"),
            latest_8k=event_item.get("latest_8k"),
            latest_periodic_filing_date=event_item.get("latest_periodic_filing_date"),
            periodic_filing_age_days=event_item.get("periodic_filing_age_days"),
            periodic_filing_stale=event_item.get("periodic_filing_stale"),
            known_risk_tags=event_item.get("known_risk_tags", []),
        )
        risk_tags = sorted(set(candidate.risk_tags + sec_data.risk_flags))
        enriched.append(
            candidate.model_copy(
                update={
                    "sec_data": sec_data,
                    "fundamental_data": fundamental_data,
                    "event_data": event_data,
                    "risk_tags": risk_tags,
                }
            )
        )
    return candidate_pool.model_copy(update={"candidates": enriched})


def reflect_candidate_pool(
    policy: InvestmentPolicy,
    candidate_pool: CandidatePool,
    artifacts: dict[str, dict[str, Any]],
) -> CandidatePoolReflection:
    """Run a constrained reflection pass over generated market artifacts."""
    checks = [
        "current portfolio was not read before candidate generation",
        "candidate additions must come from market artifacts, not LLM memory",
        "portfolio maps may only use symbols in the enriched candidate_pool",
        "coverage requirements from theme discovery are preserved for architect omission audits",
    ]
    missing_exposure = _missing_exposures(candidate_pool)
    stale_data = _stale_data(policy, candidate_pool, artifacts)
    weak_sources = [
        candidate.symbol
        for candidate in candidate_pool.candidates
        if len(set(candidate.source_tags or [candidate.source])) < 2
    ]
    diversification = artifacts.get("correlation_and_diversification", {})
    diversification_score = diversification.get("diversification_score")
    recommended_actions: list[dict[str, Any]] = []
    if missing_exposure:
        recommended_actions.append(
            {
                "action": "expand_theme_keywords",
                "reason": "Candidate pool does not cover all expected theme exposures.",
                "missing_exposure": missing_exposure,
            }
        )
    if not _has_plate_source(candidate_pool):
        recommended_actions.append(
            {
                "action": "fetch_futu_plate_constituents",
                "reason": "Futu plate/constituent data is not yet present in the artifact set.",
            }
        )
    if policy.allow_options and stale_data:
        recommended_actions.append(
            {
                "action": "refresh_options_surface",
                "reason": "Options overlay was allowed, but option surface data is incomplete.",
            }
        )
    if isinstance(diversification_score, int | float) and diversification_score < 0.45:
        recommended_actions.append(
            {
                "action": "expand_theme_keywords",
                "reason": "Candidate pool appears highly correlated; add adjacent exposures before finalizing maps.",
                "diversification_score": diversification_score,
            }
        )

    warnings = list(candidate_pool.warnings)
    if len(candidate_pool.candidates) < 3:
        warnings.append("Candidate pool has fewer than 3 symbols; generated maps may be too concentrated.")
    if weak_sources:
        warnings.append("Some candidates have weak source diversity.")
    if isinstance(diversification_score, int | float) and diversification_score < 0.45:
        warnings.append("Candidate pool has low diversification score.")

    coverage_ok = len(candidate_pool.candidates) >= 3 and not missing_exposure
    return CandidatePoolReflection(
        coverage_ok=coverage_ok,
        missing_exposure=missing_exposure,
        stale_data=stale_data,
        weak_sources=weak_sources,
        recommended_actions=recommended_actions,
        checks=checks,
        warnings=warnings,
    )


def _market_context(
    policy: InvestmentPolicy,
    candidate_pool: CandidatePool,
    generated_at: str,
) -> dict[str, Any]:
    return {
        "artifact_type": "market_context",
        "theme": candidate_pool.theme,
        "generated_at": generated_at,
        "discovery_thesis": candidate_pool.discovery_thesis,
        "coverage_requirements": [
            requirement.model_dump(mode="json")
            for requirement in candidate_pool.coverage_requirements
        ],
        "excludes_current_portfolio": True,
        "policy": policy.model_dump(mode="json"),
        "sources": candidate_pool.generated_from,
        "candidate_count": len(candidate_pool.candidates),
        "symbols": [candidate.symbol for candidate in candidate_pool.candidates],
    }


def _theme_exposure_map(candidate_pool: CandidatePool, generated_at: str) -> dict[str, Any]:
    if candidate_pool.coverage_requirements:
        exposures = []
        eligible_symbols = {
            candidate.symbol.upper()
            for candidate in candidate_pool.candidates
            if candidate.eligible_for_portfolio
        }
        for requirement in candidate_pool.coverage_requirements:
            symbols = [symbol for symbol in requirement.candidate_symbols if symbol.upper() in eligible_symbols]
            exposures.append(
                {
                    "exposure_key": requirement.key,
                    "label": requirement.name,
                    "priority": requirement.priority,
                    "thesis": requirement.thesis,
                    "status": "covered" if len(symbols) >= requirement.min_candidates else "missing",
                    "candidate_symbols": symbols,
                    "must_consider_symbols": requirement.must_consider_symbols,
                    "evidence_needed": requirement.evidence_needed,
                }
            )
        return {
            "artifact_type": "theme_exposure_map",
            "theme": candidate_pool.theme,
            "generated_at": generated_at,
            "exposures": exposures,
            "source": "theme_discovery_coverage_requirements",
        }

    return {
        "artifact_type": "theme_exposure_map",
        "theme": candidate_pool.theme,
        "generated_at": generated_at,
        "exposures": [],
        "source": "theme_discovery_coverage_requirements",
        "warnings": [
            "Theme exposure map is unavailable because discovery returned no coverage_requirements."
        ],
    }


def _plate_constituents(candidate_pool: CandidatePool, generated_at: str) -> dict[str, Any]:
    has_plate_source = _has_plate_source(candidate_pool)
    memberships: dict[str, dict[str, Any]] = {}
    for candidate in candidate_pool.candidates:
        for membership in candidate.plate_memberships:
            plate_code = membership.get("plate_code", "")
            if not plate_code:
                continue
            plate = memberships.setdefault(
                plate_code,
                {
                    "plate_code": plate_code,
                    "plate_name": membership.get("plate_name", ""),
                    "plate_type": membership.get("plate_type", ""),
                    "constituents": [],
                },
            )
            plate["constituents"].append(
                {
                    "symbol": candidate.symbol,
                    "name": candidate.name,
                    "role_hint": candidate.theme_role,
                }
            )
    return {
        "artifact_type": "plate_constituents",
        "theme": candidate_pool.theme,
        "generated_at": generated_at,
        "source_status": "available" if has_plate_source else "not_wired",
        "source": "futu_plate_stock" if has_plate_source else None,
        "plates": list(memberships.values()),
        "constituents": [
            {
                "symbol": candidate.symbol,
                "name": candidate.name,
                "role_hint": candidate.theme_role,
                "source_tags": candidate.source_tags,
                "plate_memberships": candidate.plate_memberships,
            }
            for candidate in candidate_pool.candidates
        ],
        "warnings": []
        if has_plate_source
        else ["Futu plate/constituent adapter is not wired into this MVP build."],
    }


def _market_snapshot(candidates: list[Candidate], generated_at: str) -> dict[str, Any]:
    return {
        "artifact_type": "market_snapshot",
        "generated_at": generated_at,
        "items": [
            {
                "symbol": candidate.symbol,
                "name": candidate.name,
                **_futu_quote_payload(candidate),
            }
            for candidate in candidates
        ],
    }


def _technical_summary(candidates: list[Candidate], generated_at: str) -> dict[str, Any]:
    return {
        "artifact_type": "technical_summary",
        "generated_at": generated_at,
        "items": [
            {
                "symbol": candidate.symbol,
                **_futu_technical_payload(candidate),
            }
            for candidate in candidates
        ],
    }


def _liquidity_context(candidates: list[Candidate], generated_at: str) -> dict[str, Any]:
    return {
        "artifact_type": "liquidity_context",
        "generated_at": generated_at,
        "items": [
            {
                "symbol": candidate.symbol,
                **_futu_liquidity_payload(candidate),
            }
            for candidate in candidates
        ],
    }


def _options_surface(
    candidates: list[Candidate],
    policy: InvestmentPolicy,
    generated_at: str,
) -> dict[str, Any]:
    return {
        "artifact_type": "options_surface",
        "generated_at": generated_at,
        "requested": policy.allow_options,
        "items": [
            {
                "symbol": candidate.symbol,
                **_futu_options_payload(candidate),
            }
            for candidate in candidates
        ],
    }


def _risk_flags(
    candidates: list[Candidate],
    generated_at: str,
    sec_context: dict[str, Any],
) -> dict[str, Any]:
    return {
        "artifact_type": "risk_flags",
        "generated_at": generated_at,
        "sources": ["candidate_metadata", _sec_source(sec_context)],
        "items": [
            {
                "symbol": candidate.symbol,
                "risk_tags": sorted(
                    set(candidate.risk_tags + (_sec_item(sec_context, candidate.symbol).get("risk_flags") or []))
                ),
                "sec_event_risk_level": (
                    _sec_item(sec_context, candidate.symbol).get("event_context", {}).get("event_risk_level")
                ),
            }
            for candidate in candidates
        ],
    }


def _fundamental_quality(
    candidates: list[Candidate],
    generated_at: str,
    sec_context: dict[str, Any],
) -> dict[str, Any]:
    return {
        "artifact_type": "fundamental_quality",
        "generated_at": generated_at,
        "sources": ["futu_market_snapshot", _sec_source(sec_context)],
        "sec_source_status": _sec_status(sec_context),
        "source_limits": [
            "Snapshot fundamentals are point-in-time fields and are not a full SEC filing model.",
            "SEC companyfacts adds filing-derived fundamentals but does not include forward estimates.",
        ],
        "items": [
            _fundamental_quality_item(candidate, _sec_item(sec_context, candidate.symbol))
            for candidate in candidates
        ],
    }


def _valuation_context(candidates: list[Candidate], generated_at: str) -> dict[str, Any]:
    pe_values = [_quote_num(candidate, "pe_ttm_ratio") for candidate in candidates]
    pb_values = [_quote_num(candidate, "pb_ratio") for candidate in candidates]
    pe_values = [value for value in pe_values if value and value > 0]
    pb_values = [value for value in pb_values if value and value > 0]
    pe_median = median(pe_values) if pe_values else None
    pb_median = median(pb_values) if pb_values else None
    return {
        "artifact_type": "valuation_context",
        "generated_at": generated_at,
        "source": "futu_market_snapshot",
        "peer_medians": {
            "pe_ttm": round(pe_median, 4) if pe_median is not None else None,
            "pb": round(pb_median, 4) if pb_median is not None else None,
        },
        "items": [
            _valuation_item(candidate, pe_median, pb_median)
            for candidate in candidates
        ],
    }


def _earnings_event_calendar(
    candidates: list[Candidate],
    generated_at: str,
    sec_context: dict[str, Any],
) -> dict[str, Any]:
    sec_status = _sec_status(sec_context)
    available = sec_status in {"available", "partial"}
    return {
        "artifact_type": "earnings_event_calendar",
        "generated_at": generated_at,
        "source_status": "partial" if available else sec_status,
        "sources": [_sec_source(sec_context)],
        "required_provider": "forward_earnings_calendar_adapter",
        "items": [
            _earnings_event_item(candidate, _sec_item(sec_context, candidate.symbol))
            for candidate in candidates
        ],
        "warnings": list(sec_context.get("warnings", []))
        + ["SEC filings show recent reporting events but do not provide the next earnings date."],
    }


def _correlation_and_diversification(candidates: list[Candidate], generated_at: str) -> dict[str, Any]:
    pairs = []
    correlations = []
    for index, left in enumerate(candidates):
        left_returns = _technical_value(left, "daily_returns_60d") or []
        for right in candidates[index + 1 :]:
            right_returns = _technical_value(right, "daily_returns_60d") or []
            corr = _correlation(left_returns, right_returns)
            if corr is None:
                continue
            correlations.append(corr)
            pairs.append(
                {
                    "left": left.symbol,
                    "right": right.symbol,
                    "correlation": round(corr, 4),
                }
            )
    avg_corr = sum(correlations) / len(correlations) if correlations else None
    diversification_score = 1 - max(0.0, avg_corr) if avg_corr is not None else None
    return {
        "artifact_type": "correlation_and_diversification",
        "generated_at": generated_at,
        "source": "futu_history_kline",
        "lookback": "60 daily returns",
        "avg_pairwise_corr_60d": round(avg_corr, 4) if avg_corr is not None else None,
        "diversification_score": round(diversification_score, 4)
        if diversification_score is not None
        else None,
        "highest_correlations": sorted(pairs, key=lambda item: item["correlation"], reverse=True)[:10],
        "cluster_hint": _cluster_hint(candidates, avg_corr),
    }


def _benchmark_context(
    candidate_pool: CandidatePool,
    macro_context: dict[str, Any],
    generated_at: str,
) -> dict[str, Any]:
    benchmark = macro_context.get("benchmark_context")
    if benchmark:
        return benchmark
    avg_rs = (
        sum(_technical_num(candidate, "relative_strength_60d") or 0.0 for candidate in candidate_pool.candidates)
        / len(candidate_pool.candidates)
        if candidate_pool.candidates
        else None
    )
    return {
        "artifact_type": "benchmark_context",
        "generated_at": generated_at,
        "source_status": "not_available",
        "theme": candidate_pool.theme,
        "candidate_avg_relative_strength": round(avg_rs, 4) if avg_rs is not None else None,
        "warnings": ["Benchmark ETF proxies were not supplied by the market-data adapter."],
    }


def _market_regime(macro_context: dict[str, Any], generated_at: str) -> dict[str, Any]:
    regime = macro_context.get("market_regime")
    if regime:
        return regime
    return {
        "artifact_type": "market_regime",
        "generated_at": generated_at,
        "source_status": "not_available",
        "items": {},
        "warnings": ["Market regime proxies were not supplied by the market-data adapter."],
    }


def _positioning_and_sentiment(candidates: list[Candidate], generated_at: str) -> dict[str, Any]:
    return {
        "artifact_type": "positioning_and_sentiment",
        "generated_at": generated_at,
        "source": "futu_snapshot_and_option_surface",
        "items": [
            {
                "symbol": candidate.symbol,
                "volume_ratio": _quote_num(candidate, "volume_ratio"),
                "turnover_rate": _quote_num(candidate, "turnover_rate"),
                "bid_ask_ratio": _quote_num(candidate, "bid_ask_ratio"),
                "avg_implied_volatility": _options_num(candidate, "avg_implied_volatility"),
                "put_contracts_sampled": len(_options_value(candidate, "put_candidates") or []),
                "call_contracts_sampled": len(_options_value(candidate, "call_candidates") or []),
                "sentiment_signal": _sentiment_signal(candidate),
            }
            for candidate in candidates
        ],
    }


def _analyst_revision_context(candidates: list[Candidate], generated_at: str) -> dict[str, Any]:
    return {
        "artifact_type": "analyst_revision_context",
        "generated_at": generated_at,
        "source_status": "not_wired",
        "required_provider": "analyst_estimate_revision_adapter",
        "items": [
            {
                "symbol": candidate.symbol,
                "eps_revision_30d": None,
                "revenue_revision_30d": None,
                "rating_change_30d": None,
                "revision_signal": "unknown",
            }
            for candidate in candidates
        ],
        "warnings": ["Analyst estimate revisions are not available from Futu OpenAPI in this MVP."],
    }


def _risk_scenario(
    candidate_pool: CandidatePool,
    macro_context: dict[str, Any],
    generated_at: str,
) -> dict[str, Any]:
    regime = macro_context.get("market_regime", {})
    signals = regime.get("signals", [])
    missing = _missing_exposures(candidate_pool)
    scenarios = [
        {
            "name": "theme_drawdown",
            "trigger": "Theme ETF or leading constituents break down versus SPY/QQQ.",
            "impact": "All holdings can correlate lower despite apparent single-name diversification.",
            "mitigation": "Keep sleeve sizing below policy limit and revisit candidate coverage.",
        },
        {
            "name": "earnings_reset",
            "trigger": "Upcoming earnings or guidance cut.",
            "impact": "High multiple or cycle-sensitive names may gap beyond technical levels.",
            "mitigation": "Require earnings calendar artifact before execution planning.",
        },
        {
            "name": "rates_or_volatility_shock",
            "trigger": "Bond proxies weaken, volatility proxies rise, or liquidity thins.",
            "impact": "Long-duration and high-beta candidates should receive lower weights.",
            "mitigation": "Prefer profitable leaders and raise cash in the selected map.",
        },
    ]
    if missing:
        scenarios.append(
            {
                "name": "theme_coverage_gap",
                "trigger": "Missing exposures: " + ", ".join(missing),
                "impact": "Portfolio may express only part of the intended theme.",
                "mitigation": "Expand candidates before final map approval.",
            }
        )
    return {
        "artifact_type": "risk_scenario",
        "generated_at": generated_at,
        "market_regime_signals": signals,
        "scenarios": scenarios,
    }


def _sec_filings_context(
    candidates: list[Candidate],
    sec_context: dict[str, Any],
    generated_at: str,
) -> dict[str, Any]:
    status = _sec_status(sec_context)
    return {
        "artifact_type": "sec_filings_context",
        "generated_at": generated_at,
        "source": _sec_source(sec_context),
        "source_status": status,
        "requested_symbols": sec_context.get("requested_symbols", [candidate.symbol for candidate in candidates]),
        "fetched_symbols": sec_context.get("fetched_symbols", []),
        "items": [
            _sec_filings_item(candidate, _sec_item(sec_context, candidate.symbol), status)
            for candidate in candidates
        ],
        "warnings": list(sec_context.get("warnings", [])),
    }


def _sec_filings_item(
    candidate: Candidate,
    sec_item: dict[str, Any],
    fallback_status: str,
) -> dict[str, Any]:
    filings = sec_item.get("filings", {}) if isinstance(sec_item, dict) else {}
    return {
        "symbol": candidate.symbol,
        "ticker": sec_item.get("ticker"),
        "source_status": sec_item.get("source_status", fallback_status),
        "cik": sec_item.get("cik"),
        "company_name": sec_item.get("company_name"),
        "industry": sec_item.get("industry"),
        "fiscal_year_end": sec_item.get("fiscal_year_end"),
        "filer_category": sec_item.get("filer_category"),
        "latest_10k": filings.get("latest_10k"),
        "latest_10q": filings.get("latest_10q"),
        "latest_8k": filings.get("latest_8k"),
        "numeric_evidence": sec_item.get("numeric_evidence", {}),
        "narrative_evidence": sec_item.get("narrative_evidence", {}),
        "event_context": sec_item.get("event_context", {}),
        "risk_flags": sec_item.get("risk_flags", []),
        "error": sec_item.get("error"),
    }


def _fundamental_quality_item(candidate: Candidate, sec_item: dict[str, Any]) -> dict[str, Any]:
    fundamentals = sec_item.get("fundamentals", {}) if isinstance(sec_item, dict) else {}
    return {
        "symbol": candidate.symbol,
        "net_profit": _quote_num(candidate, "net_profit"),
        "eps": _quote_num(candidate, "earning_per_share"),
        "net_asset_per_share": _quote_num(candidate, "net_asset_per_share"),
        "dividend_yield_ttm": _quote_num(candidate, "dividend_ratio_ttm"),
        "ttm_revenue": _num(fundamentals.get("ttm_revenue")),
        "ttm_net_income": _num(fundamentals.get("ttm_net_income")),
        "gross_profit": _num(fundamentals.get("gross_profit")),
        "operating_income": _num(fundamentals.get("operating_income")),
        "total_assets": _num(fundamentals.get("total_assets")),
        "total_liabilities": _num(fundamentals.get("total_liabilities")),
        "shareholders_equity": _num(fundamentals.get("shareholders_equity")),
        "debt_to_assets": _num(fundamentals.get("debt_to_assets")),
        "roe": _num(fundamentals.get("roe")),
        "net_margin": _num(fundamentals.get("net_margin")),
        "quality_score": _quality_score_with_sec(candidate, fundamentals),
        "data_status": _combined_fundamental_status(candidate, sec_item),
        "numeric_source": _numeric_source(candidate, sec_item),
        "numeric_llm_generated": False,
    }


def _earnings_event_item(candidate: Candidate, sec_item: dict[str, Any]) -> dict[str, Any]:
    filings = sec_item.get("filings", {}) if isinstance(sec_item, dict) else {}
    event_context = sec_item.get("event_context", {}) if isinstance(sec_item, dict) else {}
    return {
        "symbol": candidate.symbol,
        "next_earnings_date": None,
        "days_to_earnings": None,
        "event_risk_level": event_context.get("event_risk_level", "unknown"),
        "latest_10k": filings.get("latest_10k"),
        "latest_10q": filings.get("latest_10q"),
        "latest_8k": filings.get("latest_8k"),
        "latest_periodic_filing_date": event_context.get("latest_periodic_filing_date"),
        "periodic_filing_age_days": event_context.get("periodic_filing_age_days"),
        "periodic_filing_stale": event_context.get("periodic_filing_stale"),
        "known_risk_tags": [
            tag for tag in candidate.risk_tags if "earning" in tag.lower() or "财报" in tag
        ]
        + (sec_item.get("risk_flags", []) if isinstance(sec_item, dict) else []),
        "source_status": sec_item.get("source_status", "not_available") if isinstance(sec_item, dict) else "not_available",
    }


def _sec_item(sec_context: dict[str, Any], symbol: str) -> dict[str, Any]:
    items = sec_context.get("items", {}) if isinstance(sec_context, dict) else {}
    item = items.get(symbol) or items.get(symbol.upper())
    return item if isinstance(item, dict) else {}


def _sec_status(sec_context: dict[str, Any]) -> str:
    if not sec_context:
        return "not_available"
    return str(sec_context.get("source_status") or "not_available")


def _sec_source(sec_context: dict[str, Any]) -> str:
    source = str(sec_context.get("source") or "edgartools")
    return f"{source}:{_sec_status(sec_context)}"


def _missing_exposures(candidate_pool: CandidatePool) -> list[str]:
    if candidate_pool.coverage_requirements:
        eligible_symbols = {
            candidate.symbol.upper()
            for candidate in candidate_pool.candidates
            if candidate.eligible_for_portfolio
        }
        missing = []
        for requirement in candidate_pool.coverage_requirements:
            if requirement.priority == "optional":
                continue
            candidates = {symbol.upper() for symbol in requirement.candidate_symbols}
            must_consider = {symbol.upper() for symbol in requirement.must_consider_symbols}
            expected = must_consider or candidates
            if expected and not expected.intersection(eligible_symbols):
                missing.append(requirement.name or requirement.key)
        return missing

    return []


def _stale_data(
    policy: InvestmentPolicy,
    candidate_pool: CandidatePool,
    artifacts: dict[str, dict[str, Any]],
) -> list[str]:
    stale = []
    if not candidate_pool.candidates:
        stale.append("candidate_pool")
    if policy.allow_options:
        options = artifacts.get("options_surface", {})
        option_items = options.get("items", [])
        if not option_items or not any(item.get("has_option_data") for item in option_items):
            stale.append("options_surface")
    sec_filings = artifacts.get("sec_filings_context", {})
    if sec_filings.get("source_status") in {"not_available", "not_configured", "unavailable"}:
        stale.append("sec_filings_context")
    if any(
        item.get("event_context", {}).get("periodic_filing_stale")
        for item in sec_filings.get("items", [])
    ):
        stale.append("sec_periodic_filings")
    return stale


def _has_plate_source(candidate_pool: CandidatePool) -> bool:
    source_tags = set(candidate_pool.generated_from)
    for candidate in candidate_pool.candidates:
        source_tags.update(candidate.source_tags)
    return any("plate" in tag for tag in source_tags)


def _futu_quote_payload(candidate: Candidate) -> dict[str, Any]:
    quote = candidate.futu_data.quote if candidate.futu_data else None
    return quote.model_dump(exclude_none=True, exclude={"raw"}) if quote else {}


def _futu_technical_payload(candidate: Candidate) -> dict[str, Any]:
    technical = candidate.futu_data.technical if candidate.futu_data else None
    return technical.model_dump(exclude_none=True, exclude={"raw"}) if technical else {}


def _futu_liquidity_payload(candidate: Candidate) -> dict[str, Any]:
    liquidity = candidate.futu_data.liquidity if candidate.futu_data else None
    return liquidity.model_dump(exclude_none=True, exclude={"raw"}) if liquidity else {}


def _futu_options_payload(candidate: Candidate) -> dict[str, Any]:
    options = candidate.futu_data.options if candidate.futu_data else None
    return options.model_dump(exclude_none=True, exclude={"raw"}) if options else {}


def _quote_value(candidate: Candidate, key: str) -> Any:
    quote = candidate.futu_data.quote if candidate.futu_data else None
    return getattr(quote, key, None) if quote else None


def _technical_value(candidate: Candidate, key: str) -> Any:
    technical = candidate.futu_data.technical if candidate.futu_data else None
    return getattr(technical, key, None) if technical else None


def _options_value(candidate: Candidate, key: str) -> Any:
    options = candidate.futu_data.options if candidate.futu_data else None
    return getattr(options, key, None) if options else None


def _quote_num(candidate: Candidate, key: str) -> float | None:
    return _num(_quote_value(candidate, key))


def _technical_num(candidate: Candidate, key: str) -> float | None:
    return _num(_technical_value(candidate, key))


def _options_num(candidate: Candidate, key: str) -> float | None:
    return _num(_options_value(candidate, key))


def _num(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    if math.isnan(number):
        return None
    return number


def _quality_score(candidate: Candidate) -> float | None:
    net_profit = _quote_num(candidate, "net_profit")
    eps = _quote_num(candidate, "earning_per_share")
    market_cap = _quote_num(candidate, "total_market_val")
    if net_profit is None and eps is None and market_cap is None:
        return None
    score = 0.35
    if net_profit and net_profit > 0:
        score += 0.25
    if eps and eps > 0:
        score += 0.20
    if market_cap and market_cap > 10_000_000_000:
        score += 0.10
    if (_technical_num(candidate, "relative_strength_60d") or 0.0) >= 65:
        score += 0.10
    return round(min(1.0, score), 4)


def _quality_score_with_sec(candidate: Candidate, fundamentals: dict[str, Any]) -> float | None:
    base = _quality_score(candidate)
    if not fundamentals:
        return base
    score = base if base is not None else 0.35
    ttm_net_income = _num(fundamentals.get("ttm_net_income"))
    net_margin = _num(fundamentals.get("net_margin"))
    debt_to_assets = _num(fundamentals.get("debt_to_assets"))
    if ttm_net_income and ttm_net_income > 0:
        score += 0.08
    if net_margin and net_margin > 0.10:
        score += 0.04
    if debt_to_assets is not None and debt_to_assets < 0.65:
        score += 0.03
    return round(min(1.0, score), 4)


def _fundamental_status(candidate: Candidate) -> str:
    keys = ("net_profit", "earning_per_share", "net_asset_per_share", "pe_ttm_ratio", "pb_ratio")
    available = sum(1 for key in keys if _quote_num(candidate, key) is not None)
    if available >= 4:
        return "partial_snapshot"
    if available:
        return "sparse_snapshot"
    return "not_available"


def _combined_fundamental_status(candidate: Candidate, sec_item: dict[str, Any]) -> str:
    sec_status = sec_item.get("source_status") if isinstance(sec_item, dict) else None
    if sec_status == "available" and sec_item.get("fundamentals"):
        return "snapshot_plus_sec_companyfacts"
    snapshot_status = _fundamental_status(candidate)
    if snapshot_status != "not_available":
        return snapshot_status
    return sec_status or "not_available"


def _numeric_source(candidate: Candidate, sec_item: dict[str, Any]) -> str:
    sec_status = sec_item.get("source_status") if isinstance(sec_item, dict) else None
    if sec_status == "available" and sec_item.get("fundamentals"):
        snapshot_status = _fundamental_status(candidate)
        if snapshot_status != "not_available":
            return "futu_snapshot_plus_sec_companyfacts"
        return "sec_companyfacts"
    snapshot_status = _fundamental_status(candidate)
    if snapshot_status != "not_available":
        return "futu_snapshot"
    return "not_available"


def _valuation_item(candidate: Candidate, pe_median: float | None, pb_median: float | None) -> dict[str, Any]:
    pe = _quote_num(candidate, "pe_ttm_ratio")
    pb = _quote_num(candidate, "pb_ratio")
    high_52w = _quote_num(candidate, "highest52weeks_price")
    low_52w = _quote_num(candidate, "lowest52weeks_price")
    last_price = _quote_num(candidate, "last_price")
    position_52w = None
    if last_price is not None and high_52w and low_52w is not None and high_52w > low_52w:
        position_52w = (last_price - low_52w) / (high_52w - low_52w)
    return {
        "symbol": candidate.symbol,
        "market_cap": _quote_num(candidate, "total_market_val"),
        "pe_ttm": pe,
        "pb": pb,
        "dividend_yield_ttm": _quote_num(candidate, "dividend_ratio_ttm"),
        "position_52w": round(position_52w, 4) if position_52w is not None else None,
        "valuation_vs_peers": _valuation_label(pe, pe_median, pb, pb_median),
    }


def _valuation_label(
    pe: float | None,
    pe_median: float | None,
    pb: float | None,
    pb_median: float | None,
) -> str:
    expensive_votes = 0
    cheap_votes = 0
    if pe and pe_median:
        expensive_votes += pe > pe_median * 1.2
        cheap_votes += pe < pe_median * 0.8
    if pb and pb_median:
        expensive_votes += pb > pb_median * 1.2
        cheap_votes += pb < pb_median * 0.8
    if expensive_votes:
        return "expensive_vs_candidate_pool"
    if cheap_votes:
        return "cheap_vs_candidate_pool"
    if pe or pb:
        return "near_candidate_pool_median"
    return "unknown"


def _correlation(left: list[float], right: list[float]) -> float | None:
    count = min(len(left), len(right))
    if count < 10:
        return None
    left = left[-count:]
    right = right[-count:]
    left_mean = sum(left) / count
    right_mean = sum(right) / count
    numerator = sum((l_val - left_mean) * (r_val - right_mean) for l_val, r_val in zip(left, right))
    left_var = sum((l_val - left_mean) ** 2 for l_val in left)
    right_var = sum((r_val - right_mean) ** 2 for r_val in right)
    denom = math.sqrt(left_var * right_var)
    if denom <= 0:
        return None
    return numerator / denom


def _cluster_hint(candidates: list[Candidate], avg_corr: float | None) -> str:
    if avg_corr is None:
        return "insufficient_return_history"
    if avg_corr >= 0.75:
        return "highly_correlated_theme_cluster"
    if avg_corr >= 0.45:
        return "moderately_correlated_theme_cluster"
    return "diversified_candidate_pool"


def _sentiment_signal(candidate: Candidate) -> str:
    volume_ratio = _quote_num(candidate, "volume_ratio")
    iv = _options_num(candidate, "avg_implied_volatility")
    bid_ask = _quote_num(candidate, "bid_ask_ratio")
    if iv and iv >= 80:
        return "high_option_uncertainty"
    if volume_ratio and volume_ratio >= 1.8 and (_technical_num(candidate, "relative_strength_60d") or 0.0) >= 65:
        return "momentum_attention"
    if bid_ask and bid_ask <= -20:
        return "orderbook_pressure"
    return "neutral"
