import json
import os
import matplotlib
matplotlib.use('Agg') # Use non-interactive backend
import matplotlib.pyplot as plt
import numpy as np
from collections import defaultdict

def plot_quantum_runs(filepath="data/archival/quantum_runs.jsonl", output_path="quantum_histogram.png"):
    if not os.path.exists(filepath):
        print(f"Error: {filepath} not found.")
        return

    print(f"Loading data from {filepath}...")
    global_counts = defaultdict(int)
    total_shots = 0
    total_runs = 0

    try:
        with open(filepath, "r") as f:
            for i, line in enumerate(f):
                if not line.strip():
                    continue
                try:
                    run = json.loads(line)
                    counts = run.get("counts", {})
                    for state, count in counts.items():
                        global_counts[state] += int(count)
                    total_shots += sum(counts.values())
                    total_runs += 1
                except (json.JSONDecodeError, ValueError) as e:
                    print(f"Skipping line {i+1} due to error: {e}")
                    continue
    except Exception as e:
        print(f"Critical error reading file: {e}")
        return

    print(f"Processing complete. Runs: {total_runs}, Shots: {total_shots}")
    if total_shots == 0:
        print("No shot data available to plot.")
        return

    # Ensure all 32 basis states for 5 qubits exist
    all_states = [format(i, '05b') for i in range(32)]
    frequencies = {state: global_counts.get(state, 0) for state in all_states}

    # Sort states by frequency (descending)
    sorted_states = sorted(frequencies.items(), key=lambda x: x[1], reverse=True)
    states = [s[0] for s in sorted_states]
    counts = [float(s[1]) for s in sorted_states]
    probabilities = [(count / total_shots) * 100 for count in counts]

    print("Generating plot...")
    try:
        # Plotting
        plt.style.use('dark_background')
        fig, ax = plt.subplots(figsize=(14, 7))

        # Creates a neon-blue to purple color gradient
        colors = plt.cm.cool(np.linspace(0, 1, len(states)))
        
        bars = ax.bar(states, probabilities, color=colors, edgecolor='cyan', alpha=0.8)

        # Customize plot
        ax.set_title(f"Hermes Quantum Entanglement Distribution ({total_runs} Runs | {total_shots:,} Shots)", 
                    fontsize=16, pad=20, color='white', fontweight='bold')
        ax.set_xlabel("Hilbert Space Basis States (|00000\u27e9 to |11111\u27e9)", fontsize=12, labelpad=15, color='white')
        ax.set_ylabel("Measurement Probability (%)", fontsize=12, labelpad=15, color='white')
        
        # Grid and Spines
        ax.grid(axis='y', linestyle='--', alpha=0.3)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.spines['left'].set_color('#aaaaaa')
        ax.spines['bottom'].set_color('#aaaaaa')

        plt.xticks(rotation=90, fontsize=10, fontfamily='monospace')
        plt.yticks(fontsize=10)
        
        # Add value labels on top of the top 5 bars
        for i in range(min(5, len(bars))):
            bar = bars[i]
            height = bar.get_height()
            ax.annotate(f'{height:.2f}%',
                        xy=(bar.get_x() + bar.get_width() / 2, height),
                        xytext=(0, 3),  # 3 points vertical offset
                        textcoords="offset points",
                        ha='center', va='bottom', fontsize=9, color='cyan', fontweight='bold')

        # Add watermark/footer
        plt.figtext(0.99, 0.01, 'Generated by Cosmos 12D Hebbian Transformer | Hardware: ibm_fez',
                    horizontalalignment='right', fontsize=8, color='#888888')

        plt.tight_layout()
        plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor=fig.get_facecolor())
        print(f"Graph successfully saved to {output_path}")
    except Exception as e:
        print(f"Error during plotting: {e}")

if __name__ == "__main__":
    plot_quantum_runs(r"D:\Cosmos\Cosmos\data\archival\quantum_runs.jsonl", r"D:\Cosmos\Cosmos\quantum_histogram.png")
