"""Scaffold a new Typst project directory.

Usage:
    python new_project.py <name> --type article|report|slides
    python new_project.py <name> --type article --path /tmp/scratch
    python new_project.py <name> --type article --no-gitignore

Creates a fresh directory with a main.typ based on the chosen template,
a placeholder refs.bib for citations, an empty figures/ subdirectory, and
a .gitignore that excludes the typical Typst build artifacts (PDF, HTML,
PNG, aux). Safe to run repeatedly — refuses to overwrite an existing
directory unless --force is passed.

Stdlib only. No third-party dependencies.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path


GITIGNORE_LINES = [
    "# Typst build artifacts",
    "*.pdf",
    "*.html",
    "*.png",
    "*.svg",
    "*.aux",
    "*.log",
    "*.fls",
    "*.fdb_latexmk",
    "",
    "# OS / editor cruft",
    ".DS_Store",
    ".idea/",
    ".vscode/",
    "*.swp",
    "",
]

REFS_BIB_PLACEHOLDER = """% Bibliography file. Add BibTeX entries here, then cite from
% main.typ with:  @key  or  @key[p. 23]
%
% Example:
% @article{einstein1905,
%   author = {Einstein, Albert},
%   title  = {On the Electrodynamics of Moving Bodies},
%   year   = {1905},
%   journal = {Annalen der Physik},
% }
"""


def article_template() -> str:
    return (
        "// Generated by typst skill — article scaffold\n"
        "\n"
        "#set document(\n"
        "  title: [Article Title],\n"
        "  author: (\"Your Name\",),\n"
        ")\n"
        "\n"
        "#set text(font: \"New Computer Modern\", size: 11pt)\n"
        "#set par(justify: true, leading: 0.65em)\n"
        "\n"
        "#outline(title: [Contents], depth: 2, indent: auto)\n"
        "\n"
        "= Introduction\n"
        "\n"
        "Replace this paragraph with your introduction. Citations like\n"
        "@einstein1905 resolve automatically if you have an entry in\n"
        "`refs.bib`.\n"
        "\n"
        "= Methods\n"
        "\n"
        "= Results\n"
        "\n"
        "= Discussion\n"
        "\n"
        "// = References <references>\n"
        "//\n"
        "// #bibliography(\"refs.bib\")\n"
    )


def report_template() -> str:
    return (
        "// Generated by typst skill — report scaffold\n"
        "\n"
        "#set document(\n"
        "  title: [Report Title],\n"
        "  author: (\"Your Name\",),\n"
        ")\n"
        "\n"
        "#set text(font: \"New Computer Modern\", size: 11pt)\n"
        "#set par(justify: true, leading: 0.65em)\n"
        "\n"
        "#outline(title: [Contents], depth: 3, indent: auto)\n"
        "\n"
        "= Executive Summary\n"
        "\n"
        "= Background\n"
        "\n"
        "= Findings\n"
        "\n"
        "= Recommendations\n"
        "\n"
        "= Appendix\n"
    )


def slides_template() -> str:
    return (
        "// Generated by typst skill — slides scaffold\n"
        "\n"
        "#set document(\n"
        "  title: [Talk Title],\n"
        "  author: \"Your Name\",\n"
        ")\n"
        "\n"
        "// 16:9 aspect ratio for modern projectors\n"
        "#set page(\n"
        "  paper: \"presentation-16-9\",\n"
        "  margin: (x: 2.5em, y: 2em),\n"
        ")\n"
        "\n"
        "#set text(font: \"New Computer Modern\", size: 22pt)\n"
        "\n"
        "#title-slide[\n"
        "  = Talk Title\n"
        "\n"
        "  Your Name \\ Your Affiliation\n"
        "]\n"
        "\n"
        "= Outline\n"
        "\n"
        "= First Point\n"
        "\n"
        "Key claim, supported by evidence on the next slide.\n"
        "\n"
        "= Evidence\n"
        "\n"
        "#figure(\n"
        "  image(\"figures/diagram.png\", width: 80%),\n"
        "  caption: [Caption goes here.],\n"
        ")\n"
        "\n"
        "= Conclusions\n"
    )


TEMPLATES = {
    "article": article_template,
    "report": report_template,
    "slides": slides_template,
}


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scaffold a new Typst project directory.",
    )
    parser.add_argument(
        "name",
        help="Project name (used as the directory name and a placeholder in main.typ).",
    )
    parser.add_argument(
        "--type",
        choices=sorted(TEMPLATES.keys()),
        default="article",
        help="Template to start from (default: article).",
    )
    parser.add_argument(
        "--path",
        default=".",
        help="Parent directory in which to create the project (default: current dir).",
    )
    parser.add_argument(
        "--no-gitignore",
        action="store_true",
        help="Skip writing a .gitignore in the project directory.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing directory of the same name.",
    )
    return parser.parse_args(argv)


def scaffold(name: str, kind: str, parent: Path, write_gitignore: bool, force: bool) -> Path:
    project_dir = parent / name
    if project_dir.exists():
        if not force:
            raise SystemExit(
                f"refusing to overwrite existing directory: {project_dir} (pass --force to override)"
            )
        shutil.rmtree(project_dir)
    project_dir.mkdir(parents=True)
    (project_dir / "main.typ").write_text(TEMPLATES[kind](), encoding="utf-8")
    (project_dir / "refs.bib").write_text(REFS_BIB_PLACEHOLDER, encoding="utf-8")
    (project_dir / "figures").mkdir()
    (project_dir / "figures" / ".gitkeep").touch()
    if write_gitignore:
        (project_dir / ".gitignore").write_text("\n".join(GITIGNORE_LINES), encoding="utf-8")
    return project_dir


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    parent = Path(args.path).expanduser().resolve()
    if not parent.is_dir():
        raise SystemExit(f"parent path is not a directory: {parent}")
    project_dir = scaffold(
        name=args.name,
        kind=args.type,
        parent=parent,
        write_gitignore=not args.no_gitignore,
        force=args.force,
    )
    print(f"scaffolded {args.type} project at {project_dir}")
    print(f"next: cd {project_dir} && typst compile main.typ main.pdf")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
