"""#126883 — the sibling launchd restart must refresh a stale plist and drain the GATEWAY.

Two defects in ``_restart_macos_launchd_gateways``' sibling loop, both ending in
``hermes update`` exiting 1 on a clean pull:

1. The invoking profile's path (``launchd_restart()``) refreshes the installed plist
   before touching the service, because ``kickstart`` "faithfully revives a stale
   service" (its own comment). The sibling loop drained and kickstarted every
   derived/legacy label WITHOUT that refresh, so a plist generated by an older
   checkout (e.g. pre-``HERMES_SUPERVISED_CHILD``) was re-run as-is on every update.

2. The sibling loop drains the PID ``_locate_launchd_gateway_service`` reports, but
   under the current plist template launchd supervises the ``osascript`` wrapper
   (the job's Local Network identity), not the gateway. SIGUSR1 killed the wrapper
   (exit status -30), the gateway child was orphaned on pre-update code holding the
   socket, and fleet verification then reported the STALE that fails the update.
   The drain target must be the gateway the sibling's home actually declares on its
   control socket (#92091), falling back to the supervised PID only when no gateway
   answers.

Both fixes are scoped per sibling home; the account-global-label boundary (#93349 /
#41403 — a plist pinning a foreign HERMES_HOME is another install's job) must keep
holding: a foreign sibling is never refreshed, drained, or kickstarted.
"""

from __future__ import annotations

import os
import plistlib
from pathlib import Path
from types import SimpleNamespace

import pytest

import hermes_cli.gateway as gw
import hermes_cli.update_fleet_scope as fleet_scope
from hermes_cli.update_cmd import _restart_macos_launchd_gateways

pytestmark = pytest.mark.platforms("macos")  # launchd restart is macOS-only

UID = 501
CURRENT = "ai.hermes.gateway-invoker"
SIBLING = "ai.hermes.gateway-sib"


@pytest.fixture(autouse=True)
def _fixed_uid(monkeypatch):
    monkeypatch.setattr(gw.os, "getuid", lambda: UID)


def _write_plist(path, *, hermes_home, label):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(plistlib.dumps({
        "Label": label,
        "ProgramArguments": ["/usr/bin/true"],
        "EnvironmentVariables": {"HERMES_HOME": str(hermes_home)},
    }))
    return path


def _fleet(monkeypatch, tmp_path, *, labels, located, sibling_homes=None,
           foreign_homes=None, refresh_result=False, refresh_errors=None,
           identify_answer=None, drain_results=None, wait_results=None,
           bootstrap_error=None):
    """Wire a fake launchd fleet through the facade seams the sibling loop drives.

    ``sibling_homes`` maps label -> pinned HERMES_HOME **in this update's scope**;
    ``foreign_homes`` the same for homes belonging to another install. Both write a
    real plist file so the production ``launchd_label_pinned_home``/
    ``launchd_label_foreign_home`` read it. ``refresh_result`` is what the scoped
    refresh returns (it reloads when True); ``refresh_errors`` maps label -> an
    exception the refresh raises (one sibling's file IO wedging must not abort the
    fleet, #68523). ``identify_answer`` is the control-socket
    answer for the sibling home (dict or None). One shared ``events`` list pins
    ordering across recorders.
    """
    rec = SimpleNamespace(events=[], drains=[], kickstarts=[], waits=[], locates=[],
                          refreshes=[], identifies=[], current_restarts=[],
                          supervise_waits=[], wait_old_pids=[])

    agents = tmp_path / "LaunchAgents"
    current_plist = agents / f"{CURRENT}.plist"
    _write_plist(current_plist, hermes_home=tmp_path / "root", label=CURRENT)
    homes = {(tmp_path / "root").resolve()}
    for label, home in {**(sibling_homes or {}), **(foreign_homes or {})}.items():
        _write_plist(agents / f"{label}.plist", hermes_home=home, label=label)
    for home in (sibling_homes or {}).values():
        homes.add(home.resolve())
    # This update owns tmp root; every sibling_homes entry is in scope by definition,
    # every foreign_homes entry is out of it.
    monkeypatch.setattr(fleet_scope, "update_scope_homes", lambda: homes)

    def fake_locate(label):
        rec.locates.append(label)
        return located[label]

    def fake_refresh(label, home, *, domain):
        rec.events.append(f"refresh:{label}")
        rec.refreshes.append((label, Path(home), domain))
        err = (refresh_errors or {}).get(label)
        if err is not None:
            raise err
        # Boolean shorthand for the existing cases; a sentinel string passes
        # through so a test can wire the failed-to-re-register shape.
        if refresh_result is True:
            return gw.REFRESH_PLIST_RELOADED
        if refresh_result is False:
            return gw.REFRESH_PLIST_NO_CHANGE
        return refresh_result

    def fake_revive(label, domain, plist_path):
        rec.events.append(f"revive:{label}")
        rec.kickstarts.append(f"revive:{domain}/{label}")
        if bootstrap_error is not None:
            raise bootstrap_error

    def fake_identify(home, **_kw):
        rec.identifies.append(Path(home))
        return identify_answer

    def fake_drain(pid, drain_timeout, **_kw):
        rec.events.append(f"drain:{pid}")
        rec.drains.append(pid)
        return (drain_results or {}).get(pid, False)

    def fake_kickstart(label, domain):
        rec.events.append(f"kickstart:{label}")
        rec.kickstarts.append(f"{domain}/{label}")

    def fake_wait(label, old_pid, timeout, domain):
        rec.waits.append(f"{domain}/{label}")
        rec.wait_old_pids.append(old_pid)
        return (wait_results or {}).get(label, True)

    monkeypatch.setattr(gw, "get_launchd_label", lambda: CURRENT)
    monkeypatch.setattr(gw, "get_launchd_plist_path", lambda: current_plist)
    monkeypatch.setattr(gw, "launchd_gateway_labels_for_install", lambda: list(labels))
    monkeypatch.setattr(gw, "legacy_launchd_labels_for_install", lambda exclude=(): [])
    monkeypatch.setattr(gw, "_locate_launchd_gateway_service", fake_locate)
    monkeypatch.setattr(gw, "_graceful_restart_via_sigusr1", fake_drain)
    monkeypatch.setattr(gw, "_launchd_kickstart", fake_kickstart)
    monkeypatch.setattr(gw, "_wait_for_launchd_service_pid", fake_wait)
    monkeypatch.setattr(gw, "launchd_restart", lambda: rec.current_restarts.append(CURRENT))
    monkeypatch.setattr(gw, "wait_for_launchd_gateway_supervision", lambda *, label=None, **_: True)
    monkeypatch.setattr(
        gw, "refresh_launchd_plist_for_label", fake_refresh, raising=False)
    monkeypatch.setattr(
        gw, "launchd_reload_unregistered_job", fake_revive, raising=False)
    monkeypatch.setattr("gateway.control_socket.identify_gateway", fake_identify)
    return rec


class TestSiblingStalePlistRefresh:
    def test_stale_sibling_plist_is_refreshed_before_drain_and_kickstart(
        self, monkeypatch, tmp_path
    ):
        """The sibling loop upholds the invoking path's invariant (launchd_restart):
        kickstart re-runs whatever definition launchd holds, so a stale plist is
        rewritten and reloaded FIRST — and the refresh is scoped to the label's
        pinned home and located domain, not the invoking profile's."""
        sibling_home = tmp_path / "root" / "profiles" / "sib"
        rec = _fleet(
            monkeypatch, tmp_path,
            labels=[CURRENT, SIBLING],
            located={CURRENT: (f"gui/{UID}", 100), SIBLING: (f"user/{UID}", 200)},
            sibling_homes={SIBLING: sibling_home},
            refresh_result=False,  # plist current: ordinary drain + kickstart continue
        )
        restarted, failed = [], []
        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert rec.refreshes == [(SIBLING, sibling_home.resolve(), f"user/{UID}")]
        assert rec.events.index(f"refresh:{SIBLING}") < rec.events.index(f"drain:{200}")
        assert rec.events.index(f"refresh:{SIBLING}") < rec.events.index(f"kickstart:{SIBLING}")
        assert restarted == [CURRENT, SIBLING]
        assert failed == []

    def test_refresh_that_reloaded_skips_drain_and_kickstart(
        self, monkeypatch, tmp_path
    ):
        """A successful refresh already bootout/bootstrapped the job onto the new
        definition (RunAtLoad starts a fresh gateway). Draining or kickstarting it
        again would kill the process the refresh just brought up on new code; only
        the fresh-supervised-PID verification remains."""
        sibling_home = tmp_path / "root" / "profiles" / "sib"
        rec = _fleet(
            monkeypatch, tmp_path,
            labels=[CURRENT, SIBLING],
            located={CURRENT: (f"gui/{UID}", 100), SIBLING: (f"user/{UID}", 200)},
            sibling_homes={SIBLING: sibling_home},
            refresh_result=True,
        )
        restarted, failed = [], []
        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert rec.drains == []
        assert rec.kickstarts == []
        assert rec.waits == [f"user/{UID}/{SIBLING}"]
        # Same contract as the ordinary path: the reload-branch verification
        # baselines on the SUPERVISED pid launchd swapped, not any gateway pid.
        assert rec.wait_old_pids == [200]
        assert restarted == [CURRENT, SIBLING]
        assert failed == []

    def test_refresh_reloaded_but_unsupervised_is_failed(
        self, monkeypatch, tmp_path
    ):
        """A reload launchd never supervises is #88848's shape for a sibling: count
        it in failed_or_stale_units, never claim it restarted."""
        sibling_home = tmp_path / "root" / "profiles" / "sib"
        rec = _fleet(
            monkeypatch, tmp_path,
            labels=[CURRENT, SIBLING],
            located={CURRENT: (f"gui/{UID}", 100), SIBLING: (f"user/{UID}", 200)},
            sibling_homes={SIBLING: sibling_home},
            refresh_result=True,
            wait_results={SIBLING: False},
        )
        restarted, failed = [], []
        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert restarted == [CURRENT]
        assert failed == [SIBLING]


class TestSiblingFailureIsolation:
    """#68523: one sibling's wedged probe, timeout, or file IO is accounted as a
    failure and the loop CONTINUES — an exception escaping one label reaches the
    outer restart handler and every remaining sibling is left on pre-update code.
    The plist refresh gave the loop first-ever in-process file IO (plist read,
    log-dir mkdir, plist write), so ``OSError`` joins ``TimeoutExpired`` in the
    per-label catch."""

    def test_refresh_oserror_fails_only_that_sibling_and_loop_continues(
        self, monkeypatch, tmp_path, capsys
    ):
        unreadable = "ai.hermes.gateway-unreadable"
        after = "ai.hermes.gateway-after"
        rec = _fleet(
            monkeypatch, tmp_path,
            labels=[CURRENT, unreadable, after],
            located={
                CURRENT: (f"gui/{UID}", 100),
                unreadable: (f"user/{UID}", 200),
                after: (f"user/{UID}", 300),
            },
            sibling_homes={
                unreadable: tmp_path / "root" / "profiles" / "unreadable",
                after: tmp_path / "root" / "profiles" / "after",
            },
            refresh_errors={unreadable: PermissionError(13, "Operation not permitted")},
            wait_results={after: True},
        )
        restarted, failed = [], []
        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert failed == [unreadable]
        # The sibling AFTER the raising one was still restarted.
        assert rec.refreshes[-1][0] == after
        assert rec.kickstarts == [f"user/{UID}/{after}"]
        assert restarted == [CURRENT, after]
        out = capsys.readouterr().out
        assert unreadable in out
        assert "launchctl bootstrap" in out  # manual recovery names the working command

    def test_refresh_reregistration_failure_bootstraps_not_kickstart(
        self, monkeypatch, tmp_path, capsys
    ):
        """The loop adopted launchd_restart's refresh but must keep the OTHER half
        of its invariant: when the refresh rewrote the plist and launchd never
        re-registered the job (its False-with-reload shape), ``kickstart -k``
        cannot work on an unregistered job (#126883's stuck-unloaded class). Route
        to the bounded bootstrap+kickstart revival instead."""
        rec = _fleet(
            monkeypatch, tmp_path,
            labels=[CURRENT, SIBLING],
            located={CURRENT: (f"gui/{UID}", 100), SIBLING: (f"user/{UID}", 200)},
            sibling_homes={SIBLING: tmp_path / "root" / "profiles" / "sib"},
            refresh_result=gw.REFRESH_PLIST_FAILED_TO_REGISTER,
        )
        restarted, failed = [], []
        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        # No plain kickstart, and the drain must not fire on the unloaded job either.
        assert rec.kickstarts == [f"revive:user/{UID}/{SIBLING}"]
        assert rec.drains == []
        assert rec.waits == [f"user/{UID}/{SIBLING}"]
        assert rec.wait_old_pids == [200]
        assert restarted == [CURRENT, SIBLING]
        assert failed == []
        assert "not re-registered" in capsys.readouterr().out

    def test_refresh_reregistration_failure_revival_error_is_failed(
        self, monkeypatch, tmp_path
    ):
        """A bootstrap that itself fails lands in failed_or_stale_units with a
        BOOTSTRAP recovery hint — telling the operator to ``kickstart`` a job that
        is not registered (which cannot work) is the bug this route fixes."""
        rec = _fleet(
            monkeypatch, tmp_path,
            labels=[CURRENT, SIBLING],
            located={CURRENT: (f"gui/{UID}", 100), SIBLING: (f"user/{UID}", 200)},
            sibling_homes={SIBLING: tmp_path / "root" / "profiles" / "sib"},
            refresh_result=gw.REFRESH_PLIST_FAILED_TO_REGISTER,
            bootstrap_error=OSError("launchctl bootstrap failed: 5"),
        )
        restarted, failed = [], []
        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert failed == [SIBLING]
        assert restarted == [CURRENT]
        assert rec.waits == []  # never claimed supervision


class TestSiblingDrainTargetsTheGateway:
    def test_drain_targets_the_socket_gateway_not_the_supervised_wrapper(
        self, monkeypatch, tmp_path
    ):
        """The plist's supervised process is the osascript wrapper; the socket
        answer for the sibling's home is the actual gateway. SIGUSR1 goes to the
        gateway — the wrapper exits with its child and KeepAlive respawns the job
        on the new code."""
        sibling_home = tmp_path / "root" / "profiles" / "sib"
        rec = _fleet(
            monkeypatch, tmp_path,
            labels=[CURRENT, SIBLING],
            located={CURRENT: (f"gui/{UID}", 100), SIBLING: (f"user/{UID}", 200)},
            sibling_homes={SIBLING: sibling_home},
            identify_answer={"pid": 777, "supervisor": "launchd"},
            drain_results={777: True},
        )
        restarted, failed = [], []
        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert rec.identifies == [sibling_home.resolve()]
        assert rec.drains == [777]
        # KeepAlive respawn verified against the SUPERVISED pid: that is the pid
        # launchd swaps when the drained gateway takes the wrapper's job with it.
        # The drain pid (the socket gateway) is the WRONG baseline — it exits
        # with the job, so waiting on it would time out on a healthy respawn.
        assert rec.waits == [f"user/{UID}/{SIBLING}"]
        assert rec.wait_old_pids == [200]
        assert 777 not in rec.wait_old_pids
        assert restarted == [CURRENT, SIBLING]
        assert failed == []

    def test_drain_falls_back_to_supervised_pid_when_no_gateway_answers(
        self, monkeypatch, tmp_path
    ):
        """No socket answer (gateway predates the socket, or it is wedged before
        binding): the launchd-supervised PID is the only candidate — exactly the
        pre-fix behavior, kept as the fallback."""
        sibling_home = tmp_path / "root" / "profiles" / "sib"
        rec = _fleet(
            monkeypatch, tmp_path,
            labels=[CURRENT, SIBLING],
            located={CURRENT: (f"gui/{UID}", 100), SIBLING: (f"user/{UID}", 200)},
            sibling_homes={SIBLING: sibling_home},
            identify_answer=None,
            drain_results={200: True},
        )
        restarted, failed = [], []
        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert rec.drains == [200]
        assert restarted == [CURRENT, SIBLING]
        assert failed == []


class TestForeignSiblingBoundary:
    def test_foreign_home_sibling_is_never_touched(self, monkeypatch, tmp_path, capsys):
        """#93349/#41403: a label whose plist pins another install's HERMES_HOME is
        another updater's job — never refreshed, never located, never drained,
        never kickstarted, and not counted as a failure."""
        foreign = tmp_path / "other-install" / ".hermes"
        rec = _fleet(
            monkeypatch, tmp_path,
            labels=[CURRENT, "ai.hermes.gateway"],
            located={},  # KeyError would escape if the loop probed it anyway
            foreign_homes={"ai.hermes.gateway": foreign},
        )
        restarted, failed = [], []
        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert rec.locates == []
        assert rec.refreshes == []
        assert rec.drains == []
        assert rec.kickstarts == []
        assert restarted == [CURRENT]
        assert failed == []
        assert "left alone" in capsys.readouterr().out


class TestHomeScopedRefreshMechanism:
    """The scoped refresh compares/rewrites through the home-scoped plist
    machinery; the ONLY safe way to bind a sibling home in the updater is the
    context-local override (never os.environ — the updater process keeps running
    against the invoking profile, and threads read its env concurrently)."""

    def test_scopes_home_by_contextvar_and_restores_it(self, monkeypatch, tmp_path):
        from hermes_cli import gateway_launchd as launchd
        from hermes_constants import get_hermes_home_override

        sibling_home = tmp_path / "root" / "profiles" / "sib"
        sibling_home.mkdir(parents=True)
        plist = tmp_path / "LaunchAgents" / "ai.hermes.gateway-sib.plist"
        plist.parent.mkdir(parents=True, exist_ok=True)
        plist.write_text("<stale/>", encoding="utf-8")
        env_home_before = os.environ.get("HERMES_HOME")

        monkeypatch.setattr(gw, "get_launchd_plist_path", lambda: plist)
        monkeypatch.setattr(gw, "launchd_plist_is_current", lambda: False)
        seen = {}

        def fake_generate():
            seen["override"] = get_hermes_home_override()
            return "<fresh/>"

        monkeypatch.setattr(gw, "generate_launchd_plist", fake_generate)
        monkeypatch.setattr(gw, "_refuse_temp_home_service_write", lambda *a: False)
        monkeypatch.setattr(gw, "_prepare_service_launcher", lambda **k: None)
        monkeypatch.setattr("gateway.status.get_running_pid", lambda *a, **k: None)
        monkeypatch.setattr(gw, "_retry_launchctl_bootstrap_until_registered", lambda *a, **k: True)
        launchctl_calls = []
        monkeypatch.setattr(
            launchd.subprocess, "run",
            lambda cmd, **kw: launchctl_calls.append(cmd)
            or SimpleNamespace(returncode=0, stdout="", stderr=""))

        assert gw.refresh_launchd_plist_for_label(
            "ai.hermes.gateway-sib", sibling_home, domain=f"gui/{UID}") == gw.REFRESH_PLIST_RELOADED

        # The comparison/generation ran with the SIBLING's home bound…
        assert seen["override"] == str(sibling_home)
        # …the plist was rewritten…
        assert plist.read_text(encoding="utf-8") == "<fresh/>"
        # …launchd was reloaded in the domain the caller located, not the cached one…
        assert launchctl_calls[0] == ["launchctl", "bootout", f"gui/{UID}/ai.hermes.gateway-sib"]
        # …and the process environment was never touched (updater scope survives).
        assert os.environ.get("HERMES_HOME") == env_home_before
        assert get_hermes_home_override() is None

    def test_label_mismatch_refreshes_nothing(self, monkeypatch, tmp_path):
        """A plist whose pinned home derives a DIFFERENT service name than ``label``
        disagrees with the profile layout; rewriting the derived path would edit the
        wrong job's definition, so the label is left to the ordinary restart."""
        sibling_home = tmp_path / "root" / "profiles" / "sib"
        sibling_home.mkdir(parents=True)
        plist = tmp_path / "LaunchAgents" / "ai.hermes.gateway-sib.plist"
        plist.parent.mkdir(parents=True, exist_ok=True)
        plist.write_text("<stale/>", encoding="utf-8")
        monkeypatch.setattr(gw, "get_launchd_plist_path", lambda: plist)
        monkeypatch.setattr("gateway.status.get_running_pid", lambda *a, **k: None)
        monkeypatch.setattr(
            gw, "_retry_launchctl_bootstrap_until_registered",
            lambda *a, **k: pytest.fail("no bootstrap for a mismatched label"))

        assert gw.refresh_launchd_plist_for_label(
            "ai.hermes.gateway-other", sibling_home, domain=f"gui/{UID}") == gw.REFRESH_PLIST_NO_CHANGE
        assert plist.read_text(encoding="utf-8") == "<stale/>"

    def test_current_plist_is_not_rewritten_or_reloaded(self, monkeypatch, tmp_path):
        """Refresh is a no-op (False, no launchctl) when the installed plist already
        matches the generated one — the ordinary drain + kickstart flow continues."""
        sibling_home = tmp_path / "root" / "profiles" / "sib"
        sibling_home.mkdir(parents=True)
        plist = tmp_path / "LaunchAgents" / "ai.hermes.gateway-sib.plist"
        plist.parent.mkdir(parents=True, exist_ok=True)
        plist.write_text("<current/>", encoding="utf-8")
        monkeypatch.setattr(gw, "get_launchd_plist_path", lambda: plist)
        monkeypatch.setattr(gw, "launchd_plist_is_current", lambda: True)
        monkeypatch.setattr("gateway.status.get_running_pid", lambda *a, **k: None)
        calls = []
        from hermes_cli import gateway_launchd as launchd
        monkeypatch.setattr(
            launchd.subprocess, "run", lambda cmd, **kw: calls.append(cmd))

        assert gw.refresh_launchd_plist_for_label(
            "ai.hermes.gateway-sib", sibling_home, domain=f"gui/{UID}") == gw.REFRESH_PLIST_NO_CHANGE
        assert plist.read_text(encoding="utf-8") == "<current/>"
        assert calls == []

    def test_failed_rebootstrap_reports_failed_to_register(self, monkeypatch, tmp_path):
        """The reload shape the sibling loop must route to bootstrap revival: plist
        rewritten, job booted out, bootstrap retries exhausted → the distinct
        FAILED_TO_REGISTER outcome (kickstart -k cannot work on that job)."""
        from hermes_cli import gateway_launchd as launchd

        sibling_home = tmp_path / "root" / "profiles" / "sib"
        sibling_home.mkdir(parents=True)
        plist = tmp_path / "LaunchAgents" / "ai.hermes.gateway-sib.plist"
        plist.parent.mkdir(parents=True, exist_ok=True)
        plist.write_text("<stale/>", encoding="utf-8")
        monkeypatch.setattr(gw, "get_launchd_plist_path", lambda: plist)
        monkeypatch.setattr(gw, "launchd_plist_is_current", lambda: False)
        monkeypatch.setattr(gw, "generate_launchd_plist", lambda: "<fresh/>")
        monkeypatch.setattr(gw, "_refuse_temp_home_service_write", lambda *a: False)
        monkeypatch.setattr(gw, "_prepare_service_launcher", lambda **k: None)
        monkeypatch.setattr(
            gw, "_retry_launchctl_bootstrap_until_registered", lambda *a, **k: False)
        monkeypatch.setattr(
            launchd.subprocess, "run",
            lambda cmd, **kw: SimpleNamespace(returncode=0, stdout="", stderr=""))

        assert gw.refresh_launchd_plist_for_label(
            "ai.hermes.gateway-sib", sibling_home, domain=f"gui/{UID}") == gw.REFRESH_PLIST_FAILED_TO_REGISTER
        # The rewritten plist survives: bootstrap revival reloads the NEW definition.
        assert plist.read_text(encoding="utf-8") == "<fresh/>"
