"""Regression tests for #126883 — the macOS sibling launchd restart pass.

Two defects, same code path (``_restart_macos_launchd_gateways``):

Defect 1: the sibling loop kickstarted each label without refreshing its
launchd definition, so a plist generated by an OLD checkout (no
``HERMES_SUPERVISED_CHILD``, unconditional ``KeepAlive=true``) was revived
as-is after every update; the fresh child hit the multiplexer guard's
exit-78 refusal in a KeepAlive respawn loop, no gateway bound a socket,
and the fleet verification failed the whole update with exit 1. The
invoking label's path already enforces refresh-before-restart; siblings
now get the same invariant, evaluated under the HERMES_HOME their plist
pins.

Defect 2: the drain signaled the launchctl-supervised PID, which under
the current template is the osascript wrapper — not the gateway child.
The wrapper died on SIGUSR1, the real gateway survived on pre-update
code holding the socket, and the fresh-PID wait misread the wrapper's
death as a completed restart. Siblings now drain the state-file gateway
PID (liveness-checked), falling back to the supervised PID only when no
live gateway process answers.
"""

from __future__ import annotations

import plistlib
from types import SimpleNamespace

import pytest

import hermes_cli.gateway as gw
import hermes_cli.update_cmd_fleet as fleet
from hermes_cli.update_cmd import (
    _launchd_label_pinned_home,
    _launchd_real_gateway_pid,
    _refresh_sibling_launchd_plist,
    _restart_macos_launchd_gateways,
)


pytestmark = pytest.mark.platforms("macos")  # launchd fleet restart is macOS-only; helpers use POSIX os.getuid

UID = 501


def _write_pinned_plist(agents_dir, label: str, hermes_home) -> None:
    agents_dir.mkdir(parents=True, exist_ok=True)
    data = {
        "Label": label,
        "ProgramArguments": ["/bin/true"],
        "EnvironmentVariables": {"HERMES_HOME": str(hermes_home)},
    }
    (agents_dir / f"{label}.plist").write_bytes(plistlib.dumps(data))


def _fake_launchd_account(monkeypatch, tmp_path):
    """Point the real-account-home lookup (pwd.getpwuid) at a tmp home; return its LaunchAgents dir."""
    import pwd as pwd_module

    monkeypatch.setattr(
        pwd_module, "getpwuid", lambda _uid: SimpleNamespace(pw_dir=str(tmp_path))
    )
    return tmp_path / "Library" / "LaunchAgents"


class TestLaunchdLabelPinnedHome:
    def test_reads_the_pinned_hermes_home(self, monkeypatch, tmp_path):
        agents = _fake_launchd_account(monkeypatch, tmp_path)
        home = tmp_path / "hermes-root" / "profiles" / "ops"
        _write_pinned_plist(agents, "ai.hermes.gateway-ops", home)
        assert _launchd_label_pinned_home("ai.hermes.gateway-ops") == str(home)

    def test_missing_or_unreadable_plist_is_none(self, monkeypatch, tmp_path):
        agents = _fake_launchd_account(monkeypatch, tmp_path)
        assert _launchd_label_pinned_home("ai.hermes.gateway-absent") is None
        agents.mkdir(parents=True, exist_ok=True)
        broken = agents / "ai.hermes.gateway-broken.plist"
        broken.write_text("junk")
        assert _launchd_label_pinned_home("ai.hermes.gateway-broken") is None


class TestRefreshSiblingLaunchdPlist:
    def test_restores_hermes_home_on_every_path(self, monkeypatch, tmp_path):
        """The env switch is verified and restored — a refresh that cannot resolve
        to the sibling home aborts BEFORE any write, and the caller's environment
        comes back exactly as it was."""
        monkeypatch.setenv("HERMES_HOME", str(tmp_path / "caller-home"))
        # Force the verification to fail: get_hermes_home returns something else.
        import hermes_constants

        monkeypatch.setattr(
            hermes_constants, "get_hermes_home", lambda: tmp_path / "somewhere-else"
        )
        rewritten = []
        monkeypatch.setattr(
            gw, "refresh_launchd_plist_if_needed", lambda: rewritten.append(1) or True
        )

        assert _refresh_sibling_launchd_plist(str(tmp_path / "sibling-home")) is False
        assert rewritten == []  # never wrote in an unverified context
        import os

        assert os.environ.get("HERMES_HOME") == str(tmp_path / "caller-home")

    def test_current_plist_is_a_noop(self, monkeypatch, tmp_path):
        monkeypatch.setenv("HERMES_HOME", str(tmp_path / "sibling-home"))
        import hermes_constants

        monkeypatch.setattr(
            hermes_constants, "get_hermes_home", lambda: tmp_path / "sibling-home"
        )
        monkeypatch.setattr(gw, "launchd_plist_is_current", lambda: True)
        rewritten = []
        monkeypatch.setattr(
            gw, "refresh_launchd_plist_if_needed", lambda: rewritten.append(1) or True
        )

        assert _refresh_sibling_launchd_plist(str(tmp_path / "sibling-home")) is False
        assert rewritten == []

    def test_stale_plist_is_refreshed_under_the_sibling_home(self, monkeypatch, tmp_path):
        seen = {}
        import hermes_constants
        import os

        real_get = hermes_constants.get_hermes_home

        def spy_get():
            seen["home"] = os.environ.get("HERMES_HOME")
            return real_get()

        monkeypatch.setattr(hermes_constants, "get_hermes_home", spy_get)
        monkeypatch.setattr(gw, "launchd_plist_is_current", lambda: False)
        calls = []
        monkeypatch.setattr(
            gw, "refresh_launchd_plist_if_needed", lambda: calls.append(1) or True
        )

        assert _refresh_sibling_launchd_plist(str(tmp_path / "sibling-home")) is True
        assert calls == [1]
        # The refresh ran with the sibling home active in the environment.
        assert seen["home"] == str(tmp_path / "sibling-home")


class TestLaunchdRealGatewayPid:
    def test_returns_the_liveness_checked_state_file_pid(self, monkeypatch, tmp_path):
        home = tmp_path / "sibling-home"
        home.mkdir()
        (home / "gateway_state.json").write_text('{"pid": 4242}')
        import gateway.status as status

        monkeypatch.setattr(status, "_pid_exists", lambda pid: pid == 4242)
        monkeypatch.setattr(status, "read_runtime_status", lambda path: {"pid": 4242})
        assert _launchd_real_gateway_pid(str(home)) == 4242

    def test_dead_or_missing_gateway_is_none(self, monkeypatch, tmp_path):
        import gateway.status as status

        monkeypatch.setattr(status, "_pid_exists", lambda pid: False)
        monkeypatch.setattr(status, "read_runtime_status", lambda path: None)
        assert _launchd_real_gateway_pid(str(tmp_path / "no-such-home")) is None


class TestSiblingRestartUsesRealGatewayAndRefresh:
    def _fleet_with_pinned_home(
        self, monkeypatch, tmp_path, *, state_pid, supervised_pid
    ):
        """A two-label fleet whose sibling plist pins a real home directory."""
        agents = _fake_launchd_account(monkeypatch, tmp_path)
        sibling_home = tmp_path / "hermes-root" / "profiles" / "ops"
        sibling_home.mkdir(parents=True)
        label = "ai.hermes.gateway-ops"
        _write_pinned_plist(agents, label, sibling_home)

        current = "ai.hermes.gateway"
        monkeypatch.setattr(gw, "get_launchd_label", lambda: current)
        monkeypatch.setattr(
            gw,
            "get_launchd_plist_path",
            lambda: agents / f"{current}.plist",
        )
        monkeypatch.setattr(
            gw, "launchd_gateway_labels_for_install", lambda: [current, label]
        )
        monkeypatch.setattr(gw, "legacy_launchd_labels_for_install", lambda exclude=(): [])
        # The sibling home is one of this update's own profile homes (else the
        # #93349 foreign-home guard would — correctly — leave the label alone).
        import hermes_cli.update_fleet_scope as scope

        monkeypatch.setattr(
            scope, "update_scope_homes", lambda: {sibling_home.resolve()}
        )
        monkeypatch.setattr(
            gw,
            "_locate_launchd_gateway_service",
            lambda lbl: (f"gui/{UID}", supervised_pid) if lbl == label else (None, None),
        )
        rec = {"drains": [], "kickstarts": []}
        drained = []
        monkeypatch.setattr(
            gw,
            "_graceful_restart_via_sigusr1",
            lambda pid, drain_timeout, **_: drained.append(pid) or True,
        )
        monkeypatch.setattr(
            gw,
            "_launchd_kickstart",
            lambda lbl, domain: rec["kickstarts"].append(f"{domain}/{lbl}"),
        )
        monkeypatch.setattr(
            gw,
            "_wait_for_launchd_service_pid",
            lambda lbl, old_pid, timeout, domain: rec.setdefault(
                "waits", []
            ).append(f"{domain}/{lbl}")
            or True,
        )
        monkeypatch.setattr(gw, "launchd_restart", lambda: None)
        monkeypatch.setattr(
            gw, "wait_for_launchd_gateway_supervision", lambda **kw: True
        )
        # Refresh is a no-op stub: this test isolates the DRAIN-target selection.
        refreshed = []
        monkeypatch.setattr(
            fleet, "_refresh_sibling_launchd_plist", lambda home: refreshed.append(home) or False
        )
        # State file knows the real gateway child.
        if state_pid is not None:
            (sibling_home / "gateway_state.json").write_text(f'{{"pid": {state_pid}}}')
        import gateway.status as status

        monkeypatch.setattr(status, "_pid_exists", lambda pid: pid == state_pid)
        monkeypatch.setattr(
            status, "read_runtime_status", lambda path: {"pid": state_pid}
        )
        return drained, refreshed, rec

    def test_drains_the_real_gateway_child_not_the_wrapper(
        self, monkeypatch, tmp_path
    ):
        """#126883 defect 2: the supervised PID is the osascript wrapper; the
        drain must hit the state-file gateway PID instead."""
        drained, _refreshed, rec = self._fleet_with_pinned_home(
            monkeypatch, tmp_path, state_pid=4242, supervised_pid=111
        )
        restarted: list[str] = []
        failed: list[str] = []

        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert drained == [4242]  # the child, never the wrapper (111)
        assert rec["kickstarts"] == []
        assert restarted == ["ai.hermes.gateway-ops"]

    def test_falls_back_to_supervised_pid_without_a_live_gateway(
        self, monkeypatch, tmp_path
    ):
        """No live gateway process answers → the supervised PID remains the
        only drain target (previous behavior preserved)."""
        drained, _refreshed, rec = self._fleet_with_pinned_home(
            monkeypatch, tmp_path, state_pid=None, supervised_pid=111
        )
        restarted: list[str] = []
        failed: list[str] = []

        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert drained == [111]
        assert restarted == ["ai.hermes.gateway-ops"]

    def test_refreshes_the_sibling_definition_before_restart(
        self, monkeypatch, tmp_path
    ):
        """#126883 defect 1: each sibling's pinned home is handed to the
        refresh before the label is restarted."""
        _drained, refreshed, _rec = self._fleet_with_pinned_home(
            monkeypatch, tmp_path, state_pid=4242, supervised_pid=111
        )
        restarted: list[str] = []
        failed: list[str] = []

        _restart_macos_launchd_gateways(restarted, failed, drain_budget=0.0)

        assert len(refreshed) == 1
        assert refreshed[0].endswith("profiles/ops")
