"""Architect mode -- generate implementation plans before coding.

Provides a structured planning step that creates a detailed implementation
plan (in markdown) which is then injected into the conversation for the
regular agent to follow.
"""

import logging
import os
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# System prompt for architect mode
# ---------------------------------------------------------------------------

ARCHITECT_SYSTEM_PROMPT = """\
You are an expert software architect. Your role is to create detailed \
implementation plans -- NOT to write code.

When given a task or feature request, produce a structured markdown plan that \
covers:

## 1. Overview
A concise summary of what needs to be built and why.

## 2. Files to Create or Modify
For each file, specify:
- Full file path
- Whether it is new or existing
- What changes are needed (functions, classes, imports)

## 3. Functions and Classes
For each new or modified function/class:
- Name and signature
- Brief description of its purpose
- Input/output types
- Key logic or algorithm notes

## 4. Step-by-Step Implementation Order
Number each step. Group related changes together. Indicate dependencies \
between steps.

## 5. Edge Cases and Error Handling
List potential edge cases, error conditions, and how they should be handled.

## 6. Testing Strategy
Describe what tests should be written and what they should verify.

RULES:
- Do NOT write actual code. Describe what the code should do.
- Be specific about file paths, function names, and types.
- Keep the plan actionable -- an experienced developer should be able to \
implement it without ambiguity.
- If the task is unclear, state your assumptions explicitly.
"""


# ---------------------------------------------------------------------------
# Run architect
# ---------------------------------------------------------------------------

def run_architect(
    prompt: str,
    model: Optional[str] = None,
    provider: Optional[str] = None,
) -> str:
    """Generate an implementation plan for the given *prompt*.

    Uses the auxiliary client infrastructure to call an LLM with the
    architect system prompt. Falls back to a simpler approach if no
    LLM client is available.

    Parameters
    ----------
    prompt : str
        The user's feature request or task description.
    model : str, optional
        Override the model to use. Defaults to the auxiliary client's default.
    provider : str, optional
        Override the provider to use.

    Returns
    -------
    str
        The implementation plan in markdown format.
    """
    try:
        from agent.auxiliary_client import get_auxiliary_client

        client_info = get_auxiliary_client(
            task="architect",
            provider_override=provider,
            model_override=model,
        )
        if client_info is None:
            logger.warning("No auxiliary client available for architect mode")
            return _fallback_plan(prompt)

        client = client_info.client
        model_name = client_info.model

        response = client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": ARCHITECT_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            max_tokens=4096,
            temperature=0.3,
        )

        plan = response.choices[0].message.content
        if not plan:
            return _fallback_plan(prompt)
        return plan

    except Exception as e:
        logger.warning("Architect mode LLM call failed: %s", e)
        return _fallback_plan(prompt)


def _fallback_plan(prompt: str) -> str:
    """Generate a minimal plan template when no LLM is available."""
    return f"""\
# Implementation Plan

## Task
{prompt}

## Steps
1. Analyze the requirements described above
2. Identify files to create or modify
3. Implement changes incrementally
4. Add tests for new functionality
5. Run tests and fix any issues

*Note: Detailed plan generation requires an LLM backend. \
This is a fallback template -- please elaborate on the steps above.*
"""


def format_architect_context(plan: str, original_prompt: str) -> str:
    """Format an architect plan for injection into the conversation.

    Returns a string suitable for adding as a system/context message.
    """
    return (
        f"The following implementation plan was generated by architect mode "
        f"for the user's request. Follow this plan closely:\n\n"
        f"--- ARCHITECT PLAN ---\n{plan}\n--- END PLAN ---\n\n"
        f"Original request: {original_prompt}\n\n"
        f"Now implement the plan step by step. Write the actual code."
    )
