"""Exact-environment Claude CLI launcher and Max-plan attestation."""

from __future__ import annotations

import hashlib
import json
import os
import shlex
import subprocess
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping


@dataclass(frozen=True)
class ClaudeMaxAttestation:
    auth_method: str
    api_provider: str
    subscription_type: str
    checked_at: float
    account_key: str

    @property
    def included_usage(self) -> bool:
        return (
            self.auth_method == "claude.ai"
            and self.api_provider == "firstParty"
            and self.subscription_type == "max"
        )


_ATTESTATION_CACHE: dict[str, ClaudeMaxAttestation] = {}
_ATTESTATION_LOCK = threading.Lock()


def create_exact_env_cli_wrapper(
    real_cli: str | Path,
    exact_env: Mapping[str, str],
    wrapper_dir: str | Path,
    *,
    sandbox_profile: str | None = None,
) -> Path:
    """Create a 0700 launcher that execs the CLI through ``env -i``.

    ``ClaudeAgentOptions.env`` is only an overlay on the SDK parent's ambient
    environment. Pointing the SDK at this launcher via its public ``cli_path``
    option ensures the *actual* Claude CLI is a second process with an exact
    allowlisted environment, without mutating the Hermes process environment.
    """

    if os.name != "posix":
        raise RuntimeError("Exact Claude CLI environment is unsupported on this OS")
    real_path = Path(real_cli).expanduser().resolve()
    if not real_path.is_file():
        raise RuntimeError(f"Claude CLI does not exist: {real_path}")
    env_items = sorted((str(key), str(value)) for key, value in exact_env.items())
    digest = hashlib.sha256(
        json.dumps(
            [str(real_path), env_items, sandbox_profile], separators=(",", ":")
        ).encode()
    ).hexdigest()[:20]
    directory = Path(wrapper_dir).expanduser()
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    directory.chmod(0o700)
    wrapper = directory / f"claude-exact-env-{digest}"
    assignments = " ".join(
        f"{key}={shlex.quote(value)}" for key, value in env_items
    )
    command = shlex.quote(str(real_path))
    if sandbox_profile is not None:
        command = (
            "/usr/bin/sandbox-exec -p "
            f"{shlex.quote(sandbox_profile)} {command}"
        )
    content = (
        "#!/bin/sh\n"
        "# Generated by Hermes Agent; contains no provider credentials.\n"
        f"exec /usr/bin/env -i {assignments} {command} \"$@\"\n"
    )
    try:
        if wrapper.read_text(encoding="utf-8") == content:
            wrapper.chmod(0o700)
            return wrapper
    except OSError:
        pass
    temporary = directory / f".{wrapper.name}.{os.getpid()}.tmp"
    temporary.write_text(content, encoding="utf-8")
    temporary.chmod(0o700)
    os.replace(temporary, wrapper)
    wrapper.chmod(0o700)
    return wrapper


def invalidate_claude_auth_attestation(cli_wrapper: str | Path) -> None:
    with _ATTESTATION_LOCK:
        _ATTESTATION_CACHE.pop(str(Path(cli_wrapper).resolve()), None)


def attest_claude_max_auth(
    cli_wrapper: str | Path,
    *,
    cache_ttl_seconds: float = 60,
) -> ClaudeMaxAttestation:
    """Require same-binary, same-environment first-party Max authentication."""

    wrapper = Path(cli_wrapper).resolve()
    key = str(wrapper)
    now = time.time()
    with _ATTESTATION_LOCK:
        cached = _ATTESTATION_CACHE.get(key)
        if cached and now - cached.checked_at < cache_ttl_seconds:
            return cached
    try:
        result = subprocess.run(
            [str(wrapper), "auth", "status"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        payload = json.loads(result.stdout) if result.returncode == 0 else {}
    except Exception as exc:
        invalidate_claude_auth_attestation(wrapper)
        raise RuntimeError(f"Claude Max attestation failed: {exc}") from exc
    required = {
        "loggedIn": True,
        "authMethod": "claude.ai",
        "apiProvider": "firstParty",
        "subscriptionType": "max",
    }
    if any(payload.get(field) != expected for field, expected in required.items()):
        invalidate_claude_auth_attestation(wrapper)
        raise RuntimeError(
            "Claude Max attestation failed: exact-environment CLI is not "
            "logged into a first-party Max subscription"
        )
    attestation = ClaudeMaxAttestation(
        auth_method="claude.ai",
        api_provider="firstParty",
        subscription_type="max",
        checked_at=now,
        account_key=hashlib.sha256(
            str(
                payload.get("accountUuid")
                or payload.get("email")
                or wrapper
            ).encode("utf-8")
        ).hexdigest()[:24],
    )
    with _ATTESTATION_LOCK:
        _ATTESTATION_CACHE[key] = attestation
    return attestation


__all__ = [
    "ClaudeMaxAttestation",
    "attest_claude_max_auth",
    "create_exact_env_cli_wrapper",
    "invalidate_claude_auth_attestation",
]
