"""Minimal trusted elevated launcher for terminal_tool's elevated path.

This helper is executed by the ADMIN process after ``ShellExecuteExW(..., "runas")``
elevates it.  It deliberately does almost nothing on its own, and every
privileged action is bound to the specific launch:

Security properties (round-7):

1. **No executable-search hijack.**  The shell is resolved via
   ``GetSystemDirectoryW`` and passed as the ABSOLUTE ``lpApplicationName``;
   a fake ``cmd.exe`` dropped in the working directory (or anywhere on PATH)
   can never be executed with administrator privileges.  ``PATH``,
   ``COMSPEC`` and the request environment are never trusted to locate the
   shell.

2. **No request TOCTOU.**  The command / cwd / sanitized env arrive over a
   framed named-pipe control protocol (``tools.elevated_protocol.py``) whose
   nonce was generated by the parent before launch and whose client PID was
   verified against the elevated process handle.  A user-writable
   ``request.json`` is no longer read, so nothing can be tampered with after
   the guard approved the command.

3. **No arbitrary file writes.**  The helper never creates, overwrites or
   truncates files for medium-integrity-controlled paths.  stdout/stderr
   stream back to the parent over a separate output named pipe; the exit
   code and status travel on the control pipe.

4. **Job object truthfulness.**  Job creation / ``KILL_ON_JOB_CLOSE`` /
   child assignment are checked step by step; ``job_bound`` is only reported
   when ALL of them succeeded.  Timeout termination claims a terminated tree
   only after the job was terminated and the child verified dead.

5. **Handle allowlist.**  The elevated child is created with
   ``STARTUPINFOEXW`` + ``PROC_THREAD_ATTRIBUTE_HANDLE_LIST`` containing ONLY
   the stdout/stderr handles; sockets, tokens, files, pipes and the job
   handle are never inherited.
"""

from __future__ import annotations

import ctypes
import os
import sys
import threading
import time
from ctypes import wintypes

# The helper is launched directly (ShellExecuteExW -> python.exe
# tools/elevated_helper.py), so sys.path[0] is the tools/ directory, not the
# repo root.  Make the repo root importable so `from tools.elevated_protocol
# import ...` works exactly like the parent process.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from tools.elevated_protocol import (
    KIND_CANCELLED,
    KIND_CONNECTED,
    KIND_DONE,
    KIND_READY,
    PROTOCOL_VERSION,
    ProtocolError,
    pack_message,
    unpack_frame,
    validate_parent_message,
)

# --- Windows constants ------------------------------------------------------

CREATE_UNICODE_ENVIRONMENT = 0x00000400
CREATE_NO_WINDOW = 0x08000000
CREATE_SUSPENDED = 0x00000004
STARTF_USESTDHANDLES = 0x00000100
HANDLE_FLAG_INHERIT = 0x00000001
STILL_ACTIVE = 259
INFINITE = 0xFFFFFFFF
INVALID_HANDLE_VALUE = 0xFFFFFFFF

GENERIC_READ = 0x80000000
GENERIC_WRITE = 0x40000000
OPEN_EXISTING = 3
FILE_FLAG_FIRST_PIPE_INSTANCE = 0x00080000

PIPE_ACCESS_DUPLEX = 0x00000003
PIPE_TYPE_MESSAGE = 0x00000004
PIPE_READMODE_MESSAGE = 0x00000002
PIPE_WAIT = 0x00000000

PROC_THREAD_ATTRIBUTE_HANDLE_LIST = 0x00020002

JobObjectExtendedLimitInformation = 9
JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE = 0x00002000

# Maximum time (ms) the helper waits for the parent's request after
# connecting.  The UAC prompt can keep the helper idle; once the helper is
# actually running the parent connects within moments.
_REQUEST_WAIT_MS = 30_000


# --- Structures -------------------------------------------------------------


class _STARTUPINFOW(ctypes.Structure):
    _fields_ = [
        ("cb", wintypes.DWORD),
        ("lpReserved", wintypes.LPWSTR),
        ("lpDesktop", wintypes.LPWSTR),
        ("lpTitle", wintypes.LPWSTR),
        ("dwX", wintypes.DWORD),
        ("dwY", wintypes.DWORD),
        ("dwXSize", wintypes.DWORD),
        ("dwYSize", wintypes.DWORD),
        ("dwXCountChars", wintypes.DWORD),
        ("dwYCountChars", wintypes.DWORD),
        ("dwFillAttribute", wintypes.DWORD),
        ("dwFlags", wintypes.DWORD),
        ("wShowWindow", wintypes.WORD),
        ("cbReserved2", wintypes.WORD),
        ("lpReserved2", ctypes.POINTER(ctypes.c_byte)),
        ("hStdInput", wintypes.HANDLE),
        ("hStdOutput", wintypes.HANDLE),
        ("hStdError", wintypes.HANDLE),
    ]


class _PROCESS_INFORMATION(ctypes.Structure):
    _fields_ = [
        ("hProcess", wintypes.HANDLE),
        ("hThread", wintypes.HANDLE),
        ("dwProcessId", wintypes.DWORD),
        ("dwThreadId", wintypes.DWORD),
    ]


class _STARTUPINFOEXW(ctypes.Structure):
    _fields_ = [
        ("StartupInfo", _STARTUPINFOW),
        ("lpAttributeList", ctypes.c_void_p),
    ]


class _SECURITY_ATTRIBUTES(ctypes.Structure):
    _fields_ = [
        ("nLength", wintypes.DWORD),
        ("lpSecurityDescriptor", ctypes.c_void_p),
        ("bInheritHandle", wintypes.BOOL),
    ]


class _IO_COUNTERS(ctypes.Structure):
    _fields_ = [
        ("ReadOperationCount", ctypes.c_ulonglong),
        ("WriteOperationCount", ctypes.c_ulonglong),
        ("OtherOperationCount", ctypes.c_ulonglong),
        ("ReadTransferCount", ctypes.c_ulonglong),
        ("WriteTransferCount", ctypes.c_ulonglong),
        ("OtherTransferCount", ctypes.c_ulonglong),
    ]


class _JOBOBJECT_BASIC_LIMIT_INFORMATION(ctypes.Structure):
    _fields_ = [
        ("PerProcessUserTimeLimit", wintypes.LARGE_INTEGER),
        ("PerJobUserTimeLimit", wintypes.LARGE_INTEGER),
        ("LimitFlags", wintypes.DWORD),
        ("MinimumWorkingSetSize", ctypes.c_size_t),
        ("MaximumWorkingSetSize", ctypes.c_size_t),
        ("ActiveProcessLimit", wintypes.DWORD),
        ("Affinity", ctypes.c_ulonglong),
        ("PriorityClass", wintypes.DWORD),
        ("SchedulingClass", wintypes.DWORD),
    ]


class _JOBOBJECT_EXTENDED_LIMIT_INFORMATION(ctypes.Structure):
    _fields_ = [
        ("BasicLimitInformation", _JOBOBJECT_BASIC_LIMIT_INFORMATION),
        ("IoInfo", _IO_COUNTERS),
        ("ProcessMemoryLimit", ctypes.c_size_t),
        ("JobMemoryLimit", ctypes.c_size_t),
        ("PeakProcessMemoryUsed", ctypes.c_size_t),
        ("PeakJobMemoryUsed", ctypes.c_size_t),
    ]


def _kernel32():
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)

    kernel32.GetSystemDirectoryW.argtypes = [wintypes.LPWSTR, wintypes.UINT]
    kernel32.GetSystemDirectoryW.restype = wintypes.UINT

    kernel32.CreateNamedPipeW.argtypes = [
        wintypes.LPCWSTR,
        wintypes.DWORD,
        wintypes.DWORD,
        wintypes.DWORD,
        wintypes.DWORD,
        wintypes.DWORD,
        wintypes.DWORD,
        ctypes.c_void_p,
    ]
    kernel32.CreateNamedPipeW.restype = wintypes.HANDLE

    kernel32.ConnectNamedPipe.argtypes = [wintypes.HANDLE, ctypes.c_void_p]
    kernel32.ConnectNamedPipe.restype = wintypes.BOOL

    kernel32.CreateFileW.argtypes = [
        wintypes.LPCWSTR,
        wintypes.DWORD,
        wintypes.DWORD,
        ctypes.c_void_p,
        wintypes.DWORD,
        wintypes.DWORD,
        wintypes.HANDLE,
    ]
    kernel32.CreateFileW.restype = wintypes.HANDLE

    kernel32.PeekNamedPipe.argtypes = [
        wintypes.HANDLE,
        ctypes.c_void_p,
        wintypes.DWORD,
        ctypes.POINTER(wintypes.DWORD),
        ctypes.POINTER(wintypes.DWORD),
        ctypes.POINTER(wintypes.DWORD),
    ]
    kernel32.PeekNamedPipe.restype = wintypes.BOOL

    kernel32.ReadFile.argtypes = [
        wintypes.HANDLE,
        ctypes.c_void_p,
        wintypes.DWORD,
        ctypes.POINTER(wintypes.DWORD),
        ctypes.c_void_p,
    ]
    kernel32.ReadFile.restype = wintypes.BOOL

    kernel32.WriteFile.argtypes = [
        wintypes.HANDLE,
        ctypes.c_void_p,
        wintypes.DWORD,
        ctypes.POINTER(wintypes.DWORD),
        ctypes.c_void_p,
    ]
    kernel32.WriteFile.restype = wintypes.BOOL

    kernel32.FlushFileBuffers.argtypes = [wintypes.HANDLE]
    kernel32.FlushFileBuffers.restype = wintypes.BOOL

    kernel32.CreateProcessW.argtypes = [
        wintypes.LPCWSTR,
        wintypes.LPWSTR,
        ctypes.c_void_p,
        ctypes.c_void_p,
        wintypes.BOOL,
        wintypes.DWORD,
        ctypes.c_void_p,
        wintypes.LPCWSTR,
        ctypes.POINTER(_STARTUPINFOEXW),
        ctypes.POINTER(_PROCESS_INFORMATION),
    ]
    kernel32.CreateProcessW.restype = wintypes.BOOL

    kernel32.InitializeProcThreadAttributeList.argtypes = [
        ctypes.c_void_p,
        wintypes.DWORD,
        wintypes.DWORD,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    kernel32.InitializeProcThreadAttributeList.restype = wintypes.BOOL

    kernel32.UpdateProcThreadAttribute.argtypes = [
        ctypes.c_void_p,
        wintypes.DWORD,
        ctypes.c_ulonglong,
        ctypes.c_void_p,
        ctypes.c_size_t,
        ctypes.c_void_p,
        ctypes.c_void_p,
    ]
    kernel32.UpdateProcThreadAttribute.restype = wintypes.BOOL

    kernel32.DeleteProcThreadAttributeList.argtypes = [ctypes.c_void_p]
    kernel32.DeleteProcThreadAttributeList.restype = None

    kernel32.WaitForSingleObject.argtypes = [wintypes.HANDLE, wintypes.DWORD]
    kernel32.WaitForSingleObject.restype = wintypes.DWORD

    kernel32.CloseHandle.argtypes = [wintypes.HANDLE]
    kernel32.CloseHandle.restype = wintypes.BOOL

    kernel32.GetExitCodeProcess.argtypes = [
        wintypes.HANDLE,
        ctypes.POINTER(wintypes.DWORD),
    ]
    kernel32.GetExitCodeProcess.restype = wintypes.BOOL

    kernel32.SetHandleInformation.argtypes = [
        wintypes.HANDLE,
        wintypes.DWORD,
        wintypes.DWORD,
    ]
    kernel32.SetHandleInformation.restype = wintypes.BOOL

    kernel32.CreateJobObjectW.argtypes = [ctypes.c_void_p, wintypes.LPCWSTR]
    kernel32.CreateJobObjectW.restype = wintypes.HANDLE

    kernel32.AssignProcessToJobObject.argtypes = [
        wintypes.HANDLE,
        wintypes.HANDLE,
    ]
    kernel32.AssignProcessToJobObject.restype = wintypes.BOOL

    kernel32.SetInformationJobObject.argtypes = [
        wintypes.HANDLE,
        ctypes.c_int,
        ctypes.c_void_p,
        wintypes.DWORD,
    ]
    kernel32.SetInformationJobObject.restype = wintypes.BOOL

    kernel32.TerminateJobObject.argtypes = [wintypes.HANDLE, wintypes.UINT]
    kernel32.TerminateJobObject.restype = wintypes.BOOL

    kernel32.ResumeThread.argtypes = [wintypes.HANDLE]
    kernel32.ResumeThread.restype = wintypes.DWORD

    kernel32.GetProcessId.argtypes = [wintypes.HANDLE]
    kernel32.GetProcessId.restype = wintypes.DWORD

    return kernel32


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def system_cmd_path() -> str:
    """Absolute path of the system cmd.exe (never PATH/COMSPEC/cwd)."""
    k32 = _kernel32()
    buf = ctypes.create_unicode_buffer(261)
    n = k32.GetSystemDirectoryW(buf, 261)
    if n == 0 or n >= 261:
        raise OSError("GetSystemDirectoryW failed")
    return os.path.join(buf.value, "cmd.exe")


def _build_env_block(env: dict) -> "ctypes.Array":
    """Build a Windows Unicode environment block from *env*.

    Windows requires the environment block to be sorted case-insensitively
    (CreateProcessW documents this; an unsorted block can mis-behave in
    child ``GetEnvironmentStrings`` enumeration).  Keys containing ``=``
    or a NUL, and values containing a NUL, are invalid on Windows and are
    rejected here (fail closed — never pass a malformed block to the
    elevated child).

    An EMPTY env still produces an explicit, non-None block containing a
    single NUL terminator pair.  Passing ``None`` to CreateProcessW would
    inherit the helper's ADMIN environment, which must never happen: the
    elevated child always receives exactly the scrubbed environment the
    parent approved.
    """
    from tools.elevated_protocol import ProtocolError

    for key, value in env.items():
        if not isinstance(key, str) or not isinstance(value, str):
            raise ProtocolError("env keys/values must be strings")
        if "=" in key:
            raise ProtocolError(f"env key contains '=': {key!r}")
        if "\x00" in key:
            raise ProtocolError("env key contains NUL")
        if "\x00" in value:
            raise ProtocolError(f"env value for {key!r} contains NUL")
    # Windows sorts environment blocks case-insensitively; mirror that so
    # the child sees a well-formed block (CreateProcessW documents the
    # requirement).
    items = sorted(env.items(), key=lambda kv: kv[0].casefold())
    parts = [f"{k}={v}" for k, v in items]
    # "\x00\x00" is the empty block terminator; create_unicode_buffer adds
    # its own trailing NUL, so "\x00" in Python yields "NUL NUL" on disk.
    joined = "\x00".join(parts) + "\x00" if parts else "\x00"
    return ctypes.create_unicode_buffer(joined)


def _read_message(h_pipe: int, k32) -> dict:
    """Read one framed control message from a message-mode pipe.

    Peek the pending message size, cap it, then read the whole message in a
    single ReadFile (message-mode pipes deliver one message per read).
    """
    total = wintypes.DWORD()
    avail = wintypes.DWORD()
    k32.PeekNamedPipe(h_pipe, None, 0, None, ctypes.byref(avail), ctypes.byref(total))
    size = int(total.value)
    if size == 0:
        raise ProtocolError("no message available")
    from tools.elevated_protocol import MAX_MESSAGE_BYTES

    if size > MAX_MESSAGE_BYTES:
        raise ProtocolError(f"message too large: {size}")
    buf = ctypes.create_string_buffer(size)
    nread = wintypes.DWORD()
    if not k32.ReadFile(h_pipe, buf, size, ctypes.byref(nread), None):
        raise ProtocolError(f"pipe read failed (error {ctypes.get_last_error()})")
    message, _consumed = unpack_frame(buf.raw[: int(nread.value)])
    return message


def _write_message(h_pipe: int, message: dict, k32) -> None:
    data = pack_message(message)
    nwritten = wintypes.DWORD()
    buf = ctypes.create_string_buffer(data)
    if not k32.WriteFile(h_pipe, buf, len(data), ctypes.byref(nwritten), None):
        raise OSError(f"pipe write failed (error {ctypes.get_last_error()})")


# ---------------------------------------------------------------------------
# Job object (checked step by step)
# ---------------------------------------------------------------------------


class _JobBinding:
    """Tracks whether the job was created, configured AND assigned.

    ``job_bound`` is only True when all three steps succeeded, so the parent
    never claims a terminated tree on the strength of a half-configured job.
    Each step records a human-readable failure reason for the error message
    when the binding is incomplete.
    """

    def __init__(self) -> None:
        self.handle = None
        self.created = False
        self.limit_set = False
        self.assigned = False
        self.failure_reason: "str | None" = None

    @property
    def job_bound(self) -> bool:
        return self.created and self.limit_set and self.assigned

    def setup(self, k32, child_process: int) -> bool:
        """Create the job, set KILL_ON_JOB_CLOSE, assign the SUSPENDED child.

        Returns True only when ALL three steps succeeded.  On failure the
        partial state remains visible via ``job_bound`` / ``failure_reason``
        so the caller can terminate the still-suspended child and report an
        explicit error.
        """
        job = k32.CreateJobObjectW(None, None)
        if not job:
            self.failure_reason = (
                f"CreateJobObjectW failed (error {ctypes.get_last_error()})"
            )
            return False
        self.handle = job
        self.created = True
        info = _JOBOBJECT_EXTENDED_LIMIT_INFORMATION()
        info.BasicLimitInformation.LimitFlags = JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE
        if not k32.SetInformationJobObject(
            job,
            JobObjectExtendedLimitInformation,
            ctypes.byref(info),
            ctypes.sizeof(info),
        ):
            self.failure_reason = (
                f"SetInformationJobObject failed (error {ctypes.get_last_error()})"
            )
            return False
        self.limit_set = True
        if not k32.AssignProcessToJobObject(job, child_process):
            self.failure_reason = (
                f"AssignProcessToJobObject failed (error {ctypes.get_last_error()})"
            )
            return False
        self.assigned = True
        return True

    def terminate_tree(self, k32, exit_code: int = 1) -> bool:
        if self.handle and self.created:
            return bool(k32.TerminateJobObject(self.handle, exit_code))
        return False

    def close(self, k32) -> None:
        if self.handle:
            k32.CloseHandle(self.handle)
            self.handle = None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def _open_pipe_client(pipe_name: str, k32, desired_access: int) -> int:
    handle = k32.CreateFileW(
        pipe_name,
        desired_access,
        0,  # no sharing
        None,
        OPEN_EXISTING,
        0,
        None,
    )
    if handle in (None, ctypes.c_void_p(-1).value, 0xFFFFFFFFFFFFFFFF):
        raise OSError(
            f"failed to open named pipe {pipe_name} (error {ctypes.get_last_error()})"
        )
    return handle


def _build_handle_list(k32, handles) -> "tuple[ctypes.c_void_p, int]":
    """Create a PROC_THREAD_ATTRIBUTE_HANDLE_LIST attribute list."""
    size = ctypes.c_size_t()
    k32.InitializeProcThreadAttributeList(None, 1, 0, ctypes.byref(size))
    buf = ctypes.create_string_buffer(size.value)
    if not k32.InitializeProcThreadAttributeList(buf, 1, 0, ctypes.byref(size)):
        raise OSError(
            f"InitializeProcThreadAttributeList failed (error {ctypes.get_last_error()})"
        )
    arr = (wintypes.HANDLE * len(handles))(*handles)
    if not k32.UpdateProcThreadAttribute(
        buf,
        0,
        PROC_THREAD_ATTRIBUTE_HANDLE_LIST,
        ctypes.cast(arr, ctypes.c_void_p),
        ctypes.sizeof(arr),
        None,
        None,
    ):
        k32.DeleteProcThreadAttributeList(buf)
        raise OSError(
            f"UpdateProcThreadAttribute failed (error {ctypes.get_last_error()})"
        )
    return buf, 0


def main(argv: "list[str]") -> int:
    # argv: [helper, control_pipe_name, output_pipe_name, nonce]
    if len(argv) < 4:
        return 2
    control_name, output_name, nonce = argv[1], argv[2], argv[3]

    k32 = _kernel32()
    h_control = None
    h_output = None
    job: "_JobBinding | None" = None
    h_cmd = None
    h_cmd_thread = None
    attr_list = None
    cmd_path = None

    try:
        cmd_path = system_cmd_path()

        h_control = _open_pipe_client(control_name, k32, GENERIC_READ | GENERIC_WRITE)
        h_output = _open_pipe_client(output_name, k32, GENERIC_WRITE)
        k32.SetHandleInformation(h_output, HANDLE_FLAG_INHERIT, HANDLE_FLAG_INHERIT)

        # Announce the connection; the parent verifies this client PID before
        # sending anything.  The helper reports its OWN pid (os.getpid());
        # the parent cross-checks it against GetNamedPipeClientProcessId.
        # NOTE: sys.executable on a venv is the venvlauncher shim, so the
        # process handle returned by ShellExecuteExW may be the LAUNCHER's
        # pid while the real helper runs as its child — hence the helper
        # reports the pid that actually opened the pipe.
        _write_message(
            h_control,
            {"kind": KIND_CONNECTED, "v": PROTOCOL_VERSION, "nonce": nonce,
             "pid": os.getpid()},
            k32,
        )

        # Wait for the request (bounded).
        request = None
        deadline = time.monotonic() + _REQUEST_WAIT_MS / 1000.0
        while time.monotonic() < deadline:
            # Peek for a message without blocking forever.
            avail = wintypes.DWORD()
            ok = k32.PeekNamedPipe(h_control, None, 0, None, ctypes.byref(avail), None)
            if ok and int(avail.value) > 0:
                request = _read_message(h_control, k32)
                break
            time.sleep(0.05)
        if request is None:
            _write_message(
                h_control,
                {"kind": KIND_CANCELLED, "v": PROTOCOL_VERSION, "terminated": False,
                 "error": "request timeout"},
                k32,
            )
            return 5
        validate_parent_message(request, nonce)
        command = request["command"]
        cwd = request.get("cwd")
        env = request.get("env") or {}

        # --- create the real command process ------------------------------
        # The shell is the absolute system path; the first command-line token
        # is the same absolute path (Windows quoting rule), then /d /s /c.
        quoted_cmd = '"' + cmd_path + '"'
        cmdline = f"{quoted_cmd} /d /s /c {command}"
        cmd_buf = ctypes.create_unicode_buffer(cmdline)
        env_block = _build_env_block(env)

        # stdout/stderr: the ONLY inheritable handles (STARTUPINFOEXW +
        # handle list).  hStdInput is NULL: elevated commands are non-
        # interactive.
        si_ex = _STARTUPINFOEXW()
        si_ex.StartupInfo.cb = ctypes.sizeof(_STARTUPINFOEXW)
        si_ex.StartupInfo.dwFlags = STARTF_USESTDHANDLES
        si_ex.StartupInfo.hStdInput = None
        si_ex.StartupInfo.hStdOutput = h_output
        si_ex.StartupInfo.hStdError = h_output

        attr_list, _ = _build_handle_list(k32, [h_output, h_output])
        si_ex.lpAttributeList = ctypes.cast(attr_list, ctypes.c_void_p)

        # Create the child SUSPENDED: it must be assigned to the job (with
        # KILL_ON_JOB_CLOSE) BEFORE it runs a single instruction, so a
        # grandchild spawned immediately on startup is still inside the job
        # and dies with the tree on timeout.  The job is created and bound
        # in this window; only then is the thread resumed.
        pi = _PROCESS_INFORMATION()
        ok = k32.CreateProcessW(
            cmd_path,  # lpApplicationName: absolute, never searched
            cmd_buf,
            None,
            None,
            True,  # bInheritHandles: allowlist via PROC_THREAD_ATTRIBUTE_HANDLE_LIST
            CREATE_UNICODE_ENVIRONMENT | CREATE_NO_WINDOW | CREATE_SUSPENDED,
            env_block,
            cwd,
            ctypes.byref(si_ex),
            ctypes.byref(pi),
        )
        if not ok:
            err = ctypes.get_last_error()
            _write_message(
                h_control,
                {"kind": KIND_DONE, "v": PROTOCOL_VERSION, "nonce": nonce,
                 "rc": -1, "job_bound": False, "child_pid": None,
                 "error": f"CreateProcessW failed ({err})"},
                k32,
            )
            return 6

        h_cmd = pi.hProcess
        h_cmd_thread = pi.hThread

        # Job: create + KILL_ON_JOB_CLOSE + assign the SUSPENDED child.
        # Every step must succeed BEFORE ResumeThread; a partially-bound
        # child is terminated while still suspended and reported as an
        # explicit failure (never run an unbound admin command).
        job = _JobBinding()
        job_bound = job.setup(k32, h_cmd)
        if not job_bound:
            err_detail = job.failure_reason or "job binding failed"
            # Still-suspended child: terminate it (TerminateProcess on a
            # suspended thread is safe) and close handles.
            k32.TerminateProcess(h_cmd, 1)
            _write_message(
                h_control,
                {"kind": KIND_DONE, "v": PROTOCOL_VERSION, "nonce": nonce,
                 "rc": -1, "job_bound": False, "child_pid": None,
                 "error": f"job binding failed: {err_detail}"},
                k32,
            )
            k32.CloseHandle(h_cmd)
            k32.CloseHandle(h_cmd_thread)
            h_cmd = None
            h_cmd_thread = None
            job.close(k32)
            return 7

        # All three job steps succeeded: resume the suspended child.
        resume_rc = k32.ResumeThread(h_cmd_thread)
        if resume_rc == 0xFFFFFFFF:
            # ResumeThread failed (returns (DWORD)-1).  The child is still
            # suspended; terminate it so nothing unbounded ever runs.
            k32.TerminateProcess(h_cmd, 1)
            _write_message(
                h_control,
                {"kind": KIND_DONE, "v": PROTOCOL_VERSION, "nonce": nonce,
                 "rc": -1, "job_bound": True, "child_pid": None,
                 "error": "ResumeThread failed; suspended child terminated"},
                k32,
            )
            k32.CloseHandle(h_cmd)
            k32.CloseHandle(h_cmd_thread)
            h_cmd = None
            h_cmd_thread = None
            job.close(k32)
            return 8

        _write_message(
            h_control,
            {"kind": KIND_READY, "v": PROTOCOL_VERSION, "nonce": nonce,
             "job_bound": job.job_bound,
             "child_pid": int(pi.dwProcessId)},
            k32,
        )

        # --- cancel handling ---------------------------------------------
        cancel_seen = threading.Event()

        def _cancel_listener() -> None:
            try:
                while not cancel_seen.is_set():
                    avail = wintypes.DWORD()
                    k32.PeekNamedPipe(h_control, None, 0, None,
                                      ctypes.byref(avail), None)
                    if int(avail.value) > 0:
                        msg = _read_message(h_control, k32)
                        validate_parent_message(msg, nonce)
                        if msg.get("kind") == "cancel":
                            cancel_seen.set()
                            # Terminate the whole tree via the job when bound.
                            if job and job.job_bound:
                                job.terminate_tree(k32)
                            return
                    time.sleep(0.05)
            except Exception:
                cancel_seen.set()

        listener = threading.Thread(target=_cancel_listener, daemon=True)
        listener.start()

        wait = k32.WaitForSingleObject(h_cmd, INFINITE)
        code = wintypes.DWORD()
        k32.GetExitCodeProcess(h_cmd, ctypes.byref(code))

        if cancel_seen.is_set():
            terminated = job.job_bound if job else False
            _write_message(
                h_control,
                {"kind": KIND_CANCELLED, "v": PROTOCOL_VERSION, "nonce": nonce,
                 "rc": int(code.value), "terminated": terminated,
                 "job_bound": job.job_bound if job else False},
                k32,
            )
        else:
            _write_message(
                h_control,
                {"kind": KIND_DONE, "v": PROTOCOL_VERSION, "nonce": nonce,
                 "rc": int(code.value),
                 "job_bound": job.job_bound if job else False,
                 "child_pid": int(pi.dwProcessId)},
                k32,
            )
        return 0
    except Exception as exc:  # noqa: BLE001 - helper must fail closed
        try:
            if h_control:
                _write_message(
                    h_control,
                    {"kind": KIND_CANCELLED, "v": PROTOCOL_VERSION,
                     "nonce": nonce, "terminated": False,
                     "error": str(exc)[:400]},
                    k32,
                )
        except Exception:
            pass
        return 1
    finally:
        if h_cmd:
            k32.CloseHandle(h_cmd)
        if h_cmd_thread:
            k32.CloseHandle(h_cmd_thread)
        if job:
            job.close(k32)
        if attr_list:
            k32.DeleteProcThreadAttributeList(attr_list)
        if h_control:
            k32.CloseHandle(h_control)
        if h_output:
            k32.CloseHandle(h_output)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
