"""Framed control protocol for the elevated helper (tools/elevated_helper.py).

The medium-integrity parent and the elevated helper communicate over a
double-ended named pipe instead of a user-writable JSON file.  This module
holds the frame format and message validation rules in pure Python so both
sides (and the unit tests) share exactly one implementation:

* Every control message is a single ``WriteFile`` on a message-mode named
  pipe: ``[4-byte little-endian length][UTF-8 JSON payload]``.
* Payloads are validated against a strict schema (version, nonce, types,
  maximum length) before any field is used — unknown/oversized/truncated
  messages are rejected (fail closed).
* The nonce binds the request to THIS helper process: it is generated by the
  parent before launch, delivered on the ShellExecuteExW command line, and
  echoed back in the first message; a replayed or forged request cannot
  match a fresh nonce for a fresh launch.

The output stream is deliberately NOT part of the control protocol: stdout/
stderr bytes travel on a separate output named pipe whose write end is the
ONLY inheritable handle given to the elevated child (see
``elevated_helper.py``).
"""

from __future__ import annotations

import json
import struct

# Protocol version — bump on any incompatible change.
PROTOCOL_VERSION = 1

# Hard cap for a single control message (bytes of UTF-8 payload).  The
# command + sanitized env for a normal terminal command fits comfortably; the
# cap exists to stop a hostile/corrupt peer from exhausting helper memory.
MAX_MESSAGE_BYTES = 1024 * 1024

# Hard cap for the number of environment entries and the total env size.
MAX_ENV_ENTRIES = 4096
MAX_ENV_TOTAL_BYTES = 512 * 1024
MAX_COMMAND_BYTES = 256 * 1024
MAX_CWD_BYTES = 16 * 1024

# Message kinds (parent -> helper)
KIND_REQUEST = "request"
KIND_CANCEL = "cancel"

# Message kinds (helper -> parent)
KIND_CONNECTED = "connected"
KIND_READY = "ready"
KIND_DONE = "done"
KIND_CANCELLED = "cancelled"

_ALLOWED_PARENT_KINDS = {KIND_REQUEST, KIND_CANCEL}
_ALLOWED_HELPER_KINDS = {KIND_CONNECTED, KIND_READY, KIND_DONE, KIND_CANCELLED}

_HEADER = struct.Struct("<I")


class ProtocolError(ValueError):
    """A frame or message violated the protocol (fail closed)."""


# ---------------------------------------------------------------------------
# Framing
# ---------------------------------------------------------------------------


def pack_message(payload: dict) -> bytes:
    """Serialize a message dict into the wire frame."""
    data = json.dumps(payload, ensure_ascii=False, sort_keys=True).encode("utf-8")
    if len(data) > MAX_MESSAGE_BYTES:
        raise ProtocolError(
            f"message payload {len(data)} exceeds MAX_MESSAGE_BYTES "
            f"({MAX_MESSAGE_BYTES})"
        )
    return _HEADER.pack(len(data)) + data


def unpack_frame(data: bytes) -> "tuple[dict, int]":
    """Parse a single frame from *data*.

    Returns ``(message, consumed)`` — the number of bytes consumed.  Raises
    :class:`ProtocolError` for truncation, over-length frames, or invalid
    JSON.  If *data* contains a valid frame followed by trailing bytes the
    caller may keep feeding the remainder to a subsequent call.
    """
    if len(data) < _HEADER.size:
        raise ProtocolError("truncated frame header")
    (length,) = _HEADER.unpack_from(data, 0)
    if length > MAX_MESSAGE_BYTES:
        raise ProtocolError(
            f"frame length {length} exceeds MAX_MESSAGE_BYTES ({MAX_MESSAGE_BYTES})"
        )
    total = _HEADER.size + length
    if len(data) < total:
        raise ProtocolError(f"truncated frame: need {total}, have {len(data)}")
    payload = data[_HEADER.size:total]
    try:
        message = json.loads(payload.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ProtocolError(f"invalid JSON payload: {exc}") from exc
    if not isinstance(message, dict):
        raise ProtocolError("message must be a JSON object")
    return message, total


# ---------------------------------------------------------------------------
# Message validation
# ---------------------------------------------------------------------------


def validate_parent_message(message: dict, expected_nonce: str) -> dict:
    """Validate a parent->helper message before acting on it.

    Fail closed on: unknown kind, wrong/missing nonce, wrong protocol
    version, wrong field types, oversized fields, or unexpected extra fields.
    """
    kind = message.get("kind")
    if kind not in _ALLOWED_PARENT_KINDS:
        raise ProtocolError(f"unknown parent message kind: {kind!r}")
    if message.get("v") != PROTOCOL_VERSION:
        raise ProtocolError(
            f"protocol version mismatch: {message.get('v')!r} != {PROTOCOL_VERSION}"
        )
    if message.get("nonce") != expected_nonce:
        raise ProtocolError("nonce mismatch (replay or forged request)")
    extra = set(message) - {"kind", "v", "nonce", "command", "cwd", "env"}
    if extra:
        raise ProtocolError(f"unexpected fields: {sorted(extra)}")

    if kind == KIND_REQUEST:
        command = message.get("command")
        if not isinstance(command, str) or not command:
            raise ProtocolError("request: command must be a non-empty string")
        if len(command.encode("utf-8")) > MAX_COMMAND_BYTES:
            raise ProtocolError("request: command too large")
        cwd = message.get("cwd")
        if cwd is not None and not isinstance(cwd, str):
            raise ProtocolError("request: cwd must be a string or null")
        if cwd is not None and len(cwd.encode("utf-8")) > MAX_CWD_BYTES:
            raise ProtocolError("request: cwd too large")
        env = message.get("env")
        if env is None:
            env = {}
        if not isinstance(env, dict):
            raise ProtocolError("request: env must be an object")
        if not all(isinstance(k, str) and isinstance(v, str) for k, v in env.items()):
            raise ProtocolError("request: env keys/values must be strings")
        if len(env) > MAX_ENV_ENTRIES:
            raise ProtocolError("request: too many env entries")
        total = sum(len(k.encode("utf-8")) + len(v.encode("utf-8")) for k, v in env.items())
        if total > MAX_ENV_TOTAL_BYTES:
            raise ProtocolError("request: env too large")
        # Helper must NEVER be told to create/overwrite/truncate arbitrary
        # files: output paths are not part of the protocol.
        for key in ("stdout_path", "stderr_path", "rc_path", "done_path"):
            if key in message:
                raise ProtocolError(f"request: {key} is not allowed in the protocol")
    return message


# Required fields (with exact types) for each helper->parent message kind.
# Every helper message MUST carry the launch nonce; the parent rejects any
# message with a missing/wrong nonce before looking at any other field.
_HELPER_FIELD_TYPES: dict[str, dict[str, type]] = {
    KIND_CONNECTED: {"pid": int},
    KIND_READY: {"job_bound": bool, "child_pid": (int, type(None))},
    KIND_DONE: {"rc": int},
    KIND_CANCELLED: {"terminated": bool},
}

# Optional extra fields that are allowed (with types) on top of the required
# ones. ``error`` is a free-form diagnostic string; ``job_bound`` may also
# appear on done/cancelled for the parent's own bookkeeping.
_HELPER_OPTIONAL_FIELD_TYPES: dict[str, dict[str, type]] = {
    KIND_CONNECTED: {"error": str},
    KIND_READY: {"error": str},
    KIND_DONE: {"error": str, "job_bound": bool, "child_pid": (int, type(None))},
    KIND_CANCELLED: {"error": str, "job_bound": bool, "child_pid": (int, type(None))},
}


def validate_helper_message(message: dict, expected_nonce: str) -> dict:
    """Validate a helper->parent message before trusting any field.

    Fail closed on: unknown kind, wrong protocol version, missing/wrong
    nonce, missing required fields, wrong field types, or unexpected extra
    fields.  Every helper message (connected/ready/done/cancelled) must
    carry the launch nonce so a stale/replayed message from a previous
    launch is rejected even if it arrives on a live pipe.
    """
    kind = message.get("kind")
    if kind not in _ALLOWED_HELPER_KINDS:
        raise ProtocolError(f"unknown helper message kind: {kind!r}")
    if message.get("v") != PROTOCOL_VERSION:
        raise ProtocolError(
            f"protocol version mismatch: {message.get('v')!r} != {PROTOCOL_VERSION}"
        )
    if message.get("nonce") != expected_nonce:
        raise ProtocolError("helper message nonce mismatch (stale or forged)")

    required = _HELPER_FIELD_TYPES[kind]
    missing = [f for f in required if f not in message]
    if missing:
        raise ProtocolError(
            f"helper {kind} message missing required fields: {sorted(missing)}"
        )
    for field, field_type in required.items():
        value = message.get(field)
        if isinstance(field_type, tuple):
            if not isinstance(value, field_type):
                raise ProtocolError(
                    f"helper {kind} message field {field!r} has wrong type "
                    f"{type(value).__name__}"
                )
        elif not isinstance(value, field_type):
            raise ProtocolError(
                f"helper {kind} message field {field!r} has wrong type "
                f"{type(value).__name__}"
            )

    allowed = set(required) | set(_HELPER_OPTIONAL_FIELD_TYPES[kind])
    allowed |= {"kind", "v", "nonce"}
    extra = set(message) - allowed
    if extra:
        raise ProtocolError(f"unexpected fields: {sorted(extra)}")
    for field, field_type in _HELPER_OPTIONAL_FIELD_TYPES[kind].items():
        if field in message and not isinstance(message[field], field_type):
            raise ProtocolError(
                f"helper {kind} message optional field {field!r} has wrong "
                f"type {type(message[field]).__name__}"
            )
    return message


# Legal helper->parent state transitions.  The helper announces itself
# (connected), reports readiness with job/child info (ready), then finishes
# with a terminal done or cancelled.  A helper that fails before ready may
# send done directly (e.g. CreateProcessW failed) — the parent accepts that
# as a legal shortcut.
_HELPER_START = "start"
_HELPER_FINAL = {KIND_DONE, KIND_CANCELLED}


class _HelperStateMachine:
    """Tracks the helper->parent message sequence and rejects illegal ones.

    Legal sequences:
      start -> connected -> ready -> done|cancelled
      start -> connected -> done              (launch failure shortcut)
    Any repeated, reordered, or post-terminal message is a protocol error.
    """

    def __init__(self) -> None:
        self._state = _HELPER_START

    def transition(self, kind: str) -> None:
        if self._state == _HELPER_START:
            if kind != KIND_CONNECTED:
                raise ProtocolError(
                    f"first helper message must be {KIND_CONNECTED!r}, got {kind!r}"
                )
            self._state = KIND_CONNECTED
            return
        if self._state == KIND_CONNECTED:
            if kind in (KIND_READY, KIND_DONE):
                self._state = kind
                return
            raise ProtocolError(
                f"illegal helper transition {KIND_CONNECTED!r} -> {kind!r}"
            )
        if self._state == KIND_READY:
            if kind in _HELPER_FINAL:
                self._state = kind
                return
            raise ProtocolError(f"illegal helper transition {KIND_READY!r} -> {kind!r}")
        # Terminal state: nothing may follow.
        raise ProtocolError(
            f"helper message {kind!r} after terminal {self._state!r}"
        )


def make_request(nonce: str, command: str, cwd: "str | None", env: dict) -> dict:
    return {
        "kind": KIND_REQUEST,
        "v": PROTOCOL_VERSION,
        "nonce": nonce,
        "command": command,
        "cwd": cwd,
        "env": env,
    }


def make_cancel(nonce: str) -> dict:
    return {"kind": KIND_CANCEL, "v": PROTOCOL_VERSION, "nonce": nonce}
