"""Config-gated, allowlisted live model selection for the agent loop.

The tool owns route validation, shared model resolution, the in-place runtime
swap, reasoning selection, session-state notification, and the user-facing
notice. Frontends only persist the supplied runtime snapshot for their session.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from tools.registry import no_cache_check_fn, registry

logger = logging.getLogger(__name__)

_TOOL_NAME = "select_model"
_MAX_REASON_CHARS = 500


def _load_selection_config() -> dict:
    from hermes_cli.config import load_config_readonly

    config = load_config_readonly() or {}
    agent_config = config.get("agent") if isinstance(config, dict) else None
    selection = agent_config.get("model_selection") if isinstance(agent_config, dict) else None
    return selection if isinstance(selection, dict) else {}


@no_cache_check_fn
def check_model_selection_requirements() -> bool:
    config = _load_selection_config()
    routes = config.get("routes")
    return bool(config.get("enabled") and isinstance(routes, dict) and routes)


def _selection_description() -> dict:
    config = _load_selection_config()
    configured_routes = config.get("routes")
    routes = configured_routes if isinstance(configured_routes, dict) else {}
    route_lines = []
    for name, route in routes.items():
        if not isinstance(route, dict):
            continue
        description = str(route.get("description") or "").strip()
        default = str(route.get("default_reasoning") or "").strip().lower()
        route_lines.append(
            f"{name}: {description or 'configured route'}"
            + (f" Default reasoning: {default}." if default else "")
        )
    configured = " ".join(route_lines)
    return {
        "description": (
            "Switch this active Hermes session to an operator-configured model route before doing work "
            "that requires a different tier. Call it alone: any other tool calls emitted in the same "
            "batch are skipped and regenerated by the selected model. Give the concrete task reason; "
            "the runtime reports the selected model, reasoning effort, and reason to the user. "
            f"Configured policy: {configured}"
        )
    }


def _failure(message: str) -> str:
    return json.dumps({"success": False, "error": message}, ensure_ascii=False)


def _route_settings(config: dict, route: str, requested_effort: str | None) -> tuple[dict, str] | str:
    configured_routes = config.get("routes")
    routes = configured_routes if isinstance(configured_routes, dict) else {}
    settings = routes.get(route)
    if not isinstance(settings, dict):
        return f"Route '{route}' is not allowlisted. Available routes: {', '.join(sorted(routes)) or 'none'}."

    effort = str(requested_effort or settings.get("default_reasoning") or "").strip().lower()
    from hermes_constants import parse_reasoning_effort

    if not effort or parse_reasoning_effort(effort) is None:
        return f"Route '{route}' has no valid reasoning effort."
    allowed = settings.get("allowed_reasoning")
    if not isinstance(allowed, list) or not allowed:
        allowed = [str(settings.get("default_reasoning") or "").strip().lower()]
    allowed = [str(value).strip().lower() for value in allowed if str(value).strip()]
    if effort not in allowed:
        return (
            f"Reasoning effort '{effort}' is not allowed for route '{route}'. "
            f"Allowed: {', '.join(allowed)}."
        )
    return settings, effort


def _resolve_switch_result(agent, target: str):
    from hermes_cli.config import get_compatible_custom_providers, load_config_readonly
    from hermes_cli.model_switch import switch_model

    config = load_config_readonly() or {}
    configured_providers = config.get("providers")
    user_providers = configured_providers if isinstance(configured_providers, dict) else {}
    return switch_model(
        raw_input=target,
        current_provider=str(getattr(agent, "provider", "") or ""),
        current_model=str(getattr(agent, "model", "") or ""),
        current_base_url=str(getattr(agent, "base_url", "") or ""),
        current_api_key=getattr(agent, "api_key", "") or "",
        is_global=False,
        user_providers=user_providers,
        custom_providers=get_compatible_custom_providers(config),
    )


def _apply_reasoning(agent, effort: str) -> dict:
    from hermes_constants import parse_reasoning_effort

    parsed = parse_reasoning_effort(effort)
    if parsed is None:  # validated before the switch; retained as a local invariant
        raise ValueError(f"Invalid reasoning effort: {effort}")
    agent.reasoning_config = parsed
    primary = getattr(agent, "_primary_runtime", None)
    if isinstance(primary, dict):
        primary["reasoning_config"] = dict(parsed)
    return parsed


def _display_route(route: str) -> str:
    return route[:1].upper() + route[1:]


def _notify_user(agent, message: str, route: str) -> None:
    callback = getattr(agent, "notice_callback", None)
    if callback is None:
        return
    from agent.credits_tracker import AgentNotice

    callback(AgentNotice(
        text=message,
        level="info",
        kind="ttl",
        ttl_ms=12_000,
        key=f"model.selection.{route}",
        id=f"model.selection.{route}",
    ))


def select_model_tool(
    agent,
    *,
    route: str,
    reason: str,
    reasoning_effort: str | None = None,
    reasoning_reason: str | None = None,
) -> str:
    # The executor uses this barrier even on failure: actions emitted by the old
    # model beside a route request must be regenerated after selection succeeds.
    agent._model_selection_attempted_in_tool_batch = True
    config = _load_selection_config()
    if not config.get("enabled"):
        return _failure("Autonomous model selection is not enabled.")

    route = str(route or "").strip().lower()
    reason = " ".join(str(reason or "").split())[:_MAX_REASON_CHARS]
    if not reason:
        return _failure("A non-empty model-selection reason is required.")
    report_callback = getattr(agent, "model_selection_callback", None)
    if report_callback is None:
        return _failure("This session surface does not support reported model selection.")

    selected = _route_settings(config, route, reasoning_effort)
    if isinstance(selected, str):
        return _failure(selected)
    settings, effort = selected
    target = str(settings.get("target") or route).strip()
    reasoning_reason = " ".join(str(reasoning_reason or settings.get("reasoning_description") or "").split())
    if not reasoning_reason:
        reasoning_reason = f"{effort.capitalize()} is the configured default for the {_display_route(route)} route."
    reasoning_reason = reasoning_reason[:_MAX_REASON_CHARS]

    result = _resolve_switch_result(agent, target)
    if not result.success:
        return _failure(result.error_message or f"Could not resolve model route '{route}'.")

    old_model = str(getattr(agent, "model", "") or "")
    old_provider = str(getattr(agent, "provider", "") or "")
    old_reasoning = dict(getattr(agent, "reasoning_config", None) or {})
    parsed_reasoning = None
    try:
        same_runtime = (
            old_model == result.new_model
            and old_provider == result.target_provider
            and str(getattr(agent, "base_url", "") or "") == str(result.base_url or "")
            and str(getattr(agent, "api_mode", "") or "") == str(result.api_mode or "")
        )
        if not same_runtime:
            agent.switch_model(
                new_model=result.new_model,
                new_provider=result.target_provider,
                api_key=result.api_key,
                base_url=result.base_url,
                api_mode=result.api_mode,
                capabilities=getattr(result, "runtime_capabilities", None),
            )
        parsed_reasoning = _apply_reasoning(agent, effort)
    except Exception as exc:
        logger.warning("Autonomous model selection failed for route %s: %s", route, exc)
        return _failure(
            f"Model switch to route '{route}' failed; staying on {old_model or 'the current model'} ({exc})."
        )

    changed = old_model != result.new_model or old_provider != result.target_provider or old_reasoning != parsed_reasoning
    message = (
        f"Model selected: {_display_route(route)} ({result.new_model}) — {reason} "
        f"Reasoning: {effort} — {reasoning_reason}"
    )
    session_update = {
        "route": route,
        "reasoning_effort": effort,
        "reasoning_reason": reasoning_reason,
        "reason": reason,
        "message": message,
        "reasoning_config": dict(parsed_reasoning),
        "runtime": {
            "model": result.new_model,
            "provider": result.target_provider,
            "base_url": result.base_url,
            "api_mode": result.api_mode,
        },
    }
    try:
        report_callback(session_update)
    except Exception:
        logger.warning("Model selection session-state callback failed", exc_info=True)
        _notify_user(agent, message, route)

    agent._model_selected_in_tool_batch = True
    return json.dumps({
        "success": True,
        "changed": changed,
        "route": route,
        "model": result.new_model,
        "provider": result.target_provider,
        "reasoning_effort": effort,
        "reasoning_reason": reasoning_reason,
        "reason": reason,
        "message": message,
    }, ensure_ascii=False)


MODEL_SELECTION_SCHEMA = {
    "name": _TOOL_NAME,
    "description": "Switch to an operator-configured model route.",
    "parameters": {
        "type": "object",
        "properties": {
            "route": {"type": "string", "description": "Configured route name."},
            "reason": {
                "type": "string",
                "description": "Concrete reason this task requires the selected route.",
            },
            "reasoning_effort": {
                "type": "string",
                "enum": ["none", "minimal", "low", "medium", "high", "xhigh", "max", "ultra"],
                "description": "Optional route-allowed effort; omit for the route default.",
            },
            "reasoning_reason": {
                "type": "string",
                "description": (
                    "Why the selected reasoning effort fits this task. Omit when the route's "
                    "configured default explanation applies."
                ),
            },
        },
        "required": ["route", "reason"],
    },
}


registry.register(
    name=_TOOL_NAME,
    toolset="model_selection",
    schema=MODEL_SELECTION_SCHEMA,
    handler=lambda args, **kw: _failure("select_model must be handled by the live agent loop."),
    check_fn=check_model_selection_requirements,
    emoji="🧭",
    dynamic_schema_overrides=_selection_description,
)
