"""Regression tests for post-compression continuity state injection.

The todo snapshot is generated by Hermes, not typed by the user.  If it is
reinserted as a user-role message, the next model can treat the capsule itself
as the latest user request and drift away from the real lane after compaction.
"""

from types import SimpleNamespace

from agent.conversation_compression import compress_context
from tools.todo_tool import TodoStore


class _FakeEngine:
    compression_count = 1
    last_prompt_tokens = 0
    last_completion_tokens = 0
    _last_compress_aborted = False
    _last_summary_error = None
    _last_aux_model_failure_model = None
    _last_aux_model_failure_error = None

    def compress(self, messages, current_tokens=None, focus_topic=None, force=False):
        return [
            {"role": "user", "content": "original start"},
            {"role": "assistant", "content": "compressed summary"},
        ]


def _fake_agent(todo_store):
    return SimpleNamespace(
        _compression_feasibility_checked=True,
        context_compressor=_FakeEngine(),
        session_id="sess-1",
        model="test-model",
        platform="cli",
        log_prefix="",
        tools=[],
        _session_db=None,
        _memory_manager=None,
        _cached_system_prompt=None,
        _last_flushed_db_idx=0,
        _todo_store=todo_store,
        _emit_status=lambda *a, **kw: None,
        _emit_warning=lambda *a, **kw: None,
        _vprint=lambda *a, **kw: None,
        _invalidate_system_prompt=lambda *a, **kw: None,
        _build_system_prompt=lambda system_message: f"rebuilt:{system_message}",
        commit_memory_session=lambda *a, **kw: None,
    )


def test_compression_continuity_capsule_is_not_reinserted_as_user_message():
    store = TodoStore()
    store.write([
        {"id": "p1", "content": "Continue the real lane", "status": "in_progress"},
    ])
    agent = _fake_agent(store)

    compressed, new_prompt = compress_context(
        agent,
        [{"role": "user", "content": "hello"}, {"role": "assistant", "content": "hi"}],
        "system",
        approx_tokens=120_000,
    )

    capsule = compressed[-1]
    assert new_prompt == "rebuilt:system"
    assert len(compressed) == 2
    assert "compressed summary" in capsule["content"]
    assert "COMPACTION CONTINUATION CAPSULE" in capsule["content"]
    assert capsule["role"] == "assistant"


def test_todo_injection_marks_capsule_as_generated_continuity_state():
    store = TodoStore()
    store.write([
        {"id": "done", "content": "Already done", "status": "completed"},
        {"id": "active", "content": "Continue active work", "status": "in_progress"},
        {"id": "next", "content": "Next safe task", "status": "pending"},
    ])

    text = store.format_for_injection()
    assert text is not None

    assert text.startswith("[COMPACTION CONTINUATION CAPSULE — AUTHORITATIVE ROUTING]")
    assert "Generated by Hermes from the preserved todo store" in text
    assert "not a user-authored chat request" in text
    assert "Latest real user message after this capsule overrides it" in text
    assert "Already done" not in text
    assert "Continue active work" in text
    assert "Next safe task" in text
