export interface DashboardPageMetadata {
  route: string;
  title: string;
  recipe: string;
  owner: string;
  category: string;
  dataContracts: string[];
  requiredStates: string[];
  validation: string[];
  productionUrl?: string;
  localOnlyReason?: string;
}

export interface DashboardGovernanceDefaults {
  designSystem: {
    sourcePackage: string;
    designContract: string;
    adoptionRegistry: string;
    bypassPolicy: string;
  };
  finalHandoffEvidence: string[];
}

export const dashboardGovernanceDefaults: DashboardGovernanceDefaults = {
  designSystem: {
    sourcePackage: "@hermes/dashboard-kit",
    designContract: "packages/hermes-dashboard-kit/DESIGN.md",
    adoptionRegistry: "docs/design/dashboard-kit-adoption.json",
    bypassPolicy: "Dashboard work must use the package or static adapter unless a documented design-system exception is approved.",
  },
  finalHandoffEvidence: [
    "V7 recipe id",
    "Data contracts used",
    "Required states checked",
    "Validation commands run",
    "Screenshot evidence or explicit local-only reason",
    "Design-system status output",
  ],
};

export const dashboardPageMetadata: DashboardPageMetadata[] = [
  {
    route: "/central-command",
    title: "Hermes Central Command",
    recipe: "executive-command-center",
    owner: "Hermes",
    category: "control-plane",
    dataContracts: ["DashboardSnapshot[]", "ActionNeeded[]", "DailyBriefItem[]", "DeploymentSignal"],
    requiredStates: ["normal", "fallback", "warning", "critical", "stale", "mobile"],
    validation: ["dashboard:v12:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Central command route served by the Hermes dashboard app until promoted to production.",
  },
  {
    route: "/design-system",
    title: "Hermes Dashboard Design System",
    recipe: "system-health-deployment",
    owner: "Hermes",
    category: "design-system",
    dataContracts: ["dashboardRecipes[]", "componentExamples[]", "dashboardRegistryExamples[]"],
    requiredStates: ["normal", "loading", "empty", "error", "disabled", "warning", "critical", "mobile"],
    validation: ["dashboard:v7:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Internal gallery route served by the Hermes dashboard app.",
  },
  {
    route: "/executive-summary",
    title: "TLC Executive Summary",
    recipe: "executive-command-center",
    owner: "Hermes",
    category: "control-plane",
    dataContracts: ["DashboardSnapshot[]", "HealthSnapshot", "CostSnapshot", "CapacitySnapshot", "QueueSnapshot", "ActionNeeded[]"],
    requiredStates: ["normal", "fallback", "refreshing", "warning", "critical", "stale", "mobile"],
    validation: ["dashboard:v9:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Reference command-layer route until production Hermes dashboard deployment is promoted.",
  },
  {
    route: "/dashboard-migrations",
    title: "Package-Native Dashboard Migrations",
    recipe: "system-health-deployment",
    owner: "Hermes",
    category: "design-system-governance",
    dataContracts: ["MigrationTarget[]", "V7 recipe mapping", "adapter retirement rule"],
    requiredStates: ["normal", "planned", "ready", "in-progress", "blocked", "disabled command", "mobile"],
    validation: ["dashboard:v8:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Governance workbench route served by the Hermes dashboard app.",
  },
  {
    route: "/package-native/media-engine",
    title: "Media Engine Package-Native Ops",
    recipe: "pipeline-workflow-dashboard",
    owner: "Media Engine",
    category: "media-operations",
    dataContracts: ["DashboardSnapshot", "HealthSnapshot", "CostSnapshot", "CapacitySnapshot", "QueueSnapshot", "ActionNeeded[]"],
    requiredStates: ["normal", "fallback", "warning", "critical", "stale", "disabled command", "mobile"],
    validation: ["dashboard:v8:validate", "dashboard:visual:check", "build --workspace web"],
    productionUrl: "https://media.tlccapitalgroup.com/dashboard",
    localOnlyReason: "Shadow package-native route used for V8 parity before replacing the production static adapter.",
  },
  {
    route: "/package-native/khashi-vc",
    title: "Khashi VC Package-Native ROC",
    recipe: "operations-control-room",
    owner: "Khashi VC",
    category: "research-operations",
    dataContracts: ["DashboardSnapshot", "HealthSnapshot", "CostSnapshot", "CapacitySnapshot", "QueueSnapshot", "ActionNeeded[]"],
    requiredStates: ["normal", "fallback", "warning", "critical", "stale", "disabled command", "mobile"],
    validation: ["dashboard:v8:validate", "dashboard:visual:check", "build --workspace web"],
    productionUrl: "https://roc.tlccapitalgroup.com/",
    localOnlyReason: "Shadow package-native route used for V8 parity before replacing the production static adapter.",
  },
  {
    route: "/theme-system",
    title: "Multi-Brand Dashboard Themes",
    recipe: "system-health-deployment",
    owner: "Hermes",
    category: "design-system",
    dataContracts: ["DashboardThemeProfile[]", "DashboardThemeTokenSet"],
    requiredStates: ["normal", "contrast-watch", "theme-preview", "mobile"],
    validation: ["dashboard:v13:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Theme governance route served by the Hermes dashboard app.",
  },
  {
    route: "/dashboard-marketplace",
    title: "Dashboard Marketplace",
    recipe: "system-health-deployment",
    owner: "Hermes",
    category: "plugin-governance",
    dataContracts: ["DashboardPluginManifest[]", "DashboardPluginPanel[]", "DashboardPluginCommand[]"],
    requiredStates: ["normal", "permission-limited", "high-risk", "missing-health", "mobile"],
    validation: ["dashboard:v14:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Marketplace governance route served by the Hermes dashboard app.",
  },
  {
    route: "/live-signals",
    title: "Live Project Signal Integration",
    recipe: "system-health-deployment",
    owner: "Hermes",
    category: "control-plane",
    dataContracts: ["LiveSignalIntegration[]", "DashboardSnapshot", "HealthSnapshot", "ActionNeeded"],
    requiredStates: ["ready", "partial", "missing", "stale", "mobile"],
    validation: ["dashboard:v15:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Signal integration registry route served by the Hermes dashboard app.",
  },
  {
    route: "/task-routing",
    title: "Agent Task Routing",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "agent-operations",
    dataContracts: ["RoutedTask[]", "ActionNeeded[]", "TaskPriority", "TaskStatus"],
    requiredStates: ["queued", "assigned", "blocked", "done", "critical", "mobile"],
    validation: ["dashboard:v16:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Task routing workbench route served by the Hermes dashboard app.",
  },
  {
    route: "/decision-ledger",
    title: "Memory And Decision Ledger",
    recipe: "research-intelligence-dashboard",
    owner: "Hermes",
    category: "memory-governance",
    dataContracts: ["DecisionRecord[]", "DecisionStatus", "ReviewTimestamp"],
    requiredStates: ["active", "superseded", "needs-review", "stale", "mobile"],
    validation: ["dashboard:v17:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Decision ledger route served by the Hermes dashboard app.",
  },
  {
    route: "/model-routing",
    title: "Model And Cost Routing",
    recipe: "cost-capacity-dashboard",
    owner: "Hermes",
    category: "model-governance",
    dataContracts: ["ModelRoutingPolicy[]", "ProviderCostSignal", "ApprovalGate"],
    requiredStates: ["free-local-first", "cheap-api-first", "premium-approval", "blocked", "mobile"],
    validation: ["dashboard:v18:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Model policy route served by the Hermes dashboard app.",
  },
  {
    route: "/operating-loops",
    title: "Autonomous Operating Loops",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "agent-operations",
    dataContracts: ["OperatingLoop[]", "Cadence", "LoopOutput"],
    requiredStates: ["ready", "draft", "paused", "failed", "mobile"],
    validation: ["dashboard:v19:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Operating loop registry route served by the Hermes dashboard app.",
  },
  {
    route: "/permission-security",
    title: "Secure Tool And Permission Layer",
    recipe: "system-health-deployment",
    owner: "Hermes",
    category: "security-governance",
    dataContracts: ["PermissionPolicy[]", "ApprovalRequirement", "AuditRecord"],
    requiredStates: ["viewer", "operator", "admin", "explicit", "audited", "mobile"],
    validation: ["dashboard:v20:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Permission policy route served by the Hermes dashboard app.",
  },
  {
    route: "/business-os",
    title: "TLC Business Operating System",
    recipe: "executive-command-center",
    owner: "Hermes",
    category: "business-control-plane",
    dataContracts: ["BusinessScorecard[]", "RevenueSignal", "CostSignal", "OperatingFocus"],
    requiredStates: ["normal", "early-signal", "warning", "critical", "mobile"],
    validation: ["dashboard:v21:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Business operating system route served by the Hermes dashboard app.",
  },
  {
    route: "/project-snapshots",
    title: "Live Project Snapshot Contracts",
    recipe: "system-health-deployment",
    owner: "Hermes",
    category: "signal-governance",
    dataContracts: ["OperatingSystemStage", "DashboardSnapshot", "HealthSnapshot", "ActionNeeded", "CostSnapshot", "CapacitySnapshot"],
    requiredStates: ["built", "gated", "planned", "stale", "missing", "mobile"],
    validation: ["dashboard:v22:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Snapshot contract governance route served by the Hermes dashboard app.",
  },
  {
    route: "/durable-memory",
    title: "Durable Memory And Decision Store",
    recipe: "research-intelligence-dashboard",
    owner: "Hermes",
    category: "memory-governance",
    dataContracts: ["OperatingSystemStage", "DecisionRecord", "RoutedTask", "ReviewRecord", "ContextLink"],
    requiredStates: ["built", "gated", "active", "superseded", "needs-review", "mobile"],
    validation: ["dashboard:v23:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Memory governance route served by the Hermes dashboard app.",
  },
  {
    route: "/permission-runtime",
    title: "Permission Enforcement Runtime",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "security-governance",
    dataContracts: ["OperatingSystemStage", "PermissionPolicy", "ApprovalGate", "AuditRecord"],
    requiredStates: ["built", "gated", "denied", "approved", "audited", "mobile"],
    validation: ["dashboard:v24:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Runtime permission governance route served by the Hermes dashboard app.",
  },
  {
    route: "/cost-governor",
    title: "Model Router And Cost Governor",
    recipe: "cost-capacity-dashboard",
    owner: "Hermes",
    category: "model-governance",
    dataContracts: ["OperatingSystemStage", "ModelRoutingPolicy", "ProviderScore", "BudgetBreaker"],
    requiredStates: ["built", "gated", "local-first", "cheap-api-first", "premium-approval", "mobile"],
    validation: ["dashboard:v25:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Cost-governance route served by the Hermes dashboard app.",
  },
  {
    route: "/loop-runner",
    title: "Operating Loop Runner",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "agent-operations",
    dataContracts: ["OperatingSystemStage", "OperatingLoop", "LoopRun", "LoopArtifact"],
    requiredStates: ["built", "gated", "dry-run", "scheduled", "failed", "mobile"],
    validation: ["dashboard:v26:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Loop runner governance route served by the Hermes dashboard app.",
  },
  {
    route: "/business-command",
    title: "Cross-Business Command Center",
    recipe: "executive-command-center",
    owner: "TLC Capital Group OS",
    category: "business-control-plane",
    dataContracts: ["OperatingSystemStage", "BusinessScorecard", "AttentionQueue", "RevenueSignal", "CostSignal"],
    requiredStates: ["built", "gated", "warning", "critical", "early-signal", "mobile"],
    validation: ["dashboard:v27:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Cross-business command route served by the Hermes dashboard app.",
  },
  {
    route: "/agent-workbench",
    title: "Agent Workbench",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "agent-operations",
    dataContracts: ["OperatingSystemStage", "RoutedTask", "ApprovalGate", "ArtifactRecord", "CompletionReport"],
    requiredStates: ["built", "gated", "planned", "approved", "executed", "mobile"],
    validation: ["dashboard:v28:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Agent workbench route served by the Hermes dashboard app.",
  },
  {
    route: "/evaluation-gates",
    title: "Evaluation And Quality Gates",
    recipe: "system-health-deployment",
    owner: "Hermes",
    category: "quality-governance",
    dataContracts: ["OperatingSystemStage", "QualityGate", "ModelEval", "DashboardScore"],
    requiredStates: ["built", "gated", "passed", "failed", "regression", "mobile"],
    validation: ["dashboard:v29:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Quality gate route served by the Hermes dashboard app.",
  },
  {
    route: "/autonomy-readiness",
    title: "Production Autonomy Readiness",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "autonomy-governance",
    dataContracts: ["OperatingSystemStage", "AutonomyLevel", "KillSwitch", "BudgetBreaker", "IncidentReview"],
    requiredStates: ["built", "gated", "manual", "assisted", "supervised", "limited-autonomous", "mobile"],
    validation: ["dashboard:v30:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Autonomy readiness route served by the Hermes dashboard app.",
  },
  {
    route: "/project-registry",
    title: "Production Project Registry",
    recipe: "system-health-deployment",
    owner: "Hermes",
    category: "project-governance",
    dataContracts: ["OperatingSystemStage", "DashboardRegistryEntry", "ProjectOwner", "HealthEndpoint", "SnapshotUrl"],
    requiredStates: ["registered", "missing", "verified", "stale", "gated", "mobile"],
    validation: ["dashboard:v31:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Project registry route served by the Hermes dashboard app.",
  },
  {
    route: "/telemetry-fabric",
    title: "Telemetry Fabric",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "observability-governance",
    dataContracts: ["OperatingSystemStage", "TelemetrySignal", "FreshnessRule", "QueuePressure", "StorageSignal"],
    requiredStates: ["fresh", "stale", "missing", "degraded", "gated", "mobile"],
    validation: ["dashboard:v32:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Telemetry fabric route served by the Hermes dashboard app.",
  },
  {
    route: "/incident-command",
    title: "Incident Command",
    recipe: "operations-control-room",
    owner: "Operations",
    category: "incident-governance",
    dataContracts: ["OperatingSystemStage", "IncidentRecord", "Severity", "RollbackPlan", "Owner"],
    requiredStates: ["info", "warning", "high", "critical", "resolved", "mobile"],
    validation: ["dashboard:v33:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Incident command route served by the Hermes dashboard app.",
  },
  {
    route: "/deployment-promotion",
    title: "Deployment Promotion Rail",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "deployment-governance",
    dataContracts: ["OperatingSystemStage", "PromotionGate", "MigrationRequirement", "HealthCheck", "RollbackEvidence"],
    requiredStates: ["validated", "built", "tested", "deployed", "failed", "mobile"],
    validation: ["dashboard:v34:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Deployment promotion route served by the Hermes dashboard app.",
  },
  {
    route: "/secrets-posture",
    title: "Secrets And Access Posture",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "security-governance",
    dataContracts: ["OperatingSystemStage", "SecretPresence", "AccessScope", "RotationPolicy", "DeployKey"],
    requiredStates: ["present", "missing", "scoped", "rotation-due", "blocked", "mobile"],
    validation: ["dashboard:v35:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Secrets posture route served by the Hermes dashboard app.",
  },
  {
    route: "/data-source-catalog",
    title: "Data Source Catalog",
    recipe: "research-intelligence-dashboard",
    owner: "Hermes",
    category: "data-governance",
    dataContracts: ["OperatingSystemStage", "DataSource", "FreshnessRule", "RetentionPolicy", "ConsumerMap"],
    requiredStates: ["known", "fresh", "stale", "retention-watch", "missing", "mobile"],
    validation: ["dashboard:v36:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Data source catalog route served by the Hermes dashboard app.",
  },
  {
    route: "/finance-attribution",
    title: "Finance And Cost Attribution",
    recipe: "cost-capacity-dashboard",
    owner: "TLC Capital Group OS",
    category: "finance-governance",
    dataContracts: ["OperatingSystemStage", "CostBucket", "BusinessUnit", "ManualRate", "InvoiceReconciliation"],
    requiredStates: ["attributed", "estimated", "missing-rate", "over-budget", "gated", "mobile"],
    validation: ["dashboard:v37:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Finance attribution route served by the Hermes dashboard app.",
  },
  {
    route: "/learning-engine",
    title: "Learning Engine",
    recipe: "research-intelligence-dashboard",
    owner: "Hermes",
    category: "learning-governance",
    dataContracts: ["OperatingSystemStage", "LearningRecord", "EvidencePromotion", "PolicyProposal", "CounterEvidence"],
    requiredStates: ["candidate", "finding", "policy-proposed", "rejected", "gated", "mobile"],
    validation: ["dashboard:v38:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Learning engine route served by the Hermes dashboard app.",
  },
  {
    route: "/agent-eval-lab",
    title: "Agent Evaluation Lab",
    recipe: "research-intelligence-dashboard",
    owner: "Hermes",
    category: "model-governance",
    dataContracts: ["OperatingSystemStage", "ProviderEval", "GoldenTask", "QualityScore", "CostLatencyScore"],
    requiredStates: ["queued", "running", "passed", "failed", "insufficient-data", "mobile"],
    validation: ["dashboard:v39:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Agent evaluation lab route served by the Hermes dashboard app.",
  },
  {
    route: "/executive-cockpit",
    title: "Executive Cockpit",
    recipe: "executive-command-center",
    owner: "TLC Capital Group OS",
    category: "executive-control-plane",
    dataContracts: ["OperatingSystemStage", "ExecutiveSignal", "ApprovalAgenda", "BoardNarrative", "AutonomyLimit"],
    requiredStates: ["healthy", "watch", "blocked", "approval-needed", "critical", "mobile"],
    validation: ["dashboard:v40:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Executive cockpit route served by the Hermes dashboard app.",
  },
  {
    route: "/production-verification",
    title: "Live Production Verification Runner",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "production-governance",
    dataContracts: ["OperatingSystemStage", "ProductionCheck", "HealthCheck", "SnapshotCheck", "ScreenshotEvidence"],
    requiredStates: ["queued", "verified", "failed", "stale", "gated", "mobile"],
    validation: ["dashboard:v41:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Production verification route served by the Hermes dashboard app.",
  },
  {
    route: "/command-gates",
    title: "Command Gate Runtime",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "permission-governance",
    dataContracts: ["OperatingSystemStage", "PermissionDecision", "AuditRecord", "CommandRisk", "ExplicitApproval"],
    requiredStates: ["allowed", "denied", "confirm", "explicit", "audited", "mobile"],
    validation: ["dashboard:v42:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Command gate route served by the Hermes dashboard app.",
  },
  {
    route: "/telemetry-adapters",
    title: "Project Telemetry Adapter Kit",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "observability-governance",
    dataContracts: ["OperatingSystemStage", "TelemetryAdapter", "DashboardSnapshot", "StorageSignal", "QueueSignal"],
    requiredStates: ["ready", "partial", "missing", "stale", "warning", "mobile"],
    validation: ["dashboard:v43:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Telemetry adapter route served by the Hermes dashboard app.",
  },
  {
    route: "/incident-ingestion",
    title: "Incident Ingestion And Escalation",
    recipe: "operations-control-room",
    owner: "Operations",
    category: "incident-governance",
    dataContracts: ["OperatingSystemStage", "IncidentRule", "IncidentRecord", "EscalationPolicy", "RollbackPlan"],
    requiredStates: ["open", "triaged", "escalated", "resolved", "blocked", "mobile"],
    validation: ["dashboard:v44:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Incident ingestion route served by the Hermes dashboard app.",
  },
  {
    route: "/promotion-runner",
    title: "Shared Deployment Promotion Runner",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "deployment-governance",
    dataContracts: ["OperatingSystemStage", "PromotionRun", "ValidationEvidence", "MigrationEvidence", "RollbackEvidence"],
    requiredStates: ["validated", "blocked", "promoted", "rolled-back", "approval-needed", "mobile"],
    validation: ["dashboard:v45:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Promotion runner route served by the Hermes dashboard app.",
  },
  {
    route: "/secret-scanner",
    title: "Secrets Posture Scanner",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "security-governance",
    dataContracts: ["OperatingSystemStage", "SecretPresence", "SecretScope", "RotationStatus", "DeployKeyPosture"],
    requiredStates: ["present", "missing", "scoped", "rotation-due", "blocked", "mobile"],
    validation: ["dashboard:v46:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Secret scanner route served by the Hermes dashboard app.",
  },
  {
    route: "/cost-attribution-engine",
    title: "Cost Attribution Engine",
    recipe: "cost-capacity-dashboard",
    owner: "TLC Capital Group OS",
    category: "finance-governance",
    dataContracts: ["OperatingSystemStage", "CostRecord", "RateTable", "InvoiceImport", "BusinessUnitAllocation"],
    requiredStates: ["attributed", "estimated", "missing-rate", "over-budget", "reconciled", "mobile"],
    validation: ["dashboard:v47:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Cost attribution engine route served by the Hermes dashboard app.",
  },
  {
    route: "/learning-ingestion",
    title: "Learning Ingestion Pipeline",
    recipe: "research-intelligence-dashboard",
    owner: "Hermes",
    category: "learning-governance",
    dataContracts: ["OperatingSystemStage", "LearningEvent", "OutcomeSource", "EvidenceRecord", "PolicyProposal"],
    requiredStates: ["candidate", "finding", "policy-proposed", "rejected", "gated", "mobile"],
    validation: ["dashboard:v48:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Learning ingestion route served by the Hermes dashboard app.",
  },
  {
    route: "/model-eval-harness",
    title: "Agent And Model Eval Harness",
    recipe: "research-intelligence-dashboard",
    owner: "Hermes",
    category: "model-governance",
    dataContracts: ["OperatingSystemStage", "GoldenTask", "ProviderRun", "EvalScore", "RoutingRecommendation"],
    requiredStates: ["queued", "running", "passed", "failed", "insufficient-data", "mobile"],
    validation: ["dashboard:v49:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Model eval harness route served by the Hermes dashboard app.",
  },
  {
    route: "/circuit-breakers",
    title: "Runtime Circuit Breakers",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "autonomy-governance",
    dataContracts: ["OperatingSystemStage", "KillSwitch", "BudgetBreaker", "ProviderSpendCap", "LoopStop"],
    requiredStates: ["enabled", "disabled", "triggered", "gated", "audited", "mobile"],
    validation: ["dashboard:v50:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Circuit breaker route served by the Hermes dashboard app.",
  },
  {
    route: "/production-sweep",
    title: "Production DNS And Health Sweep",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "production-governance",
    dataContracts: ["OperatingSystemStage", "ProductionSweepRun", "DnsCheck", "TlsCheck", "ScreenshotEvidence"],
    requiredStates: ["dry-run", "approved", "verified", "failed", "incident-created", "mobile"],
    validation: ["dashboard:v51:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Production sweep route served by the Hermes dashboard app.",
  },
  {
    route: "/hetzner-promotion-execution",
    title: "Hetzner Promotion Execution",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "deployment-governance",
    dataContracts: ["OperatingSystemStage", "PromotionExecution", "MigrationPlan", "RemoteCommandPlan", "RollbackEvidence"],
    requiredStates: ["planned", "dry-run", "approved", "deployed", "rolled-back", "mobile"],
    validation: ["dashboard:v52:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Hetzner promotion execution route served by the Hermes dashboard app.",
  },
  {
    route: "/command-gate-coverage",
    title: "Command Gate Coverage Auditor",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "permission-governance",
    dataContracts: ["OperatingSystemStage", "GateCoverageRecord", "CommandHandler", "RiskClass", "AuditRecord"],
    requiredStates: ["covered", "partial", "missing", "incident-created", "blocked", "mobile"],
    validation: ["dashboard:v53:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Command gate coverage route served by the Hermes dashboard app.",
  },
  {
    route: "/project-adapter-rollout",
    title: "Project Adapter Rollout",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "observability-governance",
    dataContracts: ["OperatingSystemStage", "AdapterRolloutRecord", "DashboardManifest", "DashboardSnapshot", "MissingField"],
    requiredStates: ["adopted", "partial", "missing", "stale", "blocked", "mobile"],
    validation: ["dashboard:v54:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Project adapter rollout route served by the Hermes dashboard app.",
  },
  {
    route: "/incident-automation",
    title: "Incident Automation Engine",
    recipe: "operations-control-room",
    owner: "Operations",
    category: "incident-governance",
    dataContracts: ["OperatingSystemStage", "IncidentAutomationRule", "IncidentBatch", "EscalationPolicy", "SourceEvidence"],
    requiredStates: ["enabled", "candidate", "incident-created", "suppressed", "approval-needed", "mobile"],
    validation: ["dashboard:v55:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Incident automation route served by the Hermes dashboard app.",
  },
  {
    route: "/live-secret-scan",
    title: "Live Secret Presence Scan",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "secret-governance",
    dataContracts: ["OperatingSystemStage", "SecretPresenceScan", "SecretName", "SecretScope", "DeployKeyPosture"],
    requiredStates: ["present", "missing", "wrong-scope", "rotating", "approval-needed", "mobile"],
    validation: ["dashboard:v56:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Live secret scan route served by the Hermes dashboard app.",
  },
  {
    route: "/cost-reconciliation",
    title: "Cost Reconciliation Import",
    recipe: "operations-control-room",
    owner: "Finance",
    category: "finance-governance",
    dataContracts: ["OperatingSystemStage", "CostRateSheet", "InvoiceImport", "UsageCounter", "ActualCostRecord"],
    requiredStates: ["estimated", "actual", "blended", "missing-rate", "reconciled", "mobile"],
    validation: ["dashboard:v57:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Cost reconciliation route served by the Hermes dashboard app.",
  },
  {
    route: "/outcome-learning-feeds",
    title: "Outcome Learning Feeds",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "learning-governance",
    dataContracts: ["OperatingSystemStage", "OutcomeFeed", "LearningBatch", "SourceEvidence", "PolicyRecommendation"],
    requiredStates: ["ingested", "candidate", "finding", "policy-proposed", "approval-needed", "mobile"],
    validation: ["dashboard:v58:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Outcome learning feeds route served by the Hermes dashboard app.",
  },
  {
    route: "/golden-eval-execution",
    title: "Golden Eval Execution",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "eval-governance",
    dataContracts: ["OperatingSystemStage", "GoldenTaskRun", "ProviderScore", "EvalVerdict", "RoutingRecommendation"],
    requiredStates: ["queued", "running", "passed", "failed", "insufficient-data", "mobile"],
    validation: ["dashboard:v59:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Golden eval execution route served by the Hermes dashboard app.",
  },
  {
    route: "/hard-breaker-enforcement",
    title: "Hard Circuit Breaker Enforcement",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "autonomy-governance",
    dataContracts: ["OperatingSystemStage", "BreakerCheck", "KillSwitch", "BudgetBreaker", "ExecutionBlock"],
    requiredStates: ["allowed", "blocked", "tripped", "disabled", "audited", "mobile"],
    validation: ["dashboard:v60:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Hard breaker enforcement route served by the Hermes dashboard app.",
  },
  {
    route: "/network-runner-adapter",
    title: "Network Runner Adapter",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "production-governance",
    dataContracts: ["OperatingSystemStage", "NetworkRunnerAdapter", "ProbePlan", "ProbeResult", "ScreenshotArtifact"],
    requiredStates: ["planned", "approved", "running", "passed", "failed", "mobile"],
    validation: ["dashboard:v61:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Network runner adapter route served by the Hermes dashboard app.",
  },
  {
    route: "/hetzner-ssh-adapter",
    title: "Hetzner SSH Adapter",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "deployment-governance",
    dataContracts: ["OperatingSystemStage", "HetznerSshAdapter", "RemoteCommandPlan", "CommandReceipt", "RollbackArtifact"],
    requiredStates: ["planned", "approved", "executed", "failed", "rolled-back", "mobile"],
    validation: ["dashboard:v62:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Hetzner SSH adapter route served by the Hermes dashboard app.",
  },
  {
    route: "/secret-provider-adapter",
    title: "Secret Provider Adapter",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "secret-governance",
    dataContracts: ["OperatingSystemStage", "SecretProviderAdapter", "PresenceRecord", "ScopeRecord", "RotationFinding"],
    requiredStates: ["present", "missing", "wrong-scope", "rotation-due", "redacted", "mobile"],
    validation: ["dashboard:v63:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Secret provider adapter route served by the Hermes dashboard app.",
  },
  {
    route: "/billing-provider-adapter",
    title: "Billing Provider Adapter",
    recipe: "cost-capacity-dashboard",
    owner: "Finance",
    category: "finance-governance",
    dataContracts: ["OperatingSystemStage", "BillingProviderAdapter", "UsageImport", "InvoiceArtifact", "CostAllocation"],
    requiredStates: ["manual", "imported", "estimated", "actual", "reconciled", "mobile"],
    validation: ["dashboard:v64:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Billing provider adapter route served by the Hermes dashboard app.",
  },
  {
    route: "/project-outcome-emitter",
    title: "Project Outcome Emitter",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "learning-governance",
    dataContracts: ["OperatingSystemStage", "ProjectOutcomeEmitter", "OutcomeEvent", "SourceEvidence", "LearningCandidate"],
    requiredStates: ["emitted", "received", "invalid", "deduped", "policy-proposed", "mobile"],
    validation: ["dashboard:v65:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Project outcome emitter route served by the Hermes dashboard app.",
  },
  {
    route: "/provider-eval-runner",
    title: "Provider Eval Runner",
    recipe: "research-intelligence-dashboard",
    owner: "Hermes",
    category: "eval-governance",
    dataContracts: ["OperatingSystemStage", "ProviderEvalRunner", "GoldenTaskRun", "EvalArtifact", "SpendCheck"],
    requiredStates: ["queued", "approved", "running", "scored", "blocked", "mobile"],
    validation: ["dashboard:v66:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Provider eval runner route served by the Hermes dashboard app.",
  },
  {
    route: "/breaker-middleware",
    title: "Breaker Middleware SDK",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "autonomy-governance",
    dataContracts: ["OperatingSystemStage", "BreakerMiddleware", "ExecutionContext", "BreakerResult", "BlockEvidence"],
    requiredStates: ["allowed", "blocked", "tripped", "bypassed", "audited", "mobile"],
    validation: ["dashboard:v67:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Breaker middleware route served by the Hermes dashboard app.",
  },
  {
    route: "/incident-subscriptions",
    title: "Incident Subscription Bus",
    recipe: "operations-control-room",
    owner: "Operations",
    category: "incident-governance",
    dataContracts: ["OperatingSystemStage", "IncidentSubscription", "DedupeKey", "SuppressionRule", "EscalationTarget"],
    requiredStates: ["subscribed", "suppressed", "incident-created", "deduped", "approval-needed", "mobile"],
    validation: ["dashboard:v68:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Incident subscription route served by the Hermes dashboard app.",
  },
  {
    route: "/evidence-artifact-store",
    title: "Evidence Artifact Store",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "evidence-governance",
    dataContracts: ["OperatingSystemStage", "EvidenceArtifact", "ArtifactPointer", "RetentionPolicy", "ContentHash"],
    requiredStates: ["indexed", "missing", "expired", "retained", "linked", "mobile"],
    validation: ["dashboard:v69:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Evidence artifact store route served by the Hermes dashboard app.",
  },
  {
    route: "/release-train-orchestrator",
    title: "Release Train Orchestrator",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "deployment-governance",
    dataContracts: ["OperatingSystemStage", "ReleaseTrain", "PromotionGate", "SweepEvidence", "ReleaseSummary"],
    requiredStates: ["planned", "approved", "promoted", "verified", "rolled-back", "mobile"],
    validation: ["dashboard:v70:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Release train route served by the Hermes dashboard app.",
  },
  {
    route: "/production-screenshot-runner",
    title: "Production Screenshot Runner",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "production-governance",
    dataContracts: ["OperatingSystemStage", "ProductionScreenshotRunner", "ScreenshotArtifact", "ViewportCheck", "BlankPageSignal"],
    requiredStates: ["planned", "approved", "captured", "blank", "failed", "mobile"],
    validation: ["dashboard:v71:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Production screenshot runner route served by the Hermes dashboard app.",
  },
  {
    route: "/hetzner-promotion-transport",
    title: "Hetzner Promotion Transport",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "deployment-governance",
    dataContracts: ["OperatingSystemStage", "HetznerPromotionTransport", "SshReceipt", "PromotionScriptRun", "RollbackEvidence"],
    requiredStates: ["planned", "approved", "executed", "failed", "rolled-back", "mobile"],
    validation: ["dashboard:v72:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Hetzner promotion transport route served by the Hermes dashboard app.",
  },
  {
    route: "/server-secret-posture-scanner",
    title: "Server Secret Posture Scanner",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "secret-governance",
    dataContracts: ["OperatingSystemStage", "ServerSecretManifest", "SecretPresenceResult", "RotationMetadata"],
    requiredStates: ["present", "missing", "unknown", "rotation-due", "redacted", "mobile"],
    validation: ["dashboard:v73:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Server secret posture scanner route served by the Hermes dashboard app.",
  },
  {
    route: "/incident-notification-fanout",
    title: "Incident Notification Fanout",
    recipe: "operations-control-room",
    owner: "Operations",
    category: "incident-governance",
    dataContracts: ["OperatingSystemStage", "IncidentNotificationTarget", "FanoutAttempt", "DedupeWindow", "Acknowledgement"],
    requiredStates: ["enabled", "dispatched", "deduped", "acknowledged", "failed", "mobile"],
    validation: ["dashboard:v74:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Incident notification fanout route served by the Hermes dashboard app.",
  },
  {
    route: "/durable-artifact-backend",
    title: "Durable Artifact Backend",
    recipe: "operations-control-room",
    owner: "Hermes",
    category: "evidence-governance",
    dataContracts: ["OperatingSystemStage", "ArtifactBackend", "ArtifactWriteResult", "RetentionPolicy", "StorageUsage"],
    requiredStates: ["configured", "missing", "retained", "expired", "cleanup-needed", "mobile"],
    validation: ["dashboard:v75:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Durable artifact backend route served by the Hermes dashboard app.",
  },
  {
    route: "/remaining-project-outcome-adapters",
    title: "Remaining Project Outcome Adapters",
    recipe: "operations-control-room",
    owner: "Project teams",
    category: "learning-governance",
    dataContracts: ["OperatingSystemStage", "OutcomeAdapterAdoption", "DashboardManifest", "OutcomeEndpointCheck"],
    requiredStates: ["adopted", "missing", "partial", "stale", "blocked", "mobile"],
    validation: ["dashboard:v76:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Remaining project outcome adapters route served by the Hermes dashboard app.",
  },
  {
    route: "/breaker-middleware-rollout",
    title: "Breaker Middleware Rollout",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "autonomy-governance",
    dataContracts: ["OperatingSystemStage", "BreakerRolloutRecord", "LivePathClass", "BlockTestResult"],
    requiredStates: ["wrapped", "missing", "blocked", "tested", "bypassed", "mobile"],
    validation: ["dashboard:v77:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Breaker middleware rollout route served by the Hermes dashboard app.",
  },
  {
    route: "/provider-eval-execution",
    title: "Provider Eval Execution",
    recipe: "research-intelligence-dashboard",
    owner: "Hermes",
    category: "eval-governance",
    dataContracts: ["OperatingSystemStage", "ProviderEvalExecution", "GoldenTask", "ScoredArtifact", "BudgetBreaker"],
    requiredStates: ["queued", "approved", "running", "scored", "blocked", "mobile"],
    validation: ["dashboard:v78:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Provider eval execution route served by the Hermes dashboard app.",
  },
  {
    route: "/billing-provider-integrations",
    title: "Billing Provider Integrations",
    recipe: "cost-capacity-dashboard",
    owner: "Finance",
    category: "finance-governance",
    dataContracts: ["OperatingSystemStage", "BillingProviderIntegration", "UsageImport", "InvoiceVariance", "ActualCostRecord"],
    requiredStates: ["manual", "imported", "reconciled", "variance", "missing-api", "mobile"],
    validation: ["dashboard:v79:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Billing provider integrations route served by the Hermes dashboard app.",
  },
  {
    route: "/release-train-execution",
    title: "Release Train Execution",
    recipe: "system-health-deployment",
    owner: "Operations",
    category: "deployment-governance",
    dataContracts: ["OperatingSystemStage", "ReleaseTrainExecution", "HardGateResult", "PromotionOrder", "FinalReleaseReport"],
    requiredStates: ["planned", "approved", "running", "stopped", "verified", "mobile"],
    validation: ["dashboard:v80:validate", "dashboard:visual:check", "build --workspace web"],
    localOnlyReason: "Release train execution route served by the Hermes dashboard app.",
  },
];

export function dashboardMetadataForRoute(route: string) {
  return dashboardPageMetadata.find((entry) => entry.route === route);
}
