from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol, runtime_checkable

from .cancellation import CallTurnCancelled, CancellationScope  # re-exported; part of the contract
from .types import (
    AudioFrame, BrainEvent, CallTurnRecord, FlushResult, InterruptionDecision,
    InterruptionSignal, MediaFormat, PlaybackMark, StreamingCallContext,
    TranscriptEvent, TtsAudioEvent, TurnEvent,
)

__all__ = [
    "CallTurnCancelled", "AudioTransportPort", "TurnDetectionPort",
    "InterruptionPolicyPort", "SpeechToTextPort", "TextToSpeechPort",
    "HermesBrainPort", "StreamingCallTracerPort",
]


@runtime_checkable
class AudioTransportPort(Protocol):
    @property
    def media(self) -> MediaFormat: ...
    async def push_inbound(self, frame: AudioFrame) -> None: ...
    def inbound(self) -> AsyncIterator[AudioFrame]: ...
    async def emit_outbound(self, frame: AudioFrame) -> None: ...
    async def flush_outbound(self, reason: str) -> FlushResult: ...
    async def close(self) -> None: ...


@runtime_checkable
class TurnDetectionPort(Protocol):
    async def observe(self, frame: AudioFrame) -> tuple[TurnEvent, ...]: ...
    def reset(self) -> None: ...


@runtime_checkable
class InterruptionPolicyPort(Protocol):
    def decide(self, signal: InterruptionSignal) -> InterruptionDecision: ...


@runtime_checkable
class SpeechToTextPort(Protocol):
    async def start(self, ctx: StreamingCallContext) -> None: ...
    async def push(self, frame: AudioFrame) -> None: ...
    def events(self) -> AsyncIterator[TranscriptEvent]: ...
    async def finalize(self) -> TranscriptEvent | None: ...
    async def cancel(self) -> None: ...
    async def close(self) -> None: ...


@runtime_checkable
class TextToSpeechPort(Protocol):
    def synthesize(
        self, text: str, ctx: StreamingCallContext, scope: CancellationScope
    ) -> AsyncIterator[TtsAudioEvent]: ...
    async def cancel(self) -> None: ...
    async def flush(self) -> None: ...


@runtime_checkable
class HermesBrainPort(Protocol):
    def respond(
        self, turn: TranscriptEvent, ctx: StreamingCallContext, scope: CancellationScope
    ) -> AsyncIterator[BrainEvent]: ...


@runtime_checkable
class StreamingCallTracerPort(Protocol):
    def transcript(self, event: TranscriptEvent) -> None: ...
    def turn(self, event: TurnEvent) -> None: ...
    def brain(self, event: BrainEvent) -> None: ...
    def playback(self, mark: PlaybackMark) -> None: ...
    def interruption(self, decision: InterruptionDecision, heard: str, abandoned: str) -> None: ...
    def turn_committed(self, record: CallTurnRecord) -> None: ...
