package com.tencent.qidian.tmc.auth;

/**
 * Verifies webhook callback signatures.
 */
public interface WebhookSigner {
    /**
     * Verify callback sign generated by url + '&' + cur_time.
     */
    boolean verify(String url, String curTime, String providedSign, String secretKey);
}
