name: Sync to Gitea

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: wearerequired/git-mirror-action@master
        with:
          source-repo: ${{ github.repository }}
          destination-repo: ${{ secrets.GITEA_URL }}
          destination-token: ${{ secrets.GITEA_TOKEN }}
          force-push: true